/*
** $Id: binpack.c, initiated September 23, 2026 $
** Binary String Pack/Unpack library, a TLV binary encoder (Type-Length-Value)
** See Copyright Notice in agena.h
** Mostly generated by Gemini AI.
*/

/*

str := binpack.pack(1, 'alex', 2*Pi, Pi!E, true, false, null, fail, long.Pi, ints.int64(10), dd.new(2.1));
L := [1 ~ 1, 2 ~ 'alex', 3 ~ 6.2831853071796,
   4 ~ 3.1415926535898+2.718281828459*I, 5 ~ true, 6 ~ false, 7 ~ null, 8 ~ fail, 9 ~ long.Pi, 10 ~ ints.int64(10), 11 ~ dd.new(2.1)];
K := binpack.unpack(str);
for i to size L do
   if L[i] ~<> K[i] then print(i, L[i], K[i]) fi
od;

b := binpack.new()
b@@chars('alex')
b@@int32(-10)
b@@uint16(16)
b@@uint32(32)
b@@double(Pi)
b@@cdouble(E!Pi)
b@@longdouble(long.Pi)
b@@int64(ints.int64(10))
b@@dd(dd.new(2.1))

str := b@@tostring();

binpack.unpack(str):

 ~= ['alex', -10, 16, 32, 3.1415926535898, E!Pi, long.Pi, ints.int64(10), dd.new(2.1)]:
binpack.unpack(b@@dump()) ~= ['alex', -10, 16, 32, 3.1415926535898, E!Pi, long.Pi, ints.int64(10), dd.new(2.1)]:
clear b;

*/

#define binpack_c
#define LUA_LIB

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>

#include "agena.h"
#include "agnxlib.h"
#include "agenalib.h"
#include "ddmath.h"
#include "ints.h"
#include "long.h"


#if !(defined(__DJGPP__) || defined(__OS2__) || defined(LUA_ANSI))
#define AGENA_BINPACKLIBNAME "binpack"
LUALIB_API int (luaopen_binpack) (lua_State *L);
#endif


/* Define Type Tags matching specification */
typedef enum {
  TAG_NULL          = 0,
  TAG_INT32         = 1,
  TAG_DOUBLE        = 2,
  TAG_STRING        = 3,
  TAG_SHORT_STRING  = 4,
  TAG_MEDIUM_STRING = 5,
  TAG_COMPLEX       = 6,
  TAG_BOOL          = 7,
  TAG_UINT8         = 8,
  TAG_UINT16        = 9,
  TAG_UINT32        = 10,
  TAG_LONGDOUBLE    = 11,
  TAG_INT64         = 12,
  TAG_DD            = 13
} DataTypeTag;

/*
===============================================================================
  PACKING IMPLEMENTATION (Uses a standard dynamic byte buffer)
===============================================================================
*/
typedef struct {
  uint8_t *data;
  size_t size;
  size_t cap;
} Buffer;

/* static Buffer *binpack_newbuffer (void) {
  Buffer *b = (Buffer *)malloc(sizeof(Buffer));
  binpack_init(b);
  return b;
} */

static void binpack_init (Buffer *b) {
  if (b == NULL) return;
  b->data = NULL;
  b->size = 0;
  b->cap  = 0;
}

static void buf_ensure (Buffer *b, size_t len) {
  if (b->size + len > b->cap) {
    while (b->size + len > b->cap) b->cap = b->cap ? b->cap * 2 : 64;
    b->data = (uint8_t*)realloc(b->data, b->cap);
  }
}

/* --- PACKING FUNCTIONS --- */

static void pack_int32 (Buffer *buf, int32_t val) {
  size_t total_needed = sizeof(uint8_t) + sizeof(int32_t);
  #if BYTE_ORDER == BIG_ENDIAN
  val = tools_swapi32(val);
  #endif
  buf_ensure(buf, total_needed);
  buf->data[buf->size++] = TAG_INT32;
  memcpy(buf->data + buf->size, &val, sizeof(int32_t));
  buf->size += sizeof(int32_t);
}

static void pack_int64 (Buffer *buf, int64_t val) {
  size_t total_needed = sizeof(uint8_t) + sizeof(int64_t);
  #if BYTE_ORDER == BIG_ENDIAN
  val = tools_swapi64(val);
  #endif
  buf_ensure(buf, total_needed);
  buf->data[buf->size++] = TAG_INT64;
  memcpy(buf->data + buf->size, &val, sizeof(int64_t));
  buf->size += sizeof(int64_t);
}

static void pack_double (Buffer *buf, double val) {
  size_t total_needed = sizeof(uint8_t) + sizeof(double);
  #if BYTE_ORDER == BIG_ENDIAN
  val = tools_tolittleendian(val);
  #endif
  buf_ensure(buf, total_needed);
  buf->data[buf->size++] = TAG_DOUBLE;
  memcpy(buf->data + buf->size, &val, sizeof(double));
  buf->size += sizeof(double);
}

#ifndef PROPCMPLX
static void pack_complex (Buffer *buf, agn_Complex val) {
  size_t total_needed = sizeof(uint8_t) + sizeof(agn_Complex);
  #if BYTE_ORDER == BIG_ENDIAN
  __real__ val = tools_tolittleendian(creal(val));
  __imag__ val = tools_tolittleendian(cimag(val));
  #endif
  buf_ensure(buf, total_needed);
  buf->data[buf->size++] = TAG_COMPLEX;
  memcpy(buf->data + buf->size, &val, sizeof(agn_Complex));
  buf->size += sizeof(agn_Complex);
}
#else
static void pack_complex (Buffer *buf, lua_Number val[2]) {
  size_t total_needed = sizeof(uint8_t) + 2*sizeof(lua_Number);
  #if BYTE_ORDER == BIG_ENDIAN
  __real__ val[0] = tools_tolittleendian(val[0]);
  __imag__ val[1] = tools_tolittleendian(val[1]);
  #endif
  buf_ensure(buf, total_needed);
  buf->data[buf->size++] = TAG_COMPLEX;
  memcpy(buf->data + buf->size, val, 2*sizeof(lua_Number));
  buf->size += 2*sizeof(lua_Number);
}
#endif


static void pack_dd (Buffer *buf, dd_pair val) {
  size_t total_needed = sizeof(uint8_t) + sizeof(dd_pair);
  buf_ensure(buf, total_needed);
  buf->data[buf->size++] = TAG_DD;
  memcpy(buf->data + buf->size, &val, sizeof(dd_pair));
  buf->size += sizeof(dd_pair);
}

#ifndef __ARMCPU
static void pack_longdouble (Buffer *buf, long double val) {
  /* Force exactly 10 bytes of allocation space (1-byte tag + 10-byte payload) */
  size_t total_needed = sizeof(uint8_t) + 10;
  buf_ensure(buf, total_needed);
  buf->data[buf->size++] = TAG_LONGDOUBLE;
  /* Copy ONLY the 10 real data bytes, ignoring any trailing compiler padding */
  memcpy(buf->data + buf->size, &val, 10);
  buf->size += 10;
}
#endif

/* char val: 0 = false, 1 = true, -1 = fail */
static void pack_bool (Buffer *buf, char val) {
  size_t total_needed = sizeof(uint8_t) + sizeof(uint8_t);  /* tag + 1-byte value */
  buf_ensure(buf, total_needed);
  buf->data[buf->size++] = TAG_BOOL;
  buf->data[buf->size++] = (val == -1 || val == 255) ? 2 : val;  /* 255 is for ARM since char is UNSIGNED there [sic !] */
}

static void pack_null (Buffer *buf) {
  size_t total_needed = sizeof(uint8_t);  /* tag only */
  buf_ensure(buf, total_needed);
  buf->data[buf->size++] = TAG_NULL;
}

static void pack_uchar (Buffer *buf, unsigned char val) {
  size_t total_needed = sizeof(uint8_t) + sizeof(uint8_t);  /* tag + 1-byte value */
  buf_ensure(buf, total_needed);
  buf->data[buf->size++] = TAG_UINT8;
  buf->data[buf->size++] = val;
}

static void pack_uint16 (Buffer *buf, uint16_t val) {
  size_t total_needed = sizeof(uint8_t) + sizeof(uint16_t);  /* tag + 1-byte value */
  #if BYTE_ORDER == BIG_ENDIAN
  val = tools_swapuint16(val);
  #endif
  buf_ensure(buf, total_needed);
  buf->data[buf->size++] = TAG_UINT16;
  memcpy(buf->data + buf->size, &val, sizeof(uint16_t));
  buf->size += sizeof(uint16_t);
}

static void pack_uint32 (Buffer *buf, uint32_t val) {
  size_t total_needed = sizeof(uint8_t) + sizeof(uint32_t);  /* tag + 1-byte value */
  #if BYTE_ORDER == BIG_ENDIAN
  val = tools_swapuint32(val);
  #endif
  buf_ensure(buf, total_needed);
  buf->data[buf->size++] = TAG_UINT32;
  memcpy(buf->data + buf->size, &val, sizeof(uint32_t));
  buf->size += sizeof(uint32_t);
}

static void pack_string (Buffer *buf, const char *str, size_t len) {
  if (len < 256) {
    uint8_t short_len = (uint8_t)len;
    size_t total_needed = sizeof(uint8_t) + sizeof(uint8_t) + short_len;
    buf_ensure(buf, total_needed);
    buf->data[buf->size++] = TAG_SHORT_STRING;
    buf->data[buf->size++] = short_len;
    memcpy(buf->data + buf->size, str, short_len);
    buf->size += short_len;
  } else if (len < 65536) {
    uint16_t medium_len = (uint16_t)len;
    size_t total_needed = sizeof(uint8_t) + sizeof(uint16_t) + medium_len;
    buf_ensure(buf, total_needed);
    buf->data[buf->size++] = TAG_MEDIUM_STRING;
    #if BYTE_ORDER == BIG_ENDIAN
    medium_len = tools_swapuint16(medium_len);
    #endif
    memcpy(buf->data + buf->size, &medium_len, sizeof(uint16_t));
    buf->size += sizeof(uint16_t);
    memcpy(buf->data + buf->size, str, (uint16_t)len);
    buf->size += medium_len;
  } else {
    uint32_t long_len = (uint32_t)len;
    size_t total_needed = sizeof(uint8_t) + sizeof(uint32_t) + long_len;
    buf_ensure(buf, total_needed);
    buf->data[buf->size++] = TAG_STRING;
    #if BYTE_ORDER == BIG_ENDIAN
    long_len = tools_swapuint32(long_len);
    #endif
    memcpy(buf->data + buf->size, &long_len, sizeof(uint32_t));
    buf->size += sizeof(uint32_t);
    memcpy(buf->data + buf->size, str, (uint32_t)len);
    buf->size += long_len;
  }
}


/****************************************************************************
 *** Package functions ******************************************************
 **************************************************************************** */

static int binpack_uchar (lua_State* L) {
  int i, nargs = lua_gettop(L);
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  for (i=2; i <= nargs; i++) {
    uint8_t val = (uint8_t)(luaL_checkinteger(L, i) & 0xFF);
    pack_uchar(b, val);
  }
  lua_settop(L, 1);
  return 1;  /* Return self for chaining */
}


static int binpack_uint16 (lua_State* L) {
  int i, nargs = lua_gettop(L);
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  for (i=2; i <= nargs; i++) {
    uint16_t val = (uint16_t)(luaL_checkinteger(L, i) & 0xFFFF);
    pack_uint16(b, val);
  }
  lua_settop(L, 1);
  return 1;  /* Return self for chaining */
}


static int binpack_uint32 (lua_State* L) {
  int i, nargs = lua_gettop(L);
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  for (i=2; i <= nargs; i++) {
    uint32_t val = (uint32_t)luaL_checkinteger(L, i) & 0xFFFFFFFF;
    pack_uint32(b, val);
  }
  lua_settop(L, 1);
  return 1;  /* return self for chaining */
}


static int binpack_int32 (lua_State* L) {
  int i, nargs = lua_gettop(L);
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  for (i=2; i <= nargs; i++) {
    int32_t val = (int32_t)luaL_checkinteger(L, i);
    pack_int32(b, val);
  }
  lua_settop(L, 1);
  return 1;  /* return self for chaining */
}


static int binpack_int64 (lua_State* L) {
  int i, nargs = lua_gettop(L);
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  for (i=2; i <= nargs; i++) {
    if (!isints(L, i))
      luaL_error(L, "Error in " LUA_QS ": expected an " LUA_QS " userdata value.", "binpack.int64", "ints");
    int64_t val = getint64value(L, i);
    pack_int64(b, val);
  }
  lua_settop(L, 1);
  return 1;  /* return self for chaining */
}


static int binpack_double (lua_State* L) {
  int i, nargs = lua_gettop(L);
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  for (i=2; i <= nargs; i++) {
    double val = (double)luaL_checknumber(L, i);
    pack_double(b, val);
  }
  lua_settop(L, 1);
  return 1;  /* Return self for chaining */
}


#ifndef __ARMCPU
static int binpack_longdouble (lua_State* L) {
  #if BYTE_ORDER == BIG_ENDIAN
  luaL_error(L, "Error in " LUA_QS ": cannot use this function on Big Endian systems.", "binpack.longdouble");
  #endif
  int i, nargs = lua_gettop(L);
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  for (i=2; i <= nargs; i++) {
    long double val = checkandgetdlong(L, i);
    pack_longdouble(b, val);
  }
  lua_settop(L, 1);
  return 1;  /* Return self for chaining */
}
#endif


static int binpack_cdouble (lua_State* L) {
  int i, nargs = lua_gettop(L);
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  for (i=2; i <= nargs; i++) {
#ifndef PROPCMPLX
    agn_Complex z = agn_checkcomplex(L, i);
#else
    lua_Number *z = agn_checkcomplex(L, i);
#endif
    pack_complex(b, z);
  }
  lua_settop(L, 1);
  return 1;  /* Return self for chaining */
}


static int binpack_dd (lua_State* L) {
  int i, nargs = lua_gettop(L);
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  for (i=2; i <= nargs; i++) {
    dd_pair z = *checkdd(L, i);
    #if BYTE_ORDER == BIG_ENDIAN
    z.hi = tools_tolittleendian(z.hi);
    z.lo = tools_tolittleendian(z.lo);
    #endif
    pack_dd(b, z);
  }
  lua_settop(L, 1);
  return 1;  /* Return self for chaining */
}


static int binpack_bool (lua_State* L) {
  int i, nargs = lua_gettop(L);
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  for (i=2; i <= nargs; i++) {
    luaL_checktype(L, i, LUA_TBOOLEAN);
    pack_bool(b, lua_toboolean(L, i));
  }
  lua_settop(L, 1);
  return 1;  /* Return self for chaining */
}


static int binpack_nil (lua_State* L) {
  int i, nargs = lua_gettop(L);
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  for (i=2; i <= nargs; i++) {
    luaL_checktype(L, i, LUA_TNIL);
    pack_null(b);
  }
  lua_settop(L, 1);
  return 1;  /* Return self for chaining */
}


static int binpack_chars (lua_State* L) {
  int i, nargs = lua_gettop(L);
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  for (i=2; i <= nargs; i++) {
    size_t len;
    const char* str = luaL_checklstring(L, i, &len);
    pack_string(b, str, len);
  }
  lua_settop(L, 1);
  return 1;  /* Return self for chaining */
}


static int binpack_tostring (lua_State* L) {
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  lua_pushlstring(L, (const char*)b->data, b->size);
  return 1;
}


/*** Metamethods ***/

static int mt_tostring (lua_State *L) {  /* at the console, the ud is formatted as follows: */
  if (luaL_isudata(L, 1, AGENA_BINPACKLIBNAME))
    lua_pushfstring(L, "%s(%p)", AGENA_BINPACKLIBNAME, lua_topointer(L, 1));
  else {
    void *p = lua_touserdata(L, 1);
    lua_pushfstring(L, (p != NULL) ? "userdata(%p)" : "unknown(%p)", lua_topointer(L, 1));
  }
  return 1;
}


static int mt_gc (lua_State* L) {
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  if (b->data) free(b->data);
  return 0;
}


/*
===============================================================================
  UNPACKING IMPLEMENTATION (Malloc-Free / Directly populates Lua structures)
===============================================================================
*/

static int binpack_new (lua_State* L) {
  Buffer *b = (Buffer *)lua_newuserdata(L, sizeof(Buffer));
  if (!b)
    return luaL_error(L, "Error in " LUA_QS ": memory allocation failed.", "binpack.new");
  binpack_init(b);
  lua_setmetatabletoobject(L, -1, AGENA_BINPACKLIBNAME, 1);
  return 1;
}


static void aux_pack (lua_State *L, Buffer *buf, int idx) {
  int type = lua_type(L, idx);
  switch (type) {
    case LUA_TNUMBER: {
      double num = agn_tonumber(L, idx);
      if (tools_isint(num)) {
        if (num >= 0.0) {
          if (num <= 255.0) {
            pack_uchar(buf, (unsigned char)num); return;
          } else if (num <= 65535.0) {
            pack_uint16(buf, (uint16_t)num); return;
          } else if (num <= 4294967295.0) {
            pack_uint32(buf, (uint32_t)num); return;
          }
        } else if (num >= -2147483648.0 && num <= 2147483647.0) {
          pack_int32(buf, (int32_t)num); return;
        }
      }
      pack_double(buf, num);
      break;
    }
    case LUA_TSTRING: {
      size_t len;
      const char *str = lua_tolstring(L, idx, &len);
      pack_string(buf, str, len);
      break;
    }
    case LUA_TBOOLEAN: {
      pack_bool(buf, lua_toboolean(L, idx));
      break;
    }
    case LUA_TNIL: {
      pack_null(buf);
      break;
    }
    case LUA_TCOMPLEX: {
#ifndef PROPCMPLX
      agn_Complex z = agn_tocomplex(L, idx);
#else
      lua_Number z[2];
      lua_Number re, im;
      agn_getcmplxparts(L, idx, &re, &im);
      z[0] = re; z[1] = im;
#endif
      pack_complex(buf, z);
      break;
    }
    case LUA_TUSERDATA: {
      if (isints(L, idx)) {
        pack_int64(buf, getint64value(L, idx));
#ifndef __ARMCPU
      } else if (isdlong(L, idx)) {
        pack_longdouble(buf, getdlongvalue(L, idx));
#endif
      } else if (isdd(L, idx)) {
        pack_dd(buf, getdd(L, idx));
      } else {
        luaL_error(L, "Error in " LUA_QS ": unsupported data type at argument index %d.",
                      "binpack.pack", idx);
        return;
      }
      break;
    }
    default: {
      if (buf->data) { xfree(buf->data); buf->data = NULL; }
      luaL_error(L, "Error in " LUA_QS ": unsupported data type '%s' at argument index %d.",
                    "binpack.pack", lua_typename(L, type), idx);
    }
  }
}

static int binpack_pack (lua_State* L) {
  int i, nargs = lua_gettop(L);
  if (nargs == 0) {
    luaL_error(L, "Error in " LUA_QS ": need at least one argument.", "binpack.pack");
    return 1;
  }
  Buffer buf;
  binpack_init(&buf);
  if (lua_istable(L, 1)) {
    int sz = luaL_getn(L, 1);
    for (i=1; i <= sz; i++) {
      lua_rawgeti(L, 1, i);
      aux_pack(L, &buf, -1);
      agn_poptop(L);
    }
  } else if (lua_isseq(L, 1)) {
    size_t i, sz = agn_seqsize(L, 1);
    for (i=1; i <= sz; i++) {
      lua_seqrawgeti(L, 1, i);
      aux_pack(L, &buf, -1);
      agn_poptop(L);
    }
  } else {
    for (i=1; i <= nargs; i++) {
      aux_pack(L, &buf, i);
    }
  }
  lua_pushlstring(L, (const char*)buf.data, buf.size);
  if (buf.data) {
    xfree(buf.data);
  }
  return 1;
}


static int binpack_unpack (lua_State* L) {
  size_t bin_len;
  const uint8_t *buf = (const uint8_t*)luaL_checklstring(L, 1, &bin_len);
  size_t offset = 0;
  int index = 1;
  luaL_checkstack(L, 2, "not enough stack space");
  lua_createtable(L, 0, 0);
  while (offset < bin_len) {
    uint8_t tag = buf[offset++];
    if (tag == TAG_INT32) {
      if (offset + sizeof(int32_t) > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      int32_t val;
      memcpy(&val, buf + offset, sizeof(int32_t));
      #if BYTE_ORDER == BIG_ENDIAN  /* symmetric operation */
      val = tools_swapi32(val);
      #endif
      offset += sizeof(int32_t);
      lua_pushinteger(L, val);
    } else if (tag == TAG_UINT16) {
      if (offset + sizeof(uint16_t) > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      uint16_t val;
      memcpy(&val, buf + offset, sizeof(uint16_t));
      #if BYTE_ORDER == BIG_ENDIAN  /* symmetric operation */
      val = tools_swapuint16(val);
      #endif
      offset += sizeof(uint16_t);
      lua_pushinteger(L, val);
    } else if (tag == TAG_UINT32) {
      if (offset + sizeof(uint32_t) > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      uint32_t val;
      memcpy(&val, buf + offset, sizeof(uint32_t));
      #if BYTE_ORDER == BIG_ENDIAN  /* symmetric operation */
      val = tools_swapuint32(val);
      #endif
      offset += sizeof(uint32_t);
      lua_pushinteger(L, val);
    } else if (tag == TAG_INT64) {
      if (offset + sizeof(int64_t) > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      int64_t val;
      memcpy(&val, buf + offset, sizeof(int64_t));
      #if BYTE_ORDER == BIG_ENDIAN  /* symmetric operation */
      val = tools_swapi64(val);
      #endif
      offset += sizeof(int64_t);
      createint64(L, val);
#ifndef __ARMCPU
    } else if (tag == TAG_LONGDOUBLE) {
      /* Ensure the binary buffer has at least 10 bytes left to read */
      if (offset + 10 > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      /* Initialize to 0 to safely clear out any hidden internal padding bytes */
      long double val = 0.0L;
      /* Extract exactly 10 bytes into the local storage target */
      memcpy(&val, buf + offset, 10);
      offset += 10;
      createdlong(L, val);
#endif
    } else if (tag == TAG_DOUBLE) {
      if (offset + sizeof(double) > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      double val;
      memcpy(&val, buf + offset, sizeof(double));
      #if BYTE_ORDER == BIG_ENDIAN  /* symmetric operation */
      val = tools_tolittleendian(val);
      #endif
      offset += sizeof(double);
      lua_pushnumber(L, val);
    } else if (tag == TAG_COMPLEX) {
      if (offset + sizeof(agn_Complex) > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      double real, imag;
      size_t partlen = sizeof(agn_Complex)/2;
      memcpy(&real, buf + offset, partlen); offset += partlen;
      memcpy(&imag, buf + offset, partlen); offset += partlen;
      #if BYTE_ORDER == BIG_ENDIAN  /* symmetric operation */
      real = tools_tolittleendian(real);
      imag = tools_tolittleendian(imag);
      #endif
      agn_pushcomplex(L, real, imag);
    } else if (tag == TAG_DD) {
      if (offset + sizeof(dd_pair) > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      double hi, lo;
      size_t partlen = sizeof(dd_pair)/2;
      memcpy(&hi, buf + offset, partlen); offset += partlen;
      memcpy(&lo, buf + offset, partlen); offset += partlen;
      #if BYTE_ORDER == BIG_ENDIAN  /* symmetric operation */
      hi = tools_tolittleendian(hi);
      lo = tools_tolittleendian(lo);
      #endif
      dd_pushdd(L, (dd_pair){hi, lo});
    } else if (tag == TAG_BOOL) {  /* `fail` has been stored as +2 internally */
      if (offset + 1 > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      uint8_t val = buf[offset++];
      agn_pushboolean(L, (val == 2) ? -1 : val != 0);
    } else if (tag == TAG_NULL) {
      lua_pushnil(L);
    } else if (tag == TAG_UINT8) {
      if (offset + 1 > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      uint8_t val = buf[offset++];
      lua_pushinteger(L, val);
    } else if (tag == TAG_SHORT_STRING) {
      if (offset + 1 > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      uint8_t len = buf[offset++];
      if (offset + len > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      lua_pushlstring(L, (const char*)(buf + offset), len);
      offset += len;
    } else if (tag == TAG_MEDIUM_STRING) {
      if (offset + sizeof(uint16_t) > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      uint16_t len;
      memcpy(&len, buf + offset, sizeof(uint16_t));
      #if BYTE_ORDER == BIG_ENDIAN  /* symmetric operation */
      len = tools_swapuint16(len);
      #endif
      offset += sizeof(uint16_t);
      if (offset + len > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      lua_pushlstring(L, (const char*)(buf + offset), len);
      offset += len;
    } else if (tag == TAG_STRING) {
      if (offset + sizeof(uint32_t) > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      uint32_t len;
      memcpy(&len, buf + offset, sizeof(uint32_t));
      #if BYTE_ORDER == BIG_ENDIAN  /* symmetric operation */
      len = tools_swapuint32(len);
      #endif
      offset += sizeof(uint32_t);
      if (offset + len > bin_len) {
        luaL_error(L, "Error in " LUA_QS ": bounds have been breached.", "binpack.unpack");
        return 1;
      }
      lua_pushlstring(L, (const char*)(buf + offset), len);
      offset += len;
    } else {
      luaL_error(L, "Error in " LUA_QS ": encountered corrupt or invalid type tag %d.", "binpack.unpack", tag);
      return 1;
    }
    /* Store subtable into the parent array: array[index] = subtable */
    lua_rawseti(L, -2, index++);
  }
  return 1; /* Return the master array table */
}


static int binpack_dump (lua_State* L) {
  Buffer *b = (Buffer *)luaL_checkudata(L, 1, AGENA_BINPACKLIBNAME);
  lua_pushlstring(L, (const char*)b->data, b->size);
  uint8_t *renewed_data = (uint8_t*)realloc(b->data, 64);
  if (renewed_data != NULL) {
    b->data = renewed_data;
    b->cap  = 64;
    b->size = 0;
  } else {
    luaL_error(L, "Error in " LUA_QS ": could not resize buffer.", "binpack.dump");
  }
  return 1;
}


static const struct luaL_Reg binpack[] = {
  {"bool",       binpack_bool},
  {"chars",      binpack_chars},
  {"cdouble",    binpack_cdouble},
  {"dd",         binpack_dd},
  {"double",     binpack_double},
  {"dump",       binpack_dump},
  {"int32",      binpack_int32},
  {"int64",      binpack_int64},
#ifndef __ARMCPU
  {"longdouble", binpack_longdouble},
#endif
  {"new",        binpack_new},
  {"nil",        binpack_nil},
  {"pack",       binpack_pack},
  {"uchar",      binpack_uchar},
  {"uint16",     binpack_uint16},
  {"uint32",     binpack_uint32},
  {"unpack",     binpack_unpack},
  {"tostring",   binpack_tostring},
  {NULL, NULL}
};

/*
** Open binpack library
*/

LUALIB_API int luaopen_binpack (lua_State *L) {
  /* Metatable for OOP file handle objects */
  luaL_newmetatable(L, AGENA_BINPACKLIBNAME);
  /* Set metatable.__index = metatable */
  lua_pushvalue(L, -1);
  lua_setfield(L, -2, "__index");
  /* Register the functions directly into the metatable as OOP methods */
  luaL_register(L, NULL, binpack);
  /* Register the special garbage collection destructor into the metatable */
  lua_pushcfunction(L, mt_gc);
  lua_setfield(L, -2, "__gc");
  lua_pushcfunction(L, mt_tostring);
  lua_setfield(L, -2, "__tostring");
  /* Create the procedural global package table (e.g., global 'ads') */
  luaL_register(L, AGENA_BINPACKLIBNAME, binpack);
  return 1;
}
