/* dblhash Library, implements hash sets for Agena numbers.
   This file has been largely generated by Gemini AI, put to the public domain. Initiated January 04, 2026.
   Additions by a_walz are:
   - Checks for memory allocation errors when resizing,
   - support for low-memory slow mode and high-memory fast-mode,
   - Agena C package functions.

   Changing to triangular progression [(i*i + i) >> 1] slows down the package functions by 12 % ! */

/*
watch();
to 10k do
d := dblhash.new(1024)
for i to 2*1024 do
   dblhash.include(d, sin(i))
od
x, y, z := dblhash.has(d, sin(1)), dblhash.has(d, sin(2049)), size d;

for i to 2*1024 do
   dblhash.purge(d, sin(i))
od
x, y := empty d, dblhash.has(d, sin(1));
od;
watch():
# 11.405999898911
*/

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define dblhash_c
#define LUA_LIB

#include "agena.h"

#include "agenalib.h"
#include "agnhlps.h"
#include "agnxlib.h"
#include "dblhash.h"

#define checkdblhash(L,n) (DoubleHashSet *)luaL_checkudata(L, n, AGENA_DBLHASHLIBNAME)
#define isdblhash(L,n)    (luaL_isudata(L, n, AGENA_DBLHASHLIBNAME) && agn_isutypeset(L, n))


/* --- Internal Helper: SplitMix64 Hash --- */
static uint64_t dhs_hash (double val) {
  uint64_t u;
  val += 0.0;  /* if (val == 0.0) val = 0.0;  normalize -0.0, 7.1.9 change */
  memcpy(&u, &val, sizeof(u));
  u = (u^(u >> 30))*0xbf58476d1ce4e5b9ULL;
  u = (u^(u >> 27))*0x94d049bb133111ebULL;
  return u^(u >> 31);
}


/* static uint64_t dhs_hash (double val) {
  uint64_t u;
  val += 0.0;  // Normalize -0.0 to 0.0
  memcpy(&u, &val, sizeof(u));
  // High-entropy pre-scrambler (MurmurHash3 64-bit finalizer) ---
  u ^= u >> 33;
  u *= 0xff51afd7ed558ccdULL;
  u ^= u >> 33;
  u *= 0xc4ceb9fe1a85ec53ULL;
  u ^= u >> 33;
  // Your existing SplitMix64 step (now safe from clustering)
  u = (u ^ (u >> 30)) * 0xbf58476d1ce4e5b9ULL;
  u = (u ^ (u >> 27)) * 0x94d049bb133111ebULL;
  return u ^ (u >> 31);
} */

/* --- Initialize --- */
DoubleHashSet *dhs_create (size_t initial_capacity, int optimised) {
  /* Ensure capacity is at least 8 or the next power of 2 */
  size_t cap = 8;
  while (cap < initial_capacity) cap <<= 1;
  DoubleHashSet *set = malloc(sizeof(DoubleHashSet));
  if (!set) return NULL;
  set->keys = malloc(cap * sizeof(double));
  if (!set->keys) return NULL;
  set->status = calloc(cap, sizeof(SlotStatus));
  if (!set->status) return NULL;
  set->capacity = cap;
  set->count = 0;
  set->optimised = optimised;
  return set;
}


/* Faster than modulo: maps a 64-bit hash to [0, capacity), 6.5.12 by Gemini AI:
   Portable 32-bit reduction (works on almost any C compiler) */
static inline uint32_t aux_reduce32 (uint32_t x, uint32_t N) {
  return (uint32_t)(((uint64_t)x * (uint64_t)N) >> 32);
}

#define aux_getidx(set, h_val) ({ \
  size_t _idx; \
  if ((set)->optimised) \
    _idx = ((uint64_t)(h_val)) & ((set)->capacity - 1); \
  else \
    _idx = aux_reduce32((uint32_t)(h_val), (uint32_t)(set)->capacity); \
  (_idx); \
})

/* --- Internal: Resize/Rehash --- */
static int dhs_resize_to_size (DoubleHashSet *set, size_t new_cap) {
  size_t i, idx, old_cap = set->capacity;
  double *old_keys = set->keys;
  SlotStatus *old_status = set->status;
  /* 1. Allocate new arrays with the specific new capacity */
  double *new_keys = malloc(new_cap * sizeof(double));
  if (new_keys == NULL) return 0;
  /* calloc clears the new status array, setting all slots to DBLHASH_EMPTY */
  SlotStatus *new_status = calloc(new_cap, sizeof(SlotStatus));
  if (new_status == NULL) {
    xfree(new_keys);
    return 0;
  }
  /* 2. Temporarily update the set to the new dimensions */
  set->keys = new_keys;
  set->status = new_status;
  set->capacity = new_cap;
  set->count = 0; /* Reset count; we will increment it as we re-insert */
  /* 3. Re-hash ONLY the occupied items into the new space */
  for (i=0; i < old_cap; i++) {
    if (old_status[i] == DBLHASH_OCCUPIED) {
      uint64_t h = dhs_hash(old_keys[i]);
      idx = aux_getidx(set, h);
      /* Probing in the new table (no tombstones exist yet) */
      while (set->status[idx] == DBLHASH_OCCUPIED) {
        idx++;
        if (idx >= set->capacity) idx = 0;
      }
      set->keys[idx] = old_keys[i];
      set->status[idx] = DBLHASH_OCCUPIED;
      set->count++;
    }
  }
  /* 4. Free the old memory buffers */
  /* Assuming xfreeall is your cleanup macro */
  xfreeall(old_keys, old_status);
  return 1;
}


/* --- Insert --- */
int dhs_insert (DoubleHashSet *set, double val) {
  size_t idx, first_deleted_idx, insert_pos;
  /* Check Load Factor: Grow if > 70% */
  if ((double)set->count / set->capacity > 0.7) {
    size_t new_cap = set->optimised ? (set->capacity << 1) : tools_nextprime(agn_newsize(NULL, set->capacity));
    if (dhs_resize_to_size(set, new_cap) == 0) return 0;
  }
  uint64_t h = dhs_hash(val);
  idx = aux_getidx(set, h);
  first_deleted_idx = (size_t)-1;
  while (set->status[idx] != DBLHASH_EMPTY) {
    if (set->status[idx] == DBLHASH_OCCUPIED) {
      if (set->keys[idx] == val) return 1; /* Already exists */
    }  else if (set->status[idx] == DBLHASH_DELETED) {
      if (first_deleted_idx == (size_t)-1) first_deleted_idx = idx;
    }
    idx++;
    if (idx >= set->capacity) idx = 0;
  }
  insert_pos = (first_deleted_idx != (size_t)-1) ? first_deleted_idx : idx;
  set->keys[insert_pos] = val;
  set->status[insert_pos] = DBLHASH_OCCUPIED;
  set->count++;
  return 1;
}

/* --- Search --- */
bool dhs_contains (DoubleHashSet *set, double val) {
  uint64_t h = dhs_hash(val);
  size_t idx = aux_getidx(set, h);
  /* We loop until we hit an DBLHASH_EMPTY slot */
  while (set->status[idx] != DBLHASH_EMPTY) {
    if (set->status[idx] == DBLHASH_OCCUPIED && set->keys[idx] == val) return true;
    /* Linear Probing: increment and wrap */
    idx++;
    if (idx >= set->capacity) idx = 0;
  }
  return false;
}

/* --- removal --- */
static int dhs_shrink (DoubleHashSet *set) {
  /* Calculate new capacity: usually half of current */
  size_t new_cap;
  if (set->optimised) {
    new_cap = set->capacity >> 1;
  } else {
    /* In memory-saving mode, aim for a prime that results in roughly 40-50% load factor */
    new_cap = tools_nextprime(set->count * 2);
  }
  /* Safety: Don't shrink below a reasonable minimum */
  if (new_cap < 8) return 1;
  /* We can simply call our existing resize logic but with the smaller size */
  /* Note: You may need to tweak your dhs_resize to accept 'new_cap' as an argument */
  return dhs_resize_to_size(set, new_cap);
}

bool dhs_remove (DoubleHashSet *set, double val, int shrink) {
  uint64_t h = dhs_hash(val);
  size_t idx = aux_getidx(set, h);
  /* Search the probe chain */
  while (set->status[idx] != DBLHASH_EMPTY) {
    if (set->status[idx] == DBLHASH_OCCUPIED && set->keys[idx] == val) {
      /* 1. Remove the item */
      set->status[idx] = DBLHASH_DELETED;
      set->count--;
      /* 2. Check for downsizing */
      /* Threshold: Shrink if capacity > 16 and load factor < 12.5% */
      if (shrink && set->capacity > 16 && (double)set->count / set->capacity < 0.125) {
        /* We don't return false if shrinking fails;  the removal was still successful. */
        dhs_shrink(set);
      }
      return true;
    }
    /* Move to the next slot (Linear Probing) */
    idx++;
    if (idx >= set->capacity) idx = 0;
  }
  return false; /* Key not found */
}

void dhs_free (DoubleHashSet *set) {
  xfreeall(set->keys, set->status, set);
}

/* --- Helpers --- */

static size_t dhs_getfirstpossibleidx (DoubleHashSet *set, double val) {
  uint64_t h = dhs_hash(val);
  return aux_getidx(set, h);
}

size_t dhs_getidx (DoubleHashSet *set, double val, int *rc) {
  uint64_t h = dhs_hash(val);
  size_t idx = aux_getidx(set, h);
  *rc = 0; /* Default to not found */
  /* Loop until we hit an DBLHASH_EMPTY slot */
  while (set->status[idx] != DBLHASH_EMPTY) {
    if (set->status[idx] == DBLHASH_OCCUPIED && set->keys[idx] == val) {
      *rc = 1;      /* Found it! */
      return idx;   /* Return the actual position */
    }
    /* Consistent Linear Probing */
    idx++;
    if (idx >= set->capacity) idx = 0;
  }
  return (size_t)-1; /* Return sentinel to indicate not found */
}


/*** Agena C Functions ****************************************************************/

static int dblhash_new (lua_State *L) {
  int optimised;
  DoubleHashSet *u;
  uint32_t n = tools_nextpow2u32(agnL_optposint(L, 1, 8));  /* smallest power of 2 greater than or equal x */
  optimised = agnL_optboolean(L, 2, 0);
  u = (DoubleHashSet *)lua_newuserdata(L, sizeof(DoubleHashSet));
  u->keys = malloc(n * sizeof(double));
  if (u->keys == NULL) {
    agn_poptop(L);
    luaL_error(L, "Error in " LUA_QS ": memory allocation failed.", "dblhash.new");
  }
  u->status = calloc(n, sizeof(SlotStatus));
  if (u->status == NULL) {
    xfree(u->keys);
    agn_poptop(L);
    luaL_error(L, "Error in " LUA_QS ": memory allocation failed.", "dblhash.new");
  }
  u->capacity = n;
  u->count = 0;
  u->optimised = optimised;
  lua_setmetatabletoobject(L, -1, AGENA_DBLHASHLIBNAME, 1);
  lua_createtable(L, 0, 0);  /* create accompanying status table */
  lua_setfenv(L, -2);
  return 1;
}


static int dblhash_include (lua_State *L) {
  if (!dhs_insert(checkdblhash(L, 1), agn_checknumber(L, 2)))
    luaL_error(L, "Error in " LUA_QS ": memory allocation failed.", "dblhash.include");
  return 0;
}


static int dblhash_purge (lua_State *L) {
  DoubleHashSet *u = checkdblhash(L, 1);
  lua_Number x = agn_checknumber(L, 2);
  int shrink = agnL_optboolean(L, 3, 0);  /* 6.5.13 extension */
  lua_pushboolean(L, dhs_remove(u, x, shrink));
  return 1;
}


static int dblhash_has (lua_State *L) {
  DoubleHashSet *u = checkdblhash(L, 1);
  lua_Number x = agn_checknumber(L, 2);
  int approx = agnL_optboolean(L, 3, 0);  /* 6.5.13 extension, 7.7.11 change */
  int rc = 0;
  if (approx) {
    size_t idx;
    lua_Number eps = agn_getepsilon(L);
    rc = dhs_contains(u, x);  /* first try a fast lookup, 7.7.10 */
    if (!rc) {
      size_t cap = u->capacity;
      for (idx=0; idx < cap && !rc; idx++) {
        if (u->status[idx] == DBLHASH_OCCUPIED && tools_approx(u->keys[idx], x, eps)) {
          rc = 1;
          break;
        }
      }
    }
  } else {
    rc = (u->count > 0) && dhs_contains(u, x);
  }
  lua_pushboolean(L, rc);
  return 1;
}


static int dblhash_attrib (lua_State *L) {
  DoubleHashSet *u = checkdblhash(L, 1);
  size_t i, deleted_count = 0;
  /* Count tombstones (slots with deleted data) to report table health */
  for (i=0; i < u->capacity; i++) {
    if (u->status[i] == DBLHASH_DELETED) deleted_count++;
  }
  lua_createtable(L, 0, 6);
  lua_rawsetstringnumber(L, -1,  "count",       (double)u->count);
  lua_rawsetstringnumber(L, -1,  "capacity",    (double)u->capacity);
  lua_rawsetstringboolean(L, -1, "optimised",   u->optimised);
  /* New Health Stats */
  lua_rawsetstringnumber(L, -1,  "deleted",     (double)deleted_count);  /* tombstones */
  lua_rawsetstringnumber(L, -1,  "loadfactor",  (double)u->count/u->capacity);
  lua_rawsetstringnumber(L, -1,  "utilization", (double)(u->count + deleted_count)/u->capacity);
  return 1;
}


/* Returns the high and lower unsigned 32-bit words of the SplitMix64-based hash for number x. 6.5.11 */
static int dblhash_hash (lua_State *L) {
  uint64_t h;
  uint32_t n, hx, lx, cx;
  lua_Number x = agn_checknumber(L, 1);
  n = agnL_optuint32_t(L, 2, 0);
  h = dhs_hash(x);
  luaL_checkstack(L, 3, "not enough stack space");
  hx = (uint32_t)(h >> 32);          /* high */
  lx = (uint32_t)(h & 0xFFFFFFFFU);  /* low */
  cx = hx ^ lx;  /* high and low combined, equal to (uint32_t)(h ^ (h >> 32)) */
  if (n == 0) {
    /* return raw 32-bit unsigned integers */
    lua_pushnumber(L, (lua_Number)hx);
    lua_pushnumber(L, (lua_Number)lx);
    lua_pushnumber(L, (lua_Number)cx);
  } else {
    /* return values constrained to [0, n-1] */
    lua_pushnumber(L, (lua_Number)(hx % n));
    lua_pushnumber(L, (lua_Number)(lx % n));
    lua_pushnumber(L, (lua_Number)(cx % n));
  }
  return 3;
}


/* Returns all active numbers in double hash table d in a new sequence. The result is not sorted. Values
   previously deleted but still available will not be returned. */
static int dblhash_toseq (lua_State *L) {  /* 6.5.12 */
  int64_t idx, c;
  DoubleHashSet *u = checkdblhash(L, 1);
  agn_createseq(L, u->count);
  c = 1;
  for (idx=0; idx < u->capacity; idx++) {
    if (u->status[idx] == DBLHASH_OCCUPIED) {
      agn_seqsetinumber(L, -1, c++, u->keys[idx]);
    }
  }
  return 1;
}


/* Returns all active numbers in double hash table d in a new table with the keys the actual integer indices in d
   and the values the associated numeric data. Values previously deleted but still available will not be returned. */
static int dblhash_totable (lua_State *L) {  /* 6.5.12 */
  int64_t idx;
  DoubleHashSet *u = checkdblhash(L, 1);
  lua_createtable(L, u->count, u->count);
  for (idx=0; idx < u->capacity; idx++) {
    if (u->status[idx] == DBLHASH_OCCUPIED) {
      lua_rawsetinumber(L, -1, idx, u->keys[idx]);
    }
  }
  return 1;
}


static int dblhash_getitem (lua_State *L) {
  int nargs;
  int64_t idx;
  nargs = lua_gettop(L);
  DoubleHashSet *u = checkdblhash(L, 1);
  if (nargs == 1) {
    lua_getfenv(L, 1);
    return 1;
  }
  luaL_checkstack(L, 2, "not enough stack space");
  idx = agn_checkinteger(L, 2);  /* 7.3.9 fix */
  if (idx >= 0 && idx < u->capacity) {
    if (u->status[idx] == DBLHASH_EMPTY) {
      lua_pushnil(L);
      lua_pushliteral(L, "empty");
    } else {
      lua_pushnumber(L, u->keys[idx]);
      lua_pushstring(L, (u->status[idx] == DBLHASH_OCCUPIED) ? "occupied" : "deleted");
    }
  } else {
    luaL_error(L, "Error in " LUA_QS ": index %d out of range.", "dblhash.getitem", idx);
  }
  return 2;
}


/* Returns the actual index number x is stored in double hash table d, plus the index position where
   x could have been stored if it would not have been already occupied by another value (or itself).
   The indices returned start from 0. If d would have to be resized before inserting x, then the function
   returns `null` twice. If the first result is `null` and the second an integer n, it means that x is not
   part of d but could be stored to position n in the hash table if it were vacant.

   See also: dblhash.getitem. */
static int dblhash_getindex (lua_State *L) {
  size_t idx;
  int rc;
  DoubleHashSet *u = checkdblhash(L, 1);
  lua_Number x = agn_checknumber(L, 2);
  luaL_checkstack(L, 2, "not enough stack space");
  if ((double)u->count/u->capacity > 0.7) {
    lua_pushnil(L);
    lua_pushnil(L);
  } else {
    idx = dhs_getidx(u, x, &rc);
    if (!rc) {
      lua_pushnil(L);
    } else {
      lua_pushnumber(L, idx);
    }
    lua_pushnumber(L, dhs_getfirstpossibleidx(u, x));
  }
  return 2;
}


static int iterate (lua_State *L) {
  DoubleHashSet *u = lua_touserdata(L, lua_upvalueindex(1));
  int idx = lua_tointeger(L, lua_upvalueindex(2));
  if (idx >= u->capacity) {
    lua_pushnil(L);
    return 1;
  }
  luaL_checkstack(L, 2, "not enough stack space");
  for (; idx < u->capacity; idx++) {
    if (u->status[idx] == DBLHASH_OCCUPIED) {
      lua_pushnumber(L, u->keys[idx]);
      lua_pushinteger(L, (int)idx + 1);
      lua_replace(L, lua_upvalueindex(2));
      return 1;
    }
  }
  lua_pushnil(L);
  return 1;
}

static int dblhash_iterate (lua_State *L) {  /* 7.7.3 */
  checkdblhash(L, 1);
  luaL_checkstack(L, 2, "not enough stack space");
  lua_pushvalue(L, 1);
  lua_pushinteger(L, 0);
  lua_pushcclosure(L, &iterate, 2);
  return 1;
}


/* The function rehashes the table to remove all slots marked deleted and optimizes the memory footprint
   based on the current number of elements. It aims for a ~50% load factor, with a minimum of eight
   preallocated slots. The function returns nothing. See also: dblhash.attrib, dblhash.purge.
   Written by Gemini AI, January 06, 2026. 6.5.12
   We deliberately use the name `compact` as it works differently from `lifo.shrink`, etc. */
static int dblhash_compact (lua_State *L) {
  DoubleHashSet *u = checkdblhash(L, 1);
  /* aim for a ~50% load factor. If count is 0, we still need a small minimum capacity. */
  size_t target_count = (u->count < 8) ? 8 : u->count * 2;
  size_t new_cap = u->optimised ? tools_nextpow2u32(target_count) : target_count;
  /* Even if new_cap == u->capacity, the next call will still rebuild the table and clear all tombstones. */
  if (!dhs_resize_to_size(u, new_cap)) {
    luaL_error(L, "Error in " LUA_QS ": memory allocation failed.", "dblhash.compact");
  }
  return 0;
}


/*** Metamethods **********************************************************************/

static int mt_index (lua_State *L) {
  int64_t idx;
  DoubleHashSet *u = checkdblhash(L, 1);
  if (!agn_isinteger(L, 2))  /* OOP method */
    return agn_initmethodcall(L, AGENA_DBLHASHLIBNAME, sizeof(AGENA_DBLHASHLIBNAME) - 1);
  idx = agn_tointeger(L, 2);
  if (idx >= 0 && idx < u->capacity) {
    if (u->status[idx] != DBLHASH_OCCUPIED) {
      lua_pushnil(L);
    } else {
      lua_pushnumber(L, u->keys[idx]);
    }
  } else {
    luaL_error(L, "Error in " LUA_QS ": index %d out of range.", "dblhash.__index", idx);
  }
  return 1;
}


static int mt_getsize (lua_State *L) {
  DoubleHashSet *u = checkdblhash(L, 1);
  lua_pushinteger(L, u->count);
  return 1;
}


static int mt_empty (lua_State *L) {
  DoubleHashSet *u = checkdblhash(L, 1);
  lua_pushboolean(L, u->count == 0);
  return 1;
}


static int mt_filled (lua_State *L) {
  DoubleHashSet *u = checkdblhash(L, 1);
  lua_pushboolean(L, u->count != 0);
  return 1;
}


static int mt_in (lua_State *L) {
  DoubleHashSet *u = checkdblhash(L, 2);
  lua_Number x = agn_checknumber(L, 1);
  lua_pushboolean(L, dhs_contains(u, x));
  return 1;
}


static int mt_notin (lua_State *L) {
  DoubleHashSet *u = checkdblhash(L, 2);
  lua_Number x = agn_checknumber(L, 1);
  lua_pushboolean(L, !dhs_contains(u, x));
  return 1;
}


static int mt_u2string (lua_State *L) {  /* at the console, the array is formatted as follows: */
  DoubleHashSet *u = checkdblhash(L, 1);
  if (agn_getutype(L, 1)) {
    lua_pushfstring(L, "(%u)", u->count);
    lua_concat(L, 2);
  } else
    luaL_error(L, "Error in " LUA_QS ": invalid double hash table.", "dblhash.__tostring");
  return 1;
}


static int mt_gc (lua_State *L) {  /* __gc method */
  DoubleHashSet *u = checkdblhash(L, 1);
  /* remove read-only mode if set */
  agn_udfreeze(L, 1, 0);
  /* delete metatable and user-defined type */
  lua_setmetatabletoobject(L, 1, NULL, 1);
  /* delete registry table */
  lua_pushnil(L);  /* destroy environment table */
  lua_setfenv(L, 1);
  xfreeall(u->keys, u->status);
  return 0;
}


static const struct luaL_Reg dblhash_lib [] = {  /* metamethods for numeric userdata `n` */
  {"__index",     mt_index},     /* n[p], with p the index, counting from 1, OOP-style calls */
  {"__size",      mt_getsize},   /* metamethod for `size` operator */
  {"__empty",     mt_empty},     /* metamethod for `empty` operator */
  {"__filled",    mt_filled},    /* metamethod for `filled` operator */
  {"__in",        mt_in},        /* metamethod for `in` operator */
  {"__notin",     mt_notin},     /* metamethod for `notin` operator */
  {"__tostring",  mt_u2string},  /* for output at the console, e.g. print(n) */
  {"__gc",        mt_gc},        /* please do not forget garbage collection */
  {NULL, NULL}
};


static const luaL_Reg dblhashlib[] = {
  {"attrib",      dblhash_attrib},
  {"compact",     dblhash_compact},
  {"getindex",    dblhash_getindex},
  {"getitem",     dblhash_getitem},
  {"has",         dblhash_has},
  {"hash",        dblhash_hash},
  {"include",     dblhash_include},
  {"iterate",     dblhash_iterate},
  {"new",         dblhash_new},
  {"purge",       dblhash_purge},
  {"toseq",       dblhash_toseq},
  {"totable",     dblhash_totable},
  {NULL, NULL}
};


/*
** Open dblhash library
*/

static void createmeta (lua_State *L) {
  luaL_newmetatable(L, AGENA_DBLHASHLIBNAME);  /* create metatable */
  lua_pushvalue(L, -1);  /* push metatable */
  lua_setfield(L, -2, "__index");  /* metatable.__index = metatable */
  luaL_register(L, NULL, dblhash_lib);  /* methods */
}

LUALIB_API int luaopen_dblhash (lua_State *L) {
  createmeta(L);
  luaL_register(L, AGENA_DBLHASHLIBNAME, dblhashlib);
  return 1;
}

