/* dblmap Library, implements C double-to-C double hash maps.
   The package provides a number-to-number hash maps, with the Agena numbers the keys and 
   Agena numbers the associated values.
   Created with the help of Gemini AI on July 07/25, 2026 and put to the public domain.
   Based on the former double-to-string hash map package of the same name.
   Agena C package functions by a_walz.
   This is a working edition, successfully checked with Valgrind.

Usage:

import dblmap

h := dblmap.new()
dblmap.include(h, 10, 10)
dblmap.include(h, Pi, Pi)
dblmap.getitem(h, 10):
dblmap.getitem(h, Pi):
dblmap.getitem(h, 1):
dblmap.purge(h, Pi);
dblmap.getitem(h, Pi):

dblmap.attrib(h):
dblmap.totable(h):

10 in h:
10 notin h:

f := dblmap.iterate(h);
f():
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define dblmap_c
#define LUA_LIB

#include "agena.h"

#include "agenalib.h"
#include "agnhlps.h"  /* include before khash.h */
#include "agnxlib.h"

#include "khash.h"

#if !(defined(__DJGPP__) || defined(__OS2__) || defined(LUA_ANSI))
#define AGENA_DBLMAPLIBNAME "dblmap"
LUALIB_API int (luaopen_dblmap) (lua_State *L);
#endif

#define checkdblmap(L,n) ((kh_dblmap_t **)luaL_checkudata(L, n, AGENA_DBLMAPLIBNAME))

#define isdblmap(L,n)    (luaL_isudata(L, n, AGENA_DBLMAPLIBNAME) && agn_isutypeset(L, n))

#include <stdint.h>
#include <string.h>

/* Generated by Gemini AI: Custom hash and equal for double keys, value is double. There
   are no templates for double-keyed maps in klib/khash. */
static kh_inline khint_t __kh_double_hash (double d) {
  uint64_t k;
  memcpy(&k, &d, sizeof(k));
  return (khint_t)(k ^ (k >> 32));
}

static kh_inline int __kh_double_equal (double a, double b) {
  return a == b;
}

static kh_inline khint_t mixed_double_hash (double d) {
  uint64_t k;
  memcpy(&k, &d, sizeof(k));
  khint_t h = (khint_t)(k ^ (k >> 32));
  /* `Fibonacci mixer`: This constant (the golden ratio fractional part of 2^32) breaks up 
     any sequential or floating-point patterns instantly. */
  return h * 2654435761U;
}

/* Stats, see script at the bottom of this file. 
   --------------------------------------------- */
/* with 500,000 random integers in 1 .. 250k: 33.795999765396 secs, 152161 colls; 33.671000003815 secs, 151890 colls
   with 500,000 random fractions in 0 .. 1:   33.983000040054 499970; 33.898000001907 499969 */
/* KHASH_INIT(dblmap, double, double, 1, __kh_double_hash, __kh_double_equal) */

/* with 500,000 random integers in 1 .. 250k: 33.990999937057 secs, 152161 colls; 33.628999948502 secs, 151890 colls 
   with 500,000 random fractions in 0 .. 1: 34.584000110626 463607; 34.235000133514 463480 */
KHASH_INIT(dblmap, double, double, 1, lua_hashnum, __kh_double_equal)

/* with 500,000 random integers in 1 .. 250k: 33.881000041962 secs, 216351 colls; 33.669000148773 secs, 216070 colls 
   with 500,000 random fractions in 0 .. 1: 34.174000024796 499970; 34.960999965668 499969 */
/* KHASH_INIT(dblmap, double, double, 1, mixed_double_hash, __kh_double_equal) */

/*** Agena C Functions ****************************************************************/

static int dblmap_new (lua_State *L) {
  khash_t(dblmap) **ht;
  size_t size = (size_t)tools_nextpow2u32(agnL_optposint(L, 1, 8));
  ht = (khash_t(dblmap) **)lua_newuserdata(L, sizeof(khash_t(dblmap) *));
  *ht = kh_init(dblmap);
  if (*ht == NULL) {
    agn_poptop(L);
    luaL_error(L, "Error in " LUA_QS ": memory allocation failed.", "dblmap.new");
  }
  kh_resize(dblmap, *ht, size);
  lua_setmetatabletoobject(L, -1, AGENA_DBLMAPLIBNAME, 1);
  lua_createtable(L, 0, 0);
  lua_setfenv(L, -2);
  return 1;
}


static int dblmap_getitem (lua_State *L)  {
  int nargs = lua_gettop(L);
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  if (!h)  {
    luaL_error(L, "Error in " LUA_QS ": uninitialized hash map.", "dblmap.getitem");
  }
  if (nargs == 1)  {
    lua_getfenv(L, 1);
  } else {
    luaL_checkstack(L, 2, "not enough stack space");
    if (agn_isnumber(L, 2))  {
      lua_Number key = agn_tonumber(L, 2);
      khint_t k = kh_get(dblmap, h, key);
      if (k != kh_end(h))  {
        lua_pushnumber(L, kh_val(h, k));
      } else  {
        lua_pushnil(L);
      }
    } else  {
      luaL_error(L, "Error in " LUA_QS ": invalid second argument given.", "dblmap.getitem");
    }
  }
  return 1;
}


static int dblmap_include (lua_State *L) {
  int rc;
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  double key = (double)agn_checknumber(L, 2);
  double val = (double)agn_checknumber(L, 3);
  if (!h)  {
    luaL_error(L, "Error in " LUA_QS ": uninitialized hash map.", "dblmap.include");
  }
  khint_t k = kh_put(dblmap, h, key, &rc);
  if (rc == -1) {
    luaL_error(L, "Error in " LUA_QS ": memory allocation failed.", "dblmap.include");
  }
  kh_val(h, k) = val;
  lua_pushboolean(L, rc);
  return 1;
}


static int dblmap_purge (lua_State *L) {
  int rc = 0;
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  lua_Number key = agn_checknumber(L, 2);
  if (!h)  {
    luaL_error(L, "Error in " LUA_QS ": uninitialized hash map.", "dblmap.purge");
  }
  int shrink = agnL_optboolean(L, 3, 0);
  khint_t k = kh_get(dblmap, h, key);
  if (k != kh_end(h)) {
    kh_del(dblmap, h, k);
    rc = 1;
  }
  if (rc && shrink) {
    kh_resize(dblmap, h, kh_size(h));
  }
  lua_pushboolean(L, rc);
  return 1;
}


static int aux_has (khash_t(dblmap) *h, double x) {
  int rc = 0;
  if (h) {
    khint_t k;
    for (k = kh_begin(h); k != kh_end(h) && !rc; ++k) {
      if (kh_exist(h, k)) {
        double d = kh_val(h, k);
        if (x == d) {
          rc = 1;
        }
      }
    }
  }
  return rc;
}

static int dblmap_has (lua_State *L) {
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  double x = agn_checknumber(L, 2);
  if (!h)  {
    luaL_error(L, "Error in " LUA_QS ": uninitialized hash map.", "dblmap.has");
  }
  lua_pushboolean(L, aux_has(h, x));
  return 1;
}


static int dblmap_resize (lua_State *L) {
  int rc = 1;
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  if (!h) {
    luaL_error(L, "Error in " LUA_QS ": uninitialized hash map.", "dblmap.resize");
  } else {
    khint_t old_buckets = h->n_buckets;
    khint_t target_buckets = (khint_t)agn_checknonnegint(L, 2);
    khint_t actual_target = 1;
    while (actual_target < target_buckets) {
      actual_target <<= 1;
    }
    if (actual_target < old_buckets) {
      actual_target = old_buckets;
    }
    if (actual_target != old_buckets) {
      kh_resize(dblmap, h, actual_target);
      rc = (h->n_buckets != old_buckets);
    } else {
      rc = 0;
    }
  }
  luaL_checkstack(L, 2, "not enough stack space");
  lua_pushboolean(L, rc);
  lua_pushnumber(L, (lua_Number)h->n_buckets);
  return 2;
}


static int dblmap_cleanse (lua_State *L) {
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  if (!h)  {
    luaL_error(L, "Error in " LUA_QS ": uninitialized hash map.", "dblmap.cleanse");
  } else {
    kh_clear(dblmap, h);
  }
  return 0;
}


static int iterate (lua_State *L) {
  kh_dblmap_t **ht = lua_touserdata(L, lua_upvalueindex(1));
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  khint_t k = (khint_t)lua_tointeger(L, lua_upvalueindex(2));
  if (h->n_buckets == 0 || k >= kh_end(h) ) {
    lua_pushnil(L);
    return 1;
  }
  luaL_checkstack(L, 3, "not enough stack space");
  for (; k != kh_end(h); ++k) {
    if (kh_exist(h, k)) {
      lua_pushnumber(L, (lua_Number)kh_key(h, k));
      lua_pushnumber(L, (lua_Number)kh_val(h, k));
      lua_pushinteger(L, (int)k + 1);
      lua_replace(L, lua_upvalueindex(2));
      return 2;
    }
  }
  lua_pushnil(L);
  return 1;
}

static int dblmap_iterate (lua_State *L) {
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  luaL_checkstack(L, 2, "not enough stack space");
  lua_pushvalue(L, 1);
  (void)h;  /* silences the unused variable warning */
  lua_pushinteger(L, (int)kh_begin(h));
  lua_pushcclosure(L, &iterate, 2);
  return 1;
}


/* Counts how many times khash.h has to resolve collisions by moving to the next slot (probing).
   Created by Gemini AI, 7.7.11 */
static uint32_t khash_collisions (kh_dblmap_t *h) {
  uint32_t collision_moves = 0;
  khint_t k;
  /* kh_end(h) is the total number of buckets currently allocated in the table array */
  khint_t mask = h->n_buckets - 1; 
  /* Loop through every physical bucket slot in the hash table */
  for (k = kh_begin(h); k < kh_end(h); ++k) {
    /* Check if the current slot actually contains a valid inserted element */
    if (kh_exist(h, k)) {
      double key = kh_key(h, k);
      /* 1. Calculate the raw hash value using your hash function */
      khint_t raw_hash = __kh_double_hash(key);
      /* 2. Calculate the "ideal" starting bucket slot khash intended to use */
      khint_t ideal_slot = raw_hash & mask;
      /* 3. If its current slot (k) is not its ideal slot, it was moved! */
      if (k != ideal_slot) collision_moves++;
    }
  }
  return collision_moves;
}

static int dblmap_attrib (lua_State *L) {
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  size_t n_occupied = h ? kh_size(h) : 0;
  size_t n_capacity = h ? h->n_buckets : 0;
  size_t n_empty = 0;
  if (!h)  {
    luaL_error(L, "Error in " LUA_QS ": uninitialized hash map.", "dblmap.attrib");
  }
  khint_t k;
  for (k = kh_begin(h); k != kh_end(h); ++k) {
    if (!kh_exist(h, k)) {
      n_empty++;
    }
  }
  size_t n_void = (n_capacity > n_occupied + n_empty) ? (n_capacity - n_occupied - n_empty) : 0;
  lua_createtable(L, 0, 6);
  lua_rawsetstringnumber(L, -1, "count", (double)n_occupied);
  lua_rawsetstringnumber(L, -1, "capacity", (double)n_capacity);
  lua_rawsetstringnumber(L, -1, "empty", (double)n_empty);
  lua_rawsetstringnumber(L, -1, "void", (double)n_void);
  double cap = (double)n_capacity;
  lua_rawsetstringnumber(L, -1, "loadfactor", cap == 0.0 ? 0.0 : (double)n_occupied / cap);
  lua_rawsetstringnumber(L, -1, "utilization", cap == 0.0 ? 0.0 : (double)(n_occupied + n_empty) / cap);
  lua_rawsetstringnumber(L, -1, "collisions", khash_collisions(h));
  return 1;
}


static int dblmap_totable (lua_State *L)  {
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  if (!h)  {
    luaL_error(L, "Error in " LUA_QS ": uninitialized hash map.", "dblmap.totable");
  }
  lua_createtable(L, (int)kh_size(h), 0);
  khint_t k;
  for (k=kh_begin(h); k != kh_end(h); ++k)  {
    if (kh_exist(h, k))  {
      lua_pushnumber(L, (lua_Number)kh_key(h, k));
      lua_pushnumber(L, (lua_Number)kh_val(h, k));
      lua_rawset(L, -3);
    }
  }
  return 1;
}


static int dblmap_hash (lua_State *L) {
  double x = agn_checknumber(L, 1);
  khint_t n = agnL_optuint32_t(L, 2, 0);
  unsigned int l = lua_hashnum(x);   /* internally used by dblhash */
  khint_t h = __kh_double_hash(x);   /* originally proposed by Gemini AI */
  khint_t m = mixed_double_hash(x);  /* Fib hash proposed by Gemini AI */
  luaL_checkstack(L, 3, "not enough stack space");
  lua_pushnumber(L, (n != 0) ? l % n : l);
  lua_pushnumber(L, (n != 0) ? h % n : h);
  lua_pushnumber(L, (n != 0) ? m % n : m);
  return 3;
}


/*** Metamethods **********************************************************************/

static int mt_index (lua_State *L) {
  if (isdblmap(L, 1) || agn_isnumber(L, 1)) {  /* 7.7.11 extension for OOP-style calls */
    if (lua_gettop(L) == 2 && agn_isstring(L, 2)) {
      /* sizeof(<string constant>) == strlen(<string constant>) + 1 */
      return agn_initmethodcall(L, AGENA_DBLMAPLIBNAME, sizeof(AGENA_DBLMAPLIBNAME) - 1);
    }
  }
  return dblmap_getitem(L);
}


static int mt_getsize (lua_State *L)  {
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  lua_pushinteger(L, h ? (lua_Integer)kh_size(h) : 0);
  return 1;
}

static int mt_empty (lua_State *L)  {
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  lua_pushboolean(L, h ? kh_size(h) == 0 : 1);
  return 1;
}


static int mt_filled (lua_State *L)  {
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  lua_pushboolean(L, h ? kh_size(h) != 0 : 0);
  return 1;
}


static int mt_in (lua_State *L)  {
  kh_dblmap_t **ht = checkdblmap(L, 2);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  double val = agn_checknumber(L, 1);
  lua_pushboolean(L, aux_has(h, val));
  return 1;
}


static int mt_notin (lua_State *L)  {
  kh_dblmap_t **ht = checkdblmap(L, 2);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  double val = agn_checknumber(L, 1);
  lua_pushboolean(L, !aux_has(h, val));
  return 1;
}


static int mt_u2string (lua_State *L) {  /* at the console, the hash table is formatted as follows: */
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  if (agn_getutype(L, 1)) {
    lua_pushfstring(L, "(%u)", h ? kh_size(h) : 0);
    lua_concat(L, 2);
  } else
    luaL_error(L, "Error in " LUA_QS ": invalid number hash table.", "dblmap.__tostring");
  return 1;
}


static int mt_gc (lua_State *L)  {
  kh_dblmap_t **ht = checkdblmap(L, 1);
  kh_dblmap_t *h = (ht && *ht) ? *ht : NULL;
  if (h)  {
    *ht = NULL;  /* 7.7.10 fix */
    kh_destroy(dblmap, h);
  }
  agn_udfreeze(L, 1, 0);
  lua_setmetatabletoobject(L, 1, NULL, 1);
  lua_pushnil(L);
  lua_setfenv(L, 1);
  return 0;
}


static const struct luaL_Reg dblmap_lib [] = {  /* metamethods for numeric userdata `n` */
  {"attrib",       dblmap_attrib},
  {"cleanse",      dblmap_cleanse},
  {"getitem",      dblmap_getitem},
  {"has",          dblmap_has},
  {"include",      dblmap_include},
  {"iterate",      dblmap_iterate},
  {"purge",        dblmap_purge},
  {"resize",       dblmap_resize},
  {"totable",      dblmap_totable},
  {"__index",      mt_index},     /* n[p], with p the index, counting from 1 */
  {"__writeindex", dblmap_include},
  {"__size",       mt_getsize},   /* metamethod for `size` operator */
  {"__empty",      mt_empty},     /* metamethod for `empty` operator */
  {"__filled",     mt_filled},    /* metamethod for `filled` operator */
  {"__in",         mt_in},        /* metamethod for `in` operator */
  {"__notin",      mt_notin},     /* metamethod for `notin` operator */
  {"__tostring",   mt_u2string},  /* for output at the console, e.g. print(n) */
  {"__gc",         mt_gc},        /* please do not forget garbage collection */
  {NULL, NULL}
};


static const luaL_Reg dblmaplib[] = {
  {"attrib",       dblmap_attrib},
  {"cleanse",      dblmap_cleanse},
  {"getitem",      dblmap_getitem},
  {"has",          dblmap_has},
  {"hash",         dblmap_hash},
  {"include",      dblmap_include},
  {"iterate",      dblmap_iterate},
  {"new",          dblmap_new},
  {"purge",        dblmap_purge},
  {"resize",       dblmap_resize},
  {"totable",      dblmap_totable},
  {NULL, NULL}
};


/*
** Open dblmap library
*/

static void createmeta (lua_State *L) {
  luaL_newmetatable(L, AGENA_DBLMAPLIBNAME);  /* create metatable */
  lua_pushvalue(L, -1);  /* push metatable */
  lua_setfield(L, -2, "__index");  /* metatable.__index = metatable */
  luaL_register(L, NULL, dblmap_lib);  /* methods */
}

LUALIB_API int luaopen_dblmap (lua_State *L) {
  createmeta(L);
  luaL_register(L, AGENA_DBLMAPLIBNAME, dblmaplib);
  return 1;
}

/*
# run '../archive/dblmapcolls'

math.randomseed(0, 0);  # always generate the same random numbers
capacity := 500k;

l := numarray.double(capacity);
for i to capacity do
   l[i] := 10000*math.randoms()
   #l[i] := math.randoms(1, 250k)
od

watch();
to 100 do
   h := dblmap.new();
   for i in l do
      dblmap.include(h, i, i)
   od;
   colls := dblmap.attrib(h)['collisions'];
   for i in l do
      if not dblmap.getitem(h, i) then print(i) fi
   od;
   environ.gc('step', 100) 
od;
print(watch(), colls);
*/
