/* Double-Double Arithmetic library.

   Generated by Gemini AI, April 09, 2026, put to the public domain.

   The implementation is based on the TwoSum and TwoProd algorithms, taken from the library
   `TwoFloat: Double-Word Arithmetic in C++` with the following

   MIT License:

   Copyright (c) 2023 Embedded Systems and Applications Group

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all
   copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE.

   History: The TwoSum algorithm was discovered by Ole Møller in 1965 and later popularized and formally
   proven by Donald Knuth in "The Art of Computer Programming" (Volume 2). The TwoProd splitting technique
   is attributed to Veltkamp and Dekker (1971).

   IMPORTANT: To get the best results, use the compiler switches:

   set gccfileopts=-O3 -mfma -fno-unsafe-math-optimizations -DLUA_BUILD_AS_DLL -fgnu89-inline -Wno-attributes
   set gccfileopts=-O3 -fno-builtin -ffloat-store -fno-unsafe-math-optimizations -DLUA_BUILD_AS_DLL -fgnu89-inline -Wno-attributes
*/

#define calc_c
#define LUA_LIB

#include <math.h>
#include <stdio.h>
#include "agnhlps.h"
#include "ddmath.h"

/* Optimization: use this inline function for degree-to-radian conversion */
dd_pair dd_to_radians (dd_pair degrees) {
  return dd_mul(degrees, DD_PI_180);
}

/* The TwoSum algorithm (Knuth 1998). Calculates the sum and resulting rounding
   error of two floating point numbers using the TwoSum algorithm. */
dd_pair two_sum (double a, double b) {
  dd_pair res;
  res.hi = a + b;
  volatile double v = res.hi - a; /* volatile forces the CPU to actually do the math */
  res.lo = (a - (res.hi - v)) + (b - v);
  return res;
}

/* Fast2Sum algorithm (Dekker 1971).
   Calculates the sum and resulting rounding error of two floating point numbers using the
   Fast2Sum algorithm. Algorithm 1 in https://doi.org/10.1145/3121432

   REQUIRES that |a| >= |b| !!!

   Taken from TwoSum C++ library */
dd_pair fast_two_sum (double a, double b) {
  dd_pair res;
  res.hi = a + b;
  double z = res.hi - a;
  res.lo = b - z;
  return res;
}

/* Calculates the difference and resulting rounding error of two floating point
   numbers using the same principle as the TwoSum algorithm.
   Taken from TwoSum C++ library */
dd_pair two_diff (double a, double b) {
  dd_pair res;
  res.hi = a - b;
  double a1 = res.hi - a;
  double b1 = res.hi - a1;
  double da = a - b1;
  double db = b + a1;
  res.lo = da - db;
  return res;
}

/* The Fast2Prod algorithm (e.g. Kahan 1996)
   Calculates the product and resulting rounding error of two floating point
   numbers using the Fast2Prod algorithm. For performance reasons, this
   algorithm should only be used if the CPU has support for fused multiply add
   (fmaf) instructions, which is not the case for most CPUs.
   Algorithm 3 in https://doi.org/10.1145/3121432
   Taken from TwoSum C++ library */
dd_pair two_prod (double a, double b) {
  dd_pair res;
  res.hi = a*b;
  res.lo = fma(a, b, -res.hi);
  return res;
}

/* Adds two double-word floating point numbers.
   We use the accurate mode (AccurateDWPlusDW in Joldes et al. (2017)),
   with the relative error always bounded.
   Taken from TwoSum C++ library */
dd_pair dd_add (dd_pair x, dd_pair y) {
  dd_pair s, t, v;
  double c, w;
  s = two_sum(x.hi, y.hi);
  t = two_sum(x.lo, y.lo);
  c = s.lo + t.hi;
  v = two_sum(s.hi, c);
  w = t.lo + v.lo;
  return two_sum(v.hi, w);  /* ensure normalisation */
}

dd_pair dd_sub (dd_pair a, dd_pair b) {
  /* Subtraction is just addition with the signs of the second operand flipped */
  dd_pair neg_b;
  neg_b.hi = -b.hi;
  neg_b.lo = -b.lo;
  return dd_add(a, neg_b);
}

dd_pair dd_mul_d (dd_pair a, double b) {
  dd_pair p = two_prod(a.hi, b);
  p.lo += a.lo*b;
  return two_sum(p.hi, p.lo);
}

dd_pair dd_mul (dd_pair x, dd_pair y) {
  /* 1. Get the high-precision product of the high parts */
  dd_pair p = two_prod(x.hi, y.hi);
  /* 2. Incorporate the cross-products of the low parts */
  /* p.lo += (x.hi*y.lo) + (x.lo*y.hi) */
  p.lo = fma(x.hi, y.lo, p.lo);
  p.lo = fma(x.lo, y.hi, p.lo);
  /* 3. Renormalize */
  return two_sum(p.hi, p.lo);  /* ensure normalisation */
}

dd_pair dd_mul_d_d (double a, double b) {
  /* No promotion needed; two_prod returns the hi and lo exactly */
  return two_prod(a, b);
}

/* Fused Multiply-Add: (a*b) + c */
dd_pair dd_fma (dd_pair a, dd_pair b, dd_pair c) {
  /* Step 1: Compute a*b exactly as a quad-double (roughly) */
  /* We start with the exact product of the high parts */
  dd_pair prod = two_prod(a.hi, b.hi);
  /* Step 2: Accumulate all cross-terms into the low part of the product */
  /* prod.lo += (a.hi*b.lo) + (a.lo*b.hi) */
  prod.lo += a.hi*b.lo;
  prod.lo += a.lo*b.hi;
  /* Step 3: Add 'c' to the product */
  /* First, add the high parts */
  dd_pair res = two_sum(prod.hi, c.hi);
  /* Step 4: Accumulate all remaining low-order components */
  /* This includes the low part of the sum, the low part of the product, */
  /* and the low part of the added pair 'c'. */
  res.lo += (prod.lo + c.lo);
  /* Step 5: Final renormalization to ensure |res.lo| <= 0.5*ulp(res.hi) */
  return two_sum(res.hi, res.lo);
}

dd_pair dd_div (dd_pair a, dd_pair b) {
  double q1 = a.hi/b.hi;
  dd_pair p1 = two_prod(q1, b.hi);
  double r_hi = a.hi - p1.hi;
  double r_lo = a.lo - p1.lo;
  r_lo -= q1*b.lo;
  double q2 = (r_hi + r_lo)/b.hi;
  return two_sum(q1, q2);
}

dd_pair dd_div_d_d (double a, double b) {
  /* Step 1: Promote doubles to dd_pair */
  dd_pair da, db;
  da.hi = a;
  da.lo = 0.0;
  db.hi = b;
  db.lo = 0.0;
  /* Step 2: Perform the double-double division */
  return dd_div(da, db);
}

dd_pair dd_inv (dd_pair a) {
  /* Step 1: Initial estimate using standard double division */
  double x0 = 1.0/a.hi;
  /* Step 2: One iteration of Newton's method: x1 = x0 + x0*(1 - a*x0) */
  /* This captures the error in the initial double-precision reciprocal */
  dd_pair ax0 = dd_mul_d(a, x0);
  /* Compute (1.0 - a*x0) accurately */
  dd_pair diff;
  diff.hi = 1.0 - ax0.hi;
  diff.lo = -ax0.lo;
  /* Correction: x0*diff */
  dd_pair corr = dd_mul_d(diff, x0);
  /* Final result: x0 + corr */
  return two_sum(x0, corr.hi + corr.lo);
}

dd_pair dd_inv_d (double a) {
  /* Step 1: Initial estimate using standard double division */
  double x0 = 1.0/a;
  /* Step 2: Refinement. Compute 1.0 - a*x0 accurately. */
  /* Since a and x0 are doubles, we use a specialized double*double->dd_pair multiplication */
  dd_pair ax0 = two_prod(a, x0);
  /* Compute (1.0 - ax0) */
  dd_pair diff;
  diff.hi = 1.0 - ax0.hi;
  diff.lo = -ax0.lo;
  /* Correction: x0*diff */
  /* Since diff is a dd_pair and x0 is a double, use dd_mul_d */
  dd_pair corr = dd_mul_d(diff, x0);
  /* Final result: x0 + corr */
  return two_sum(x0, corr.hi + corr.lo);
}

dd_pair dd_pow_n (dd_pair a, int n) {
  /* Exponentiation by squaring: O(log n) complexity */
  dd_pair res;
  res.hi = 1.0;
  res.lo = 0.0;
  if (n == 0) return res;
  /* Handle negative exponents */
  int neg = (n < 0);
  if (neg) n = -n;
  dd_pair base = a;
  while (n > 0) {
    if (n % 2 == 1) {
      res = dd_mul(res, base);
    }
    base = dd_mul(base, base);
    n /= 2;
  }
  if (neg) {
    dd_pair one;
    one.hi = 1.0;
    one.lo = 0.0;
    return dd_div(one, res);
  }
  return res;
}

dd_pair dd_pow_d_i (double a, int n) {
  /* Step 1: Promote doubles to dd_pair */
  dd_pair da;
  da.hi = a;
  da.lo = 0.0;
  /* Step 2: Perform the double-double division */
  return dd_pow_n(da, n);
}

dd_pair dd_pow (dd_pair a, dd_pair b) {  /* 7.4.1 */
  /* 1. Special Case: a^0 = 1 */
  if (b.hi == 0.0 && b.lo == 0.0) {
    return (dd_pair)DD_ONE;
  }
  /* 2. Special Case: 0^b */
  if (a.hi == 0.0 && a.lo == 0.0) {
    if (b.hi > 0.0) return (dd_pair)DD_NAUGHT;
    if (b.hi < 0.0) return (dd_pair)DD_INF;
    return (dd_pair)DD_NAN;
  }
  /* 3. Handle Negative Base 'a' */
  if (a.hi < 0.0) {
    /* a^b is only real if b is an integer */
    double b_int = sun_floor(b.hi + 0.5);
    if (b.hi == b_int && b.lo == 0.0) {
      /* Use the identity: (-a)^b = (a^b) * (-1)^b */
      dd_pair res = dd_pow(dd_neg(a), b);
      if ((int)sun_fmod(b_int, 2.0) != 0) {
        return dd_neg(res);
      }
      return res;
    }
    return (dd_pair)DD_NAN; /* Complex result not supported */
  }
  /* 4. Optimization: If b is a small exact integer, use your dd_pow_n */
  /* This is much faster and avoids log/exp overhead */
  double b_round = sun_floor(b.hi + 0.5);
  if (b.hi == b_round && b.lo == 0.0 && fabs(b_round) < 1024.0) {
    return dd_pow_n(a, (int)b_round);
  }
  /* 5. General Case: a^b = exp(b * ln(a)) */
  return dd_exp(dd_mul(b, dd_log(a)));
}

dd_pair dd_unm (dd_pair a) {
  return (dd_pair){-a.hi, -a.lo};
}

dd_pair dd_abs (dd_pair a) {
  if (a.hi < 0.0) {
    return (dd_pair){-a.hi, -a.lo};
  }
  return a;
}

dd_pair dd_absdiff (dd_pair a, dd_pair b) {
  return (dd_pair){fabs(a.hi - b.hi), fabs(a.lo - b.lo)};
}

int dd_sign (dd_pair a) {
  if (a.hi > 0.0) return 1;
  if (a.hi < 0.0) return -1;
  return 0;
}

int dd_signbit (dd_pair a) {
  /* The high part always dictates the sign of the whole pair */
  return signbit(a.hi) != 0;
}

dd_pair dd_copysign (dd_pair mag, dd_pair sgn) {
  /* We use the sign of sgn.hi and apply it to mag */
  double s = (signbit(sgn.hi)) ? -1.0 : 1.0;
  /* If the current sign doesn't match the target, flip both parts */
  if ((s < 0.0 && mag.hi >= 0.0) || (s > 0.0 && mag.hi < 0.0)) {
    return (dd_pair){-mag.hi, -mag.lo};
  }
  return mag;
}

dd_pair dd_square (dd_pair a) {
  /* Step 1: Compute the high-precision square of the hi part */
  dd_pair p = two_prod(a.hi, a.hi);
  /* Step 2: Add the cross-term: 2*a.hi*a.lo */
  /* Note: 2.0*a.hi*a.lo is equivalent to (a.hi*a.lo) + (a.hi*a.lo) */
  p.lo += 2.0*a.hi*a.lo;
  /* Step 3: Renormalize the result */
  return two_sum(p.hi, p.lo);
}

dd_pair dd_cube (dd_pair a) {
  /* Step 1: Compute a^2 with high precision */
  dd_pair a2 = dd_square(a);
  /* Step 2: Multiply by a (full dd_mul) */
  /* While we could optimize further, dd_mul(a2, a) is the most robust way
     to ensure the cross-terms are captured as the magnitude grows. */
  return dd_mul(a2, a);
}

dd_pair dd_sqrt (dd_pair a) {
  /* Step 1: Handle cases where a <= 0 */
  if (a.hi <= 0.0) {
    dd_pair res = DD_NAUGHT;
    if (a.hi < 0.0) res.hi = 0.0/0.0; /* Return NaN for negative */
    return res;
  }
  /* Step 2: Initial estimate using standard sqrt */
  double s = sqrt(a.hi);
  /* Step 3: One iteration of Newton's method: res = 0.5*(a/s + s) */
  /* We use dd_div_d_d or similar to divide our high-precision 'a' by scalar 's' */
  dd_pair a_div_s = dd_div(a, (dd_pair){s, 0.0});
  dd_pair res = dd_add(a_div_s, (dd_pair){s, 0.0});
  /* Multiply by 0.5 (which is exact in floating point) */
  res.hi *= 0.5;
  res.lo *= 0.5;
  return res;
}

dd_pair dd_cbrt (dd_pair a) {
  /* Step 1: Handle zero and special cases */
  if (a.hi == 0.0) return (dd_pair)DD_NAUGHT;
  /* Step 2: Initial estimate using standard cbrt */
  double x0 = sun_cbrt(a.hi);
  /* Step 3: Halley's Method refinement
     Formula: x1 = x0*(x0^3 + 2a)/(2x0^3 + a) */
  dd_pair x0_dd = {x0, 0.0};
  dd_pair x0_2 = dd_mul(x0_dd, x0_dd);
  dd_pair x0_3 = dd_mul(x0_2, x0_dd); /* x0^3 */
  /* Numerator: x0^3 + 2a */
  dd_pair two_a = dd_add(a, a);
  dd_pair num = dd_add(x0_3, two_a);
  /* Denominator: 2x0^3 + a */
  dd_pair two_x0_3 = dd_add(x0_3, x0_3);
  dd_pair den = dd_add(two_x0_3, a);
  /* Final refinement: x0*(num/den) */
  dd_pair ratio = dd_div(num, den);
  return dd_mul(x0_dd, ratio);
}

dd_pair dd_root_n (dd_pair a, int n) {
  /* Step 1: Handle special cases */
  if (n <= 0) return (dd_pair)DD_NAN; /* NaN */
  if (n == 1) return a;
  if (a.hi == 0.0) return (dd_pair)DD_NAUGHT;
  /* For even roots, check for negative input */
  if (n % 2 == 0 && a.hi < 0.0) return (dd_pair)DD_NAN;
  /* Step 2: Initial estimate using standard pow() */
  /* If a.hi is negative and n is odd, pow() might need help with the sign */
  double x0;
  if (a.hi < 0.0) {
    x0 = -sun_pow(-a.hi, 1.0/(double)n, 1);
  } else {
    x0 = sun_pow(a.hi, 1.0/(double)n, 1);
  }
  /* Step 3: One iteration of Newton's method */
  /* x1 = x0 + (a/x0^(n-1) - x0)/n */
  dd_pair x0_dd = {x0, 0.0};
  dd_pair x0_n_minus_1 = dd_pow_n(x0_dd, n - 1);
  dd_pair ratio = dd_div(a, x0_n_minus_1); /* a/x0^(n-1) */
  dd_pair diff = dd_sub(ratio, x0_dd);     /* (a/x0^(n-1)) - x0 */
  /* Final correction: x0 + diff/n */
  dd_pair corr = dd_mul_d(diff, 1.0/(double)n);
  return dd_add(x0_dd, corr);
}

/* High-precision Hypotenuse with coupled Newton iteration */
dd_pair dd_hypot (dd_pair a, dd_pair b) {
  /* 1. Handle special cases */
  if (a.hi == 0.0 && a.lo == 0.0) return (b.hi < 0) ? dd_neg(b) : b;
  if (b.hi == 0.0 && b.lo == 0.0) return (a.hi < 0) ? dd_neg(a) : a;
  /* 2. Compute a^2 + b^2 accurately */
  dd_pair sum2 = dd_add(dd_mul(a, a), dd_mul(b, b));
  /* 3. Initial approximation using hardware sqrt */
  double x0 = 1.0/sqrt(sum2.hi); /* We use the reciprocal sqrt for speed/accuracy */
  dd_pair h = dd_mul_d(sum2, x0);  /* h is the first estimate of sqrt(sum2) */
  /* 4. One iteration of the "coupled" Newton step:
     res = h + (sum2 - h*h) / (2 * h)
     This specific form is much more stable than 0.5 * (h + sum2/h) */
  dd_pair h2 = dd_mul(h, h);
  dd_pair diff = dd_sub(sum2, h2);
  /* Correction: diff / (2 * h) */
  double corr = (diff.hi + diff.lo)/(2.0*h.hi);
  /* 5. Final result */
  return two_sum(h.hi, h.lo + corr);
}

/* High-precision Square Root of Difference, cathetus: sqrt(a^2 - b^2) */
dd_pair dd_hypot4 (dd_pair a, dd_pair b) {
  /* 1. Handle special cases and domain validation */
  /* If |b| > |a|, the result is mathematically complex/NaN */
  if (fabs(b.hi) > fabs(a.hi)) {
    return (dd_pair){0.0/0.0, 0.0/0.0}; /* Return NaN */
  }
  /* 2. Compute a^2 - b^2 accurately */
  /* We use dd_mul and dd_sub to maintain 106-bit depth of the radicand */
  dd_pair a2 = dd_mul(a, a);
  dd_pair b2 = dd_mul(b, b);
  dd_pair diff_sq = dd_sub(a2, b2);
  /* Guard against tiny negative results due to precision limits when a == b */
  if (diff_sq.hi <= 0.0) return (dd_pair)DD_NAUGHT;
  /* 3. Initial approximation */
  double x0 = sqrt(diff_sq.hi);
  /* 4. Coupled Newton-Raphson iteration for 106-bit refinement:
     res = x0 + (diff_sq - x0^2) / (2 * x0) */
  dd_pair x0_sq = dd_mul_d((dd_pair){x0, 0.0}, x0);
  dd_pair error_term = dd_sub(diff_sq, x0_sq);
  /* Correction: error / (2 * x0) */
  double corr = (error_term.hi + error_term.lo)/(2.0*x0);
  /* 5. Final assembly */
  return two_sum(x0, corr);
}

/* Complementary Error Function: erfc(x) = 1 - erf(x) */
dd_pair dd_erfc (dd_pair x) {
  int i;
  /* 1. Handle Symmetry: erfc(-x) = 2 - erfc(x) */
  if (x.hi < 0.0) {
    dd_pair pos_erfc = dd_erfc(dd_neg(x));
    return dd_sub((dd_pair){2.0, 0.0}, pos_erfc);
  }
  /* 2. Case 1: Small x (x in [0, 1.0]) */
  /* It is more accurate to use 1 - erf(x) when x is small */
  if (x.hi <= 1.0) {
    return dd_sub((dd_pair)DD_ONE, dd_erf(x));
  }
  /* 3. Case 2: Large x (x > 1.0) */
  /* Use the Continued Fraction:
     erfc(x) = [exp(-x^2) / sqrt(pi)] * [1 / (x + (0.5 / (x + (1.0 / (x + ...)))))]
  */
  dd_pair x2 = dd_mul(x, x);
  dd_pair exp_neg_x2 = dd_exp(dd_neg(x2));
  /* Constant: 1 / sqrt(pi) */
  static const dd_pair INV_SQRT_PI = {0.56418958354775628, -2.5933010537021575e-18};
  dd_pair factor = dd_mul(exp_neg_x2, INV_SQRT_PI);
  /* Iterative evaluation of the continued fraction (Backwards) */
  /* 60 iterations are generally sufficient for 106-bit depth */
  dd_pair res = {0.0, 0.0};
  for (i=60; i > 0; i--) {
    /* res = (i * 0.5) / (x + res) */
    dd_pair num = {(double)i * 0.5, 0.0};
    dd_pair den = dd_add(x, res);
    res = dd_div(num, den);
  }
  /* final = factor / (x + res) */
  return dd_mul(factor, dd_inv(dd_add(x, res)));
}

/* Error Function: erf(x) */
dd_pair dd_erf (dd_pair x) {
  int n;
  /* Step 1: Handle Symmetry - This fixes the negative argument issue */
  if (x.hi < 0.0) {
    return dd_neg(dd_erf(dd_neg(x)));
  }
  double ax = x.hi;
  /* Case 1: Small to Medium x (Taylor Series) */
  /* We use 1.0 as the cutoff to ensure the series is fully converged */
  if (ax <= 1.0) {
    dd_pair x2 = dd_mul(x, x);
    dd_pair term = x;
    dd_pair sum = x;
    for (n=1; n < 60; n++) { /* Increased depth for 106-bit precision at x=1.0 */
      /* term = term * (-x^2) / n */
      term = dd_mul(term, x2);
      term = dd_mul_d(term, -1.0 / (double)n);

      /* current = term / (2n + 1) */
      dd_pair current = dd_mul_d(term, 1.0 / (2.0 * (double)n + 1.0));
      dd_pair next_sum = dd_add(sum, current);

      /* Check if the low part has stabilized */
      if (current.hi == 0.0 && current.lo == 0.0) break;
      if (fabs(current.hi) < fabs(sum.hi) * 1e-32) break;
      sum = next_sum;
    }
    /* erf(x) = sum * (2 / sqrt(pi)) */
    static const dd_pair TWO_OVER_SQRT_PI = {1.12837916709551257, -1.64366289567954541e-17};
    return dd_mul(sum, TWO_OVER_SQRT_PI);
  }
  /* Case 2: Large x - Use the complementary function erfc */
  /* Since x > 1.0 here, this is stable and avoids cancellation */
  return dd_sub((dd_pair)DD_ONE, dd_erfc(x));
}

/* Constants taken from:

   DoubleFloats.jl-1.6.2/src/math/elementary/sequences.jl

   Copyright (c) 2018-2023 Julia Math

   MIT License

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all
   copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE.

   function exp_taylor(a::DoubleFloat{T}) where {T<:IEEEFloat}
     x = a
     x2 = x*x
     x3 = x*x2
     x4 = x2*x2
     x5 = x2*x3
     x10 = x5*x5
     x15 = x5*x10
     x20 = x10*x10
     x25 = x10*x15

     z = x + inv_fact[2]*x2 + inv_fact[3]*x3 + inv_fact[4]*x4
     z2 = x5*(inv_fact[5] + x*inv_fact[6] + x2*inv_fact[7] +
          x3*inv_fact[8] + x4*inv_fact[9])
     z3 = x10*(inv_fact[10] + x*inv_fact[11] + x2*inv_fact[12] +
          x3*inv_fact[13] + x4*inv_fact[14])
     z4 = x15*(inv_fact[15] + x*inv_fact[16] + x2*inv_fact[17] +
          x3*inv_fact[18] + x4*inv_fact[19])
     z5 = x20*(inv_fact[20] + x*inv_fact[21] + x2*inv_fact[22] +
          x3*inv_fact[23] + x4*inv_fact[24])
     z6 = x25*(inv_fact[25] + x*inv_fact[26] + x2*inv_fact[27])

     ((((z6+z5)+z4)+z3)+z2)+z + one(DoubleFloat{T})
   end */
static dd_pair inv_fact[33] = {
/*  0 */  {0.0, 0.0},  /* do not set to DD_XYZ, Mac OS X does not like it */
/*  1 */  {1.0, 0.0},  /* ditto */
/*  2 */  {0.5, 0.0},
/*  3 */  {0.16666666666666666,     9.25185853854297e-18},
/*  4 */  {0.041666666666666664,    2.3129646346357427e-18},
/*  5 */  {0.008333333333333333,    1.1564823173178714e-19},
/*  6 */  {0.001388888888888889,   -5.300543954373577e-20},
/*  7 */  {0.0001984126984126984,   1.7209558293420705e-22},
/*  8 */  {2.48015873015873e-5,     2.1511947866775882e-23},
/*  9 */  {2.7557319223985893e-6,  -1.858393274046472e-22},
/* 10 */  {2.755731922398589e-7,    2.3767714622250297e-23},
/* 11 */  {2.505210838544172e-8,   -1.448814070935912e-24},
/* 12 */  {2.08767569878681e-9,    -1.20734505911326e-25},
/* 13 */  {1.6059043836821613e-10,  1.2585294588752098e-26},
/* 14 */  {1.1470745597729725e-11,  2.0655512752830745e-28},
/* 15 */  {7.647163731819816e-13,   7.03872877733453e-30},
/* 16 */  {4.779477332387385e-14,   4.399205485834081e-31},
/* 17 */  {2.8114572543455206e-15,  1.6508842730861433e-31},
/* 18 */  {1.5619206968586225e-16,  1.1910679660273754e-32},
/* 19 */  {8.22063524662433e-18,    2.2141894119604265e-34},
/* 20 */  {4.110317623312165e-19,   1.4412973378659527e-36},
/* 21 */  {1.9572941063391263e-20, -1.3643503830087908e-36},
/* 22 */  {8.896791392450574e-22,  -7.911402614872376e-38},
/* 23 */  {3.868170170630684e-23,  -8.843177655482344e-40},
/* 24 */  {1.6117375710961184e-24, -3.6846573564509766e-41},
/* 25 */  {6.446950284384474e-26,  -1.9330404233703465e-42},
/* 26 */  {2.4795962632247976e-27, -1.2953730964765229e-43},
/* 27 */  {9.183689863795546e-29,   1.4303150396787322e-45},
/* 28 */  {3.279889237069838e-30,   1.5117542744029879e-46},
/* 29 */  {1.1309962886447716e-31,  1.0498015412959506e-47},
/* 30 */  {3.7699876288159054e-33,  2.5870347832750324e-49},
/* 31 */  {1.216125041553518e-34,   5.586290567888806e-51},
/* 32 */  {3.8003907548547434e-36,  1.7457158024652518e-52}
};

dd_pair dd_exp (dd_pair a) {
  int i;
  /* Handle large/small exponents */
  if (a.hi > 709.0) return (dd_pair)DD_INF; /* Inf */
  if (a.hi < -709.0) return (dd_pair)DD_NAUGHT;    /* 0 */
  /* 1. Find n = round(a/ln2) */
  double n = sun_floor(a.hi*DD_INV_LN2.hi + 0.5);
  /* 2. Compute r = a - n*ln2 (the remainder) */
  dd_pair x = dd_sub(a, dd_mul_d(DD_LN2, n));
  /* 3. Taylor series for e^r: 1 + r + r^2/2! + r^3/3! + r^4/4! + r^5/5! */
  /* For r < 0.35, 5-6 terms in DD math provide excellent precision */
  dd_pair x2 = dd_mul(x, x);
  dd_pair x3 = dd_mul(x2, x);
  dd_pair x4 = dd_mul(x2, x2);
  dd_pair x5 = dd_mul(x2, x3);
  dd_pair x10 = dd_mul(x5, x5);
  dd_pair x15 = dd_mul(x10, x5);
  dd_pair x20 = dd_mul(x10, x10);
  dd_pair x25 = dd_mul(x10, x15);
  dd_pair t[5] = { { 0, 0} };
  /* Coefficients */
  t[0] = dd_add((dd_pair)DD_ONE, x);
  t[1] = dd_mul(x2, inv_fact[2]);
  t[2] = dd_mul(x3, inv_fact[3]);
  t[3] = dd_mul(x4, inv_fact[4]);
  /* Sum the series: 1.0 + r + r^2/2 + r^3/6 + r^4/24 */
  /* z = x + inv_fact[2]*x2 + inv_fact[3]*x3 + inv_fact[4]*x4 */
  dd_pair z = (dd_pair){ 0.0, 0.0 };
  for (i=0; i < 4; i++) {
    z = dd_add(z, t[i]);
  }
  /* z2 = x5*(inv_fact[5] + x*inv_fact[6] + x2*inv_fact[7] +
     x3*inv_fact[8] + x4*inv_fact[9]) */
  t[0] = inv_fact[5];
  t[1] = dd_mul(x, inv_fact[6]);
  t[2] = dd_mul(x2, inv_fact[7]);
  t[3] = dd_mul(x3, inv_fact[8]);
  t[4] = dd_mul(x4, inv_fact[9]);
  dd_pair z2 = (dd_pair){ 0.0, 0.0 };
  for (i=0; i < 5; i++) {
    z2 = dd_add(z2, t[i]);
  }
  z2 = dd_mul(x5, z2);
  /* z3 = x10*(inv_fact[10] + x*inv_fact[11] + x2*inv_fact[12] +
     x3*inv_fact[13] + x4*inv_fact[14]) */
  t[0] = inv_fact[10];
  t[1] = dd_mul(x, inv_fact[11]);
  t[2] = dd_mul(x2, inv_fact[12]);
  t[3] = dd_mul(x3, inv_fact[13]);
  t[4] = dd_mul(x4, inv_fact[14]);
  dd_pair z3 = (dd_pair){ 0.0, 0.0 };
  for (i=0; i < 5; i++) {
    z3 = dd_add(z3, t[i]);
  }
  z3 = dd_mul(x10, z3);
  /* z4 = x15*(inv_fact[15] + x*inv_fact[16] + x2*inv_fact[17] +
     x3*inv_fact[18] + x4*inv_fact[19]) */
  t[0] = inv_fact[15];
  t[1] = dd_mul(x, inv_fact[16]);
  t[2] = dd_mul(x2, inv_fact[17]);
  t[3] = dd_mul(x3, inv_fact[18]);
  t[4] = dd_mul(x4, inv_fact[19]);
  dd_pair z4 = (dd_pair){ 0.0, 0.0 };
  for (i=0; i < 5; i++) {
    z4 = dd_add(z4, t[i]);
  }
  z4 = dd_mul(x15, z4);
  /* z5 = x20*(inv_fact[20] + x*inv_fact[21] + x2*inv_fact[22] +
     x3*inv_fact[23] + x4*inv_fact[24]) */
  t[0] = inv_fact[20];
  t[1] = dd_mul(x, inv_fact[21]);
  t[2] = dd_mul(x2, inv_fact[22]);
  t[3] = dd_mul(x3, inv_fact[23]);
  t[4] = dd_mul(x4, inv_fact[24]);
  dd_pair z5 = (dd_pair){ 0.0, 0.0 };
  for (i=0; i < 5; i++) {
    z5 = dd_add(z5, t[i]);
  }
  z5 = dd_mul(x20, z5);
  /* z6 = x25*(inv_fact[25] + x*inv_fact[26] + x2*inv_fact[27]) */
  t[0] = inv_fact[25];
  t[1] = dd_mul(x, inv_fact[26]);
  t[2] = dd_mul(x2, inv_fact[27]);
  dd_pair z6 = (dd_pair){ 0.0, 0.0 };
  for (i=0; i < 3; i++) {
    z6 = dd_add(z6, t[i]);
  }
  z6 = dd_mul(x25, z6);
  /* ((((z6+z5)+z4)+z3)+z2)+z + one(DoubleFloat{T}) (for one see above */
  t[0] = dd_add(z6, z5);
  t[0] = dd_add(t[0], z4);
  t[0] = dd_add(t[0], z3);
  t[0] = dd_add(t[0], z2);
  z = dd_add(t[0], z);
  /* 4. Scale by 2^n */
  z.hi = sun_ldexp(z.hi, (int)n);
  z.lo = sun_ldexp(z.lo, (int)n);
  return z;
}

/* exp2(x) = 2^x = e^(x * ln2), 7.4.1 */
dd_pair dd_exp2 (dd_pair a) {
  /* we do not use: return dd_exp(dd_mul(a, DD_LN2)); */
  /* 1. Handle overflow/underflow boundaries for 64-bit doubles */
  if (a.hi > 1023.0) return (dd_pair)DD_INF;
  if (a.hi < -1074.0) return (dd_pair)DD_NAUGHT;
  /* 2. Extract integer part n and fractional part r */
  /* 2^a = 2^n * 2^r */
  double n = sun_floor(a.hi + 0.5);
  dd_pair r = dd_sub(a, (dd_pair){n, 0.0});
  /* 3. Compute 2^r using e^(r * ln2) */
  /* Because |r| <= 0.5, the Taylor series is at its most accurate */
  dd_pair e_r = dd_exp(dd_mul(r, DD_LN2));
  /* 4. Scale by 2^n using ldexp */
  /* This is a lossless operation for both hi and lo parts */
  e_r.hi = sun_ldexp(e_r.hi, (int)n);
  e_r.lo = sun_ldexp(e_r.lo, (int)n);
  return e_r;
}

/* exp10(x) = 10^x = e^(x * ln10), 7.4.1 */
dd_pair dd_exp10 (dd_pair a) {
  /* return dd_exp(dd_mul(a, DD_LN10)); is too inaccurate */
  /* 1. Handle large/small exponents */
  if (a.hi > 308.0) return (dd_pair)DD_INF;
  if (a.hi < -308.0) return (dd_pair)DD_NAUGHT;
  /* 2. Decompose a into integer and fractional parts: 10^a = 10^n * 10^r */
  double n = sun_floor(a.hi + 0.5);
  dd_pair r = dd_sub(a, (dd_pair){n, 0.0});
  /* 3. Compute 10^r using 10^r = e^(r * ln10) */
  /* Since r is now very small (-0.5 to 0.5), the Taylor series is extremely stable */
  dd_pair r_ln10 = dd_mul(r, DD_LN10);
  dd_pair e_r = dd_exp(r_ln10);
  /* 4. Scale by 10^n */
  /* We use pow(10, n) for the high part and then perform a clean dd multiplication */
  dd_pair scale = {(double)sun_pow(10.0, n, 1), 0.0};
  return dd_mul(e_r, scale);
}

dd_pair dd_log (dd_pair a) {
  if (a.hi <= 0.0) return (dd_pair)DD_NAN;
  /* 1. Initial guess */
  double x0 = sun_log(a.hi);
  /* 2. Refinement: x1 = x0 + (a - exp(x0))/exp(x0) */
  dd_pair ex0 = dd_exp((dd_pair){x0, 0.0});
  dd_pair diff = dd_sub(a, ex0);
  dd_pair corr = dd_div(diff, ex0);
  return dd_add((dd_pair){x0, 0.0}, corr);
}

dd_pair dd_log2 (dd_pair a) {
  /* Step 1: Handle non-positive inputs */
  if (a.hi <= 0.0) return (dd_pair)DD_NAN;
  /* Step 2: Change of base formula: log2(a) = ln(a)/ln(2) */
  /* Using your previously defined dd_log and DD_LN2 constant */
  return dd_div(dd_log(a), DD_LN2);
}

dd_pair dd_log10 (dd_pair a) {  /* 7.4.1 */
  /* Step 1: Handle non-positive inputs */
  if (a.hi <= 0.0) return (dd_pair)DD_NAN;
  /* Step 2: Change of base formula: log10(a) = ln(a)/ln(10) */
  /* We use the pre-defined dd_log and the high-precision DD_LN10 constant */
  return dd_div(dd_log(a), DD_LN10);
}

dd_pair dd_sin (dd_pair a) {
  /* 1. Argument reduction */
  double k_double = sun_floor(a.hi*DD_INV_PI_2.hi + 0.5);
  int i, k = (int)k_double;
  dd_pair r = dd_sub(a, dd_mul_d(DD_PI_2, k_double));
  dd_pair r2 = dd_mul(r, r);
  /* 2. Taylor series: Horner evaluation */
  dd_pair s_res = (dd_pair)DD_ONE;
  for (i=25; i >= 3; i -= 2) {
    dd_pair term = dd_mul(r2, s_res);
    /* Divide dd_pair by dd_pair to maintain 106-bit precision */
    dd_pair divisor = (dd_pair){(double)(i*(i - 1)), 0.0};
    dd_pair divided_term = dd_div(term, divisor);
    s_res = dd_sub(DD_ONE, divided_term);
  }
  dd_pair sin_r = dd_mul(r, s_res);
  /* cos(r) Horner */
  dd_pair c_res = (dd_pair)DD_ONE;
  for (i=26; i >= 2; i -= 2) {
    dd_pair term = dd_mul(r2, c_res);
    dd_pair divisor = (dd_pair){(double)(i*(i - 1)), 0.0};
    dd_pair divided_term = dd_div(term, divisor);
    c_res = dd_sub(DD_ONE, divided_term);
  }
  dd_pair cos_r = c_res;
  /* 3. Selection */
  dd_pair res;
  switch (k & 3) {
    case 0:  res = sin_r; break;
    case 1:  res = cos_r; break;
    case 2:  res = (dd_pair){-sin_r.hi, -sin_r.lo}; break;
    case 3:  res = (dd_pair){-cos_r.hi, -cos_r.lo}; break;
    default: res = sin_r; break;
  }
  return res;
}

dd_pair dd_cos (dd_pair a) {
  double k_double = sun_floor(a.hi*DD_INV_PI_2.hi + 0.5);
  int i, k = (int)k_double;
  dd_pair r = dd_sub(a, dd_mul_d(DD_PI_2, k_double));
  dd_pair r2 = dd_mul(r, r);
  /* sin(r) Horner */
  dd_pair s_res = (dd_pair)DD_ONE;
  for (i=25; i >= 3; i -= 2) {
    dd_pair term = dd_mul(r2, s_res);
    dd_pair divisor = (dd_pair){(double)(i*(i - 1)), 0.0};
    dd_pair divided_term = dd_div(term, divisor);
    s_res = dd_sub((dd_pair)DD_ONE, divided_term);
  }
  dd_pair sin_r = dd_mul(r, s_res);
  /* cos(r) Horner */
  dd_pair c_res = (dd_pair)DD_ONE;
  for (i=26; i >= 2; i -= 2) {
    dd_pair term = dd_mul(r2, c_res);
    dd_pair divisor = (dd_pair){(double)(i*(i - 1)), 0.0};
    dd_pair divided_term = dd_div(term, divisor);
    c_res = dd_sub((dd_pair)DD_ONE, divided_term);
  }
  dd_pair cos_r = c_res;
  dd_pair res;
  switch (k & 3) {
    case 0:  res = cos_r; break;
    case 1:  res = (dd_pair){-sin_r.hi, -sin_r.lo}; break;
    case 2:  res = (dd_pair){-cos_r.hi, -cos_r.lo}; break;
    case 3:  res = sin_r; break;
    default: res = cos_r; break;
  }
  return res;
}

dd_pair dd_tan (dd_pair a) {
  /* Reuse the reduction and Taylor logic from dd_sin/dd_cos */
  /* This is a simplified wrapper for brevity */
  dd_pair s = dd_sin(a);
  dd_pair c = dd_cos(a);
  return dd_div(s, c);
}

/* Secant: 1/cos(a) */
dd_pair dd_sec (dd_pair a) {
  dd_pair cos_a = dd_cos(a);
  /* Use the reciprocal logic: 1.0/cos_a */
  return dd_inv(cos_a);
}

/* Cosecant: 1/sin(a) */
dd_pair dd_csc (dd_pair a) {
  dd_pair sin_a = dd_sin(a);
  /* Use the reciprocal logic: 1.0/sin_a */
  return dd_inv(sin_a);
}

/* Cotangent: cos(a)/sin(a) */
dd_pair dd_cot (dd_pair a) {
  dd_pair s = dd_sin(a);
  dd_pair c = dd_cos(a);
  /* Manual dd_div(c, s) logic for maximum precision */
  /* Step 1: Approximate quotient */
  double q0 = c.hi/s.hi;
  /* Step 2: Refine using: q1 = q0 + (c - s*q0)/s */
  dd_pair sq0 = dd_mul_d(s, q0);
  /* Compute remainder: diff = c - sq0 */
  dd_pair diff = dd_sub(c, sq0);
  /* Correction term: diff/s.hi (approximate is fine for the tail) */
  double corr = (diff.hi + diff.lo)/s.hi;
  /* Final result */
  if (dd_signbit(a)) corr = -corr;
  return two_sum(q0, corr);
}

dd_pair dd_sinc (dd_pair x) {
  double abs_x = (x.hi < 0) ? -x.hi : x.hi;
  /* Taylor series for small x to avoid precision loss and division by zero.
     The threshold 1e-4 is safe for maintaining ~31 decimal digits. */
  if (abs_x < 1e-4) {
    /* sinc(x) = 1 - x^2/6 + x^4/120 - x^6/5040 ... */
    dd_pair x2 = dd_mul(x, x);
    /* Term 1: 1.0 */
    dd_pair res = DD_ONE;
    /* Term 2: -x^2/6 */
    dd_pair term2 = dd_mul_d(x2, -1.0/6.0);
    res = dd_add(res, term2);
    /* Term 3: x^4/120 */
    dd_pair x4 = dd_mul(x2, x2);
    dd_pair term3 = dd_mul_d(x4, 1.0/120.0);
    res = dd_add(res, term3);
    /* Term 4: -x^6/5040 (Optional but recommended for 106-bit depth) */
    dd_pair x6 = dd_mul(x4, x2);
    dd_pair term4 = dd_mul_d(x6, -1.0/5040.0);
    res = dd_add(res, term4);
    return res;
  }
  /* Standard case: sin(x)/x */
  dd_pair s = dd_sin(x);
  /* Use the high-precision division refinement */
  double q0 = s.hi/x.hi;
  dd_pair xq0 = dd_mul_d(x, q0);
  dd_pair diff = dd_sub(s, xq0);
  double corr = (diff.hi + diff.lo)/x.hi;
  return two_sum(q0, corr);
}

dd_pair dd_sinh (dd_pair x) {
  /* Guard against overflow (matches Julia's maxhyp_fp64max) */
  if (fabs(x.hi) > 710.47) {
    return (dd_pair){(x.hi > 0) ? 1.0/0.0 : -1.0/0.0, 0.0};
  }
  /* signbit(x) && return -sinh(-x) */
  if (x.hi < 0.0) {
    dd_pair res = dd_sinh((dd_pair){-x.hi, -x.lo});
    return (dd_pair){-res.hi, -res.lo};
  }
  /* y = exp(x) - exp(-x) */
  dd_pair exp_x = dd_exp(x);
  dd_pair exp_neg_x = dd_inv(exp_x);
  dd_pair y = dd_sub(exp_x, exp_neg_x);
  /* z = y*0.5 */
  return (dd_pair){y.hi*0.5, y.lo*0.5};
}

dd_pair dd_cosh (dd_pair x) {
  if (fabs(x.hi) > 710.47) return (dd_pair)DD_INF;
  /* cosh(x) is symmetric, so we can work with absolute value */
  dd_pair abs_x = (x.hi < 0.0) ? (dd_pair){-x.hi, -x.lo} : x;
  /* y = exp(x) + exp(-x) */
  dd_pair exp_x = dd_exp(abs_x);
  dd_pair exp_neg_x = dd_inv(exp_x);
  dd_pair y = dd_add(exp_x, exp_neg_x);
  return (dd_pair){y.hi*0.5, y.lo*0.5};
}

dd_pair dd_tanh (dd_pair x) {
  /* For large x, tanh approaches 1 or -1 */
  if (fabs(x.hi) > 20.0) { /* 20 is enough for 106-bit saturation */
    return (x.hi > 0) ? (dd_pair)DD_ONE : (dd_pair){-1.0, 0.0};
  }
  return dd_div(dd_sinh(x), dd_cosh(x));
}

/* Hyperbolic Secant: 1/cosh(a) */
dd_pair dd_sech (dd_pair a) {
  dd_pair cosh_a = dd_cosh(a);
  return dd_inv(cosh_a);
}

/* Hyperbolic Cosecant: 1/sinh(a) */
dd_pair dd_csch (dd_pair a) {
  dd_pair sinh_a = dd_sinh(a);
  return dd_inv(sinh_a);
}

/* Hyperbolic Cotangent: cosh(a)/sinh(a) */
dd_pair dd_coth (dd_pair a) {
  /* Using the same refined division logic as dd_cot */
  dd_pair s = dd_sinh(a);
  dd_pair c = dd_cosh(a);
  /* Step 1: Approximate quotient */
  double q0 = c.hi/s.hi;
  /* Step 2: Refinement: q1 = q0 + (c - s*q0)/s */
  dd_pair sq0 = dd_mul_d(s, q0);
  dd_pair diff = dd_sub(c, sq0);
  /* Correction term */
  double corr = (diff.hi + diff.lo)/s.hi;
  return two_sum(q0, corr);
}

dd_pair dd_atan2 (dd_pair y, dd_pair x);

dd_pair dd_atan (dd_pair x) {
  /* Using the atan2 logic: atan(x) = atan2(x, 1) */
  return dd_atan2(x, (dd_pair)DD_ONE);
}

dd_pair dd_asin (dd_pair x) {
  /* Check for domain errors */
  if (x.hi > 1.0 || x.hi < -1.0) return DD_NAN;
  /* asin(x) = atan2(x, sqrt(1 - x^2)) */
  dd_pair x2 = dd_mul(x, x);
  dd_pair root = dd_sqrt(dd_sub((dd_pair)DD_ONE, x2));
  return dd_atan2(x, root);
}

dd_pair dd_acos (dd_pair x) {
  /* Check for domain errors */
  if (x.hi > 1.0 || x.hi < -1.0) return DD_NAN;
  /* acos(x) = atan2(sqrt(1 - x^2), x) */
  dd_pair x2 = dd_mul(x, x);
  dd_pair root = dd_sqrt(dd_sub((dd_pair)DD_ONE, x2));
  return dd_atan2(root, x);
}

#define DD_ZERO DD_NAUGHT
#define dd_neg dd_unm

static const double PI2_HI  = 1.570796326794896558e+00;
static const double PI2_LO  = 6.123233995736764803e-17;
static const double PI2_LO2 = 8.478427660368899958e-32;

/* Factorial Reciprocals as dd_pairs */
static const dd_pair DD_INV_2f  = { -5.00000000000000000e-01,  0.00000000000000000e+00 };
static const dd_pair DD_INV_3f  = { -1.66666666666666657e-01, -9.25185853854297066e-18 };
static const dd_pair DD_INV_4f  = {  4.16666666666666644e-02,  2.31296463463574266e-19 };
static const dd_pair DD_INV_5f  = {  8.33333333333333322e-03,  1.15740740740740731e-19 };
static const dd_pair DD_INV_6f  = { -1.38888888888888884e-03, -1.92901234567901219e-21 };
static const dd_pair DD_INV_7f  = { -1.98412698412698413e-04, -1.25816434460596323e-21 };
static const dd_pair DD_INV_8f  = {  2.48015873015873016e-05,  1.57270543075745404e-23 };
static const dd_pair DD_INV_9f  = {  2.75573192239858907e-06,  1.23330105370215750e-23 };
static const dd_pair DD_INV_10f = { -2.75573192239858907e-07, -1.23330105370215750e-25 };
static const dd_pair DD_INV_11f = { -2.50521083854417188e-08, -6.64322477382215714e-26 };
static const dd_pair DD_INV_12f = {  2.08767569878680990e-09,  5.53602064485179762e-27 };
static const dd_pair DD_INV_13f = {  1.60590438368216146e-10,  1.25055964894318182e-28 };
static const dd_pair DD_INV_14f = { -2.05885177395148906e-12, -4.38536294717112285e-30 };
static const dd_pair DD_INV_15f = { -7.64716373181981648e-13, -3.24794712850383178e-30 };

static dd_pair dd_pi_reduce (dd_pair theta, int *k) {
  double k_double = floor(theta.hi * TWOOPI + 0.5);
  *k = (int)k_double;
  /* Three-stage reduction for 106-bit stability */
  dd_pair r = dd_sub(theta, two_prod(k_double, PI2_HI));
  r = dd_sub(r, two_prod(k_double, PI2_LO));
  r = dd_sub(r, (dd_pair){k_double * PI2_LO2, 0.0}); /* Final tail correction */
  return r;
}

void dd_sincos (dd_pair theta, dd_pair *s, dd_pair *c) {
  int k;
  dd_pair r = dd_pi_reduce(theta, &k);
  /* Precompute powers to r^15 */
  dd_pair r2 = dd_mul(r, r);
  dd_pair r3 = dd_mul(r, r2);
  dd_pair r4 = dd_mul(r2, r2);
  dd_pair r5 = dd_mul(r3, r2);
  dd_pair r6 = dd_mul(r4, r2);
  dd_pair r7 = dd_mul(r5, r2);
  dd_pair r8 = dd_mul(r6, r2);
  dd_pair r9 = dd_mul(r7, r2);
  dd_pair r10 = dd_mul(r8, r2);
  dd_pair r11 = dd_mul(r9, r2);
  dd_pair r12 = dd_mul(r10, r2);
  dd_pair r13 = dd_mul(r11, r2);
  dd_pair r14 = dd_mul(r12, r2);
  dd_pair r15 = dd_mul(r13, r2);
  /* Sine Series Expansion (r^1 to r^15) */
  dd_pair s_tail = dd_mul(r15, DD_INV_15f);
  s_tail = dd_add(s_tail, dd_mul(r13, DD_INV_13f));
  s_tail = dd_add(s_tail, dd_mul(r11, DD_INV_11f));
  s_tail = dd_add(s_tail, dd_mul(r9,  DD_INV_9f));
  s_tail = dd_add(s_tail, dd_mul(r7,  DD_INV_7f));
  s_tail = dd_add(s_tail, dd_mul(r5,  DD_INV_5f));
  s_tail = dd_add(s_tail, dd_mul(r3,  DD_INV_3f));
  dd_pair s_res = dd_add(r, s_tail);
  /* Cosine Series Expansion (r^0 to r^14) */
  dd_pair c_tail = dd_mul(r14, DD_INV_14f);
  c_tail = dd_add(c_tail, dd_mul(r12, DD_INV_12f));
  c_tail = dd_add(c_tail, dd_mul(r10, DD_INV_10f));
  c_tail = dd_add(c_tail, dd_mul(r8,  DD_INV_8f));
  c_tail = dd_add(c_tail, dd_mul(r6,  DD_INV_6f));
  c_tail = dd_add(c_tail, dd_mul(r4,  DD_INV_4f));
  c_tail = dd_add(c_tail, dd_mul(r2,  DD_INV_2f));
  dd_pair c_res = dd_add((dd_pair){1.0, 0.0}, c_tail);
  /* Map to correct quadrant */
  switch (k & 3) {
    case 0: *s = s_res;         *c = c_res;         break;
    case 1: *s = c_res;         *c = dd_neg(s_res); break;
    case 2: *s = dd_neg(s_res); *c = dd_neg(c_res); break;
    case 3: *s = dd_neg(c_res); *c = s_res;         break;
  }
}

dd_pair dd_atan2 (dd_pair y, dd_pair x) {
  int i;
  /* 1. Handle the origin */
  if (x.hi == 0.0 && y.hi == 0.0) return DD_ZERO;
  /* 2. Record the signs for later reconstruction */
  int sign_x = (x.hi < 0) ? -1 : 1;
  int sign_y = (y.hi < 0) ? -1 : 1;
  /* 3. Force everything into the First Quadrant (0 to pi/2) */
  dd_pair abs_x = (x.hi < 0) ? dd_neg(x) : x;
  dd_pair abs_y = (y.hi < 0) ? dd_neg(y) : y;
  /* 4. Use your stable Newton-Raphson on the 'safe' positive values */
  /* We use the ratio to get the initial estimate */
  double t0 = sun_atan2(abs_y.hi, abs_x.hi);
  dd_pair theta = {t0, 0.0};
  for (i=0; i < 3; i++) {
    dd_pair s = dd_sin(theta);
    dd_pair c = dd_cos(theta);
    /* Corrected stable formula for the 1st quadrant: */
    /* num = abs_y*c - abs_x*s, den = abs_x*c + abs_y*s */
    dd_pair num = dd_sub(dd_mul(abs_y, c), dd_mul(abs_x, s));
    dd_pair den = dd_add(dd_mul(abs_x, c), dd_mul(abs_y, s));
    if (den.hi == 0.0) break;
    dd_pair corr = dd_div(num, den);
    theta = dd_add(theta, corr);
    if (sun_fabs(corr.hi) < sun_fabs(theta.hi)*1e-32) break;
  }
  /* 5. Reconstruction Logic (Symmetry Mapping) */
  /* If x was negative, we are in Quadrant 2 or 3: angle = PI - angle */
  if (sign_x < 0) {
    theta = dd_sub(DD_PI, theta);
  }
  /* If y was negative, flip the final sign (Odd Function Symmetry) */
  if (sign_y < 0) {
    theta = dd_neg(theta);
  }
  return theta;
}

/* Inverse Secant: acos(1/a) */
dd_pair dd_asec (dd_pair a) {
  /* Step 1: Compute reciprocal of the argument */
  dd_pair inv_a = dd_inv(a);
  /* Step 2: Use the identity asec(x) = acos(1/x) */
  return dd_acos(inv_a);
}

/* Inverse Cosecant: asin(1/a) */
dd_pair dd_acsc (dd_pair a) {
  /* Step 1: Compute reciprocal of the argument */
  dd_pair inv_a = dd_inv(a);
  /* Step 2: Use the identity acsc(x) = asin(1/x) */
  return dd_asin(inv_a);
}

/* Inverse Cotangent: atan(1/a) */
dd_pair dd_acot (dd_pair a) {
  /* Handle the singularity at 0 directly for stability */
  if (a.hi == 0.0) {
    return dd_mul_d(DD_PI, 0.5); /* pi/2 */
  }
  dd_pair inv_a = dd_inv(a);
  dd_pair res = dd_atan(inv_a);
  /* If a is negative, shift the result by PI to stay in the (0, pi) range */
  if (a.hi < 0.0) {
    res = dd_add(res, DD_PI);
  }
  return res;
}

/* Lanczos Coefficients for approx 30 digits of precision (g=5) */
static const dd_pair LY[] = {
  { 1.0000000001900149,      8.2323233762130100e-17},
  { 76.180091729471463,     -3.5153200155018615e-15},
  {-86.505320329416776,      2.9151528643039600e-15},
  { 24.014098240830911,     -1.0182414771746700e-15},
  {-1.2317395724501550,      1.2404077677843000e-16},
  { 0.001208650973866179,    2.0625902506634500e-20},
  {-0.000005395239384953,   -3.5933615964098400e-22}
};

dd_pair dd_pair_from_d (double d) {
  dd_pair res;
  res.hi = d;
  res.lo = 0.0;
  return res;
}

dd_pair dd_lgamma (dd_pair x) {
  int i;
  /* Use the identity Gamma(x+1) = x*Gamma(x) if x is small */
  /* For lgamma: ln(Gamma(x)) = ln(Gamma(x+1)) - ln(x) */
  double y = dd2double(x);
  if (y == 1.0) {
    return (dd_pair)DD_ONE;
  } else if (y <= 0) {
    return (dd_pair)DD_NAN;
  }
  dd_pair tmp = dd_add(x, dd_pair_from_d(5.5)); /* x + g + 0.5 */
  /* (x + 0.5)*ln(tmp) */
  dd_pair log_part = dd_mul(dd_add(x, DD_HALF), dd_log(tmp));
  /* Summing Ag(x) */
  dd_pair a = LY[0];
  for (i=1; i < 7; i++) {
    dd_pair denom = dd_add(x, dd_pair_from_d((double)i));
    a = dd_add(a, dd_div(LY[i], denom));
  }
  /* ln(sqrt(2*pi)*a/x) */
  /* dd_pair sqrt2pi = dd_pair_from_d(2.5066282746310005); */
  dd_pair final_ln = dd_log(dd_div(dd_mul(DD_SQRT_2PI, a), x));
  /* Result = log_part - tmp + final_ln */
  return dd_add(dd_sub(log_part, tmp), final_ln);
}

/* Note that 170! is the largest factorial that fits in a standard double range (1.7×10^308). */
dd_pair dd_fac (dd_pair a) {
  int i;
  /* 1. Handle Negative Arguments */
  if (a.hi < 0.0) return (dd_pair)DD_NAN;
  /* 2. Exact Integer Case (up to ~30 for speed) */
  /* We check if it's an integer by comparing the double part to its cast */
  if (a.lo == 0.0 && a.hi <= 30.0 && a.hi == (double)((int)a.hi)) {
    int n = (int)a.hi;
    if (n == 0) return (dd_pair)DD_NAN;
    dd_pair res = DD_ONE;
    for (i=2; i <= n; i++) {
      res = dd_mul_d(res, (double)i);
    }
    return res;
  }
  /* 3. General Case: Gamma(a + 1) */
  /* We manually create a dd_pair for 1.0 to use the standard dd_add */
  /* dd_pair one = DD_ONE; */
  dd_pair a_plus_one = dd_add(a, DD_ONE);
  /* Ensure these functions exist in your ddmath.h */
  return dd_exp(dd_lgamma(a_plus_one));
}

dd_pair dd_floor (dd_pair a) {
  double hi = floor(a.hi);
  double lo = 0.0;
  if (hi == a.hi) {
    /* If the high part is an integer, the low part determines the floor */
    lo = sun_floor(a.lo);
    /* Re-normalize: if lo is -1.0, it affects the high part */
    return two_sum(hi, lo);
  }
  return (dd_pair){hi, 0.0};
}

dd_pair dd_ceil (dd_pair a) {
  double hi = ceil(a.hi);
  double lo = 0.0;
  if (hi == a.hi) {
    /* If the high part is an integer, the low part determines the ceil */
    lo = sun_ceil(a.lo);
    /* Re-normalize: if lo is 1.0, it affects the high part */
    return two_sum(hi, lo);
  }
  return (dd_pair){hi, 0.0};
}

/* round to nearest integer */
dd_pair dd_round (dd_pair a) {
  double hi = sun_round(a.hi);
  if (hi == a.hi) {
    /* High part is an integer, check low part to see if it nudges the result */
    double lo = sun_round(a.lo);
    return two_sum(hi, lo);
  }
  /* Check if a.lo was enough to push a.hi across a midpoint boundary */
  /* This happens if a.hi was something like 2.4999... and a.lo pushed it to 2.5 */
  double diff = a.hi - hi;
  if (fabs(diff) == 0.5 && ((diff > 0 && a.lo < 0) || (diff < 0 && a.lo > 0))) {
     /* Re-evaluate if the tail changed the rounding direction */
     return dd_round(two_sum(a.hi, a.lo));
  }
  return (dd_pair){hi, 0.0};
}

/* trunc toward Zero */
dd_pair dd_trunc (dd_pair a) {
  return (a.hi >= 0.0) ? dd_floor(a) : dd_ceil(a);
}

dd_pair dd_frac (dd_pair a) {
  /* frac = a - floor(a) */
  return dd_sub(a, dd_trunc(a));
}

dd_pair dd_modf (dd_pair a, dd_pair *iptr) {
  /* Store the integer part in the provided pointer */
  *iptr = dd_trunc(a);
  /* Return the fractional part */
  return dd_sub(a, *iptr);
}

/* renorm (Internal Precision Rounding): Sometimes "rounding" refers to the internal
   process of ensuring the hi and lo parts are as "separated" as possible.
   While your two_sum and two_prod functions handle this automatically, a dedicated
   renormalization ensures that. */
dd_pair dd_renorm (double hi, double lo) {
  /* This is effectively a robust two_sum */
  double s = hi + lo;
  double v = s - hi;
  double e = (hi - (s - v)) + (lo - v);
  return (dd_pair){s, e};
}

dd_pair dd_ldexp (dd_pair a, int e) {
  /* We scale both parts by the same power of 2 */
  /* This preserves the relative gap between hi and lo */
  return (dd_pair){
    sun_ldexp(a.hi, e),
    sun_ldexp(a.lo, e)
  };
}

dd_pair dd_frexp (dd_pair a, int *e) {
  /* 1. Decompose the high part to get the exponent */
  double f_hi = sun_frexp(a.hi, e);
  /* 2. Scale the low part by the SAME exponent to keep them aligned */
  /* We use negative *exp because we are 'unscaling' the value */
  double f_lo = sun_ldexp(a.lo, -(*e));

  return (dd_pair){f_hi, f_lo};
}


/* Printing function: Since this uses a static buffer, you must use it immediately or copy it:

   WRONG: Both will point to the same string (the value of b)
   const char* str_a = dd_to_str(a);
   const char* str_b = dd_to_str(b);
   printf("%s %s", str_a, str_b);

   CORRECT:
   printf("Value A: %s\n", dd_to_str(a));
   printf("Value B: %s\n", dd_to_str(b)); */
const char *dd_to_str (dd_pair a) {
  static char buffer[128];
  int i, decimal_exp;
  if (isinf(a.hi) || isnan(a.hi)) {
    sprintf(buffer, "%g", a.hi);
    return buffer;
  }
  if (a.hi == 0.0 && a.lo == 0.0)
    return "0.0000000000000000000000000000000e+00";
  /* 1. Calculate exponent */
  decimal_exp = (int)floor(log10(fabs(a.hi + a.lo)));
  /* 2. Scale the value to [1, 10) */
  dd_pair scaled = dd_mul(a, dd_pow_n((dd_pair){10.0, 0.0}, -decimal_exp));
  /* 3. Handle negative numbers */
  int pos = 0;
  if (scaled.hi < 0 || (scaled.hi == 0 && scaled.lo < 0)) {
    buffer[pos++] = '-';
    scaled.hi = -scaled.hi;
    scaled.lo = -scaled.lo;
  }
  /* 4. The Extraction Loop */
  for (i = 0; i < 32; i++) {
    /* 1. Extract the digit using the combined weight */
    double val = scaled.hi + scaled.lo;
    int digit = (int)floor(val + 1e-14);
    if (digit > 9) digit = 9;
    if (digit < 0) digit = 0;
    buffer[pos++] = (char)('0' + digit);
    if (i == 0) buffer[pos++] = '.';
    /* 2. MANUAL SUBTRACTION - Do not rely on dd_sub for now */
    /* This ensures the lo part isn't dropped by a bad metamethod/function */
    double t_hi = scaled.hi - (double)digit;
    double t_lo = scaled.lo;
    /* 3. RENORMALIZE - This is the key */
    /* It pulls the high-precision 'remainder' back into the hi double */
    scaled.hi = t_hi + t_lo;
    scaled.lo = t_lo - (scaled.hi - t_hi);
    /* 4. SHIFT - Pull the next bits up */
    /* Use your dd_mul_d or do it manually to be safe */
    double m_hi = scaled.hi*10.0;
    double m_lo = scaled.lo*10.0;
    scaled.hi = m_hi + m_lo;
    scaled.lo = m_lo - (scaled.hi - m_hi);
  }
  sprintf(buffer + pos, "e%+03d", decimal_exp);
  return buffer;
}

int dd_eq (dd_pair a, dd_pair b) {
  return (a.hi == b.hi && a.lo == b.lo);
}

int dd_lt (dd_pair a, dd_pair b) {
  return (a.hi < b.hi || (a.hi == b.hi && a.lo < b.lo));
}

int dd_gt (dd_pair a, dd_pair b) {
  return (a.hi > b.hi || (a.hi == b.hi && a.lo > b.lo));
}

int dd_le (dd_pair a, dd_pair b) {
  return (a.hi < b.hi || (a.hi == b.hi && a.lo <= b.lo));
}

int dd_ge (dd_pair a, dd_pair b) {
  return (a.hi > b.hi || (a.hi == b.hi && a.lo >= b.lo));
}

int dd_approx (dd_pair x, dd_pair y, dd_pair eps) {
  /* 1. Identity and NaN check */
  if ((x.hi == y.hi && x.lo == y.lo) || (isnan(x.hi) && isnan(y.hi))) {
    return 1;
  }
  /* 2. Calculate absolute distance |x - y| */
  dd_pair dist = dd_abs(dd_sub(x, y));
  /* 3. Infinite distance check (overflow in subtraction) */
  if (isinf(dist.hi)) return 0;
  /* 4. Absolute tolerance check: dist <= eps */
  if (dd_le(dist, eps)) return 1;
  /* 5. Relative tolerance check: dist <= eps*max(|x|, |y|) */
  dd_pair abs_x = dd_abs(x);
  dd_pair abs_y = dd_abs(y);
  dd_pair max_val = dd_gt(abs_x, abs_y) ? abs_x : abs_y;
  dd_pair rel_tol = dd_mul(eps, max_val);
  return dd_le(dist, rel_tol);
}

int dd_zero (dd_pair a) {
  return (a.hi == 0.0 && a.lo == a.lo);
}

int dd_nonzero (dd_pair a) {
  return (a.hi != 0.0 || a.lo != a.lo);
}

/* Returns non-zero if the value is NaN */
int dd_isnan (dd_pair a) {
  return isnan(a.hi);
}

/* Returns non-zero if the value is +inf or -inf */
int dd_isinf (dd_pair a) {
  return isinf(a.hi);
}

/* Returns non-zero if the value is a real, finite number */
/* (Not NaN and not Infinity) */
int dd_isfinite (dd_pair a) {
  return isfinite(a.hi);
}

