/*
** $Id: ints.c,v 0.1 October 20, 2025 $
** 64-bit Integer Library
** See Copyright Notice in agena.h
*/

#define ints_c
#define LUA_LIB

#include <stdlib.h>
#include <string.h>
#include <float.h>     /* DBL_MIN, DBL_MAX */
#include <inttypes.h>  /* for int64_t and PRId64 */
#include <stdbool.h>
#include <limits.h>    /* For INT64_MAX and INT64_MIN */
#include <errno.h>

#include "agena.h"

#include "agenalib.h"
#include "agnhlps.h"
#include "agnxlib.h"

#include "ints.h"


/* Taken from: https://graphics.stanford.edu/~seander/bithacks.html
   "Compute the integer absolute value (abs) without branching", 6.2.2 */
static INLINE int64_t abs64 (int64_t v) {
  int64_t const mask = v >> (sizeof(int64_t)*CHAR_BIT - 1);
  return (v + mask) ^ mask;
}


/* Conversion from/to strings **************************************************************************/

/* Safely converts a string to a uint64_t. Generated by Gemini AI, public domain. */
static uint64_t safe_str_to_uint64 (const char *str, int *rc) {
  char *endptr;
  uint64_t result;
  const char *oldstr = str;
  if (str == NULL) { *rc = 4; return 0; }
  *rc = 0;
  /* 1. Reset errno to 0 before the call to distinguish between  successful execution and error conditions. */
  errno = 0;
  /* 2. Perform the conversion using base 10 (decimal). */
  result = strtoull(str, &endptr, 10);
  /* 3A. Check for underflow/overflow (result out of range). If the result equals ULLONG_MAX (UINT64_MAX) AND
         errno is ERANGE, an overflow/underflow occurred. */
  if (errno == ERANGE) {  /* fprintf(stderr, "Error: Value out of range for uint64_t.\n"); */
    *rc = 1; return 0;
  }
  /* 3B. Check for no conversion (input was not a number)
         If endptr points to the start of the string, no digits were processed. */
  if (endptr == str) {  /* fprintf(stderr, "Error: No digits were found in the string.\n"); */
    *rc = 2; return 0;
  }
  /* 3C. Check for extraneous characters (non-numeric data after the number)
         The string should be fully consumed (endptr should point to the null terminator). */
  if (*endptr != '\0') {  /* try hex string */
    int r;
    lua_State *L = NULL;
    result = lua_stringtouint64(L, oldstr, 0, NULL, &r);
    if (r) {  /* fprintf(stderr, "Error: Invalid character(s) found after the number: %s\n", endptr); */
      *rc = r; return 0;
    }
  }
  return result;
}

static int64_t safe_str_to_int64 (const char *str, int *rc) {
  char *endptr;
  int64_t result;
  const char *oldstr = str;
  if (str == NULL) { *rc = 4; return 0; }
  *rc = 0;
  /* 1. Reset errno to 0 before the call to distinguish between  successful execution and error conditions. */
  errno = 0;
  /* 2. Perform the conversion using base 10 (decimal). */
  result = strtoll(str, &endptr, 10);
  /* 3A. Check for underflow/overflow (result out of range). If the result equals ULLONG_MAX (UINT64_MAX) AND
         errno is ERANGE, an overflow/underflow occurred. */
  if (errno == ERANGE) { /* fprintf(stderr, "Error: Value out of range for uint64_t.\n"); */
    *rc = 1; return 0;
  }
  /* 3B. Check for no conversion (input was not a number)
         If endptr points to the start of the string, no digits were processed. */
  if (endptr == str) {  /* fprintf(stderr, "Error: No digits were found in the string.\n"); */
    *rc = 2; return 0;
  }
  /* 3C. Check for extraneous characters (non-numeric data after the number, e.g. scientific notation)
         The string should be fully consumed (endptr should point to the null terminator). */
  if (*endptr != '\0') {  /* try hex string */
    int r;
    lua_State *L = NULL;
    result = lua_stringtoint64(L, oldstr, 0, NULL, &r);
    if (r) {  /* fprintf(stderr, "Error: Invalid character(s) found after the number: %s\n", endptr); */
      *rc = r; return 0;
    }
  }
  return result;
}

/* Generated by Gemini AI, public domain */
static int safe_int64_to_string (int64_t num, char *buffer, size_t buffer_size, int *rc) {
  /* PRId64 expands to the correct format specifier for int64_t (e.g., "lld" or "ld" depending on the system). */
  int result = snprintf(buffer, buffer_size, "%" PRId64, num);
  if (result < 0) {  /* encoding error or other system issue */
    buffer[0] = '\0';  /* ensure buffer is empty or 0-terminated */
    *rc = -1;
  } else if ((size_t)result >= buffer_size) {  /* output was truncated (buffer was too small) */
    *rc = 1;
  } else {
    *rc = 0;
  }
  return result;
}

/* Generated by Gemini AI, public domain */
static int safe_uint64_to_string (uint64_t num, char *buffer, size_t buffer_size, int *rc) {
  /* PRIu64 expands to the correct format specifier for uint64_t
     (e.g., "llu" or "lu" depending on the system) for UNSIGNED decimal output. */
  int result = snprintf(buffer, buffer_size, "%" PRIu64, num);
  if (result < 0) {
    buffer[0] = '\0';
    *rc = -1;
  } else if ((size_t)result >= buffer_size) {  /* buffer was too small and output was truncated */
    *rc = 1;
  } else {
    *rc = 0;
  }
  return result;
}


/* Extraction & generation etc. ************************************************************************/

/* Generated by Gemini AI, put into the public domain, 6.2.3 */

/* Extracts the High (Most Significant) 32-bit part */
static uint32_t gethighu32 (uint64_t n64) {
  /* Right shift by 32 bits discards the low 32 bits, moving the high 32 bits into the lower position. */
  return (uint32_t)(n64 >> 32);
}

/* Extracts the Low (Least Significant) 32-bit part */
static uint32_t getlowu32 (uint64_t n64) {
  /* A simple cast or a bitwise AND with 0xFFFFFFFF (as a mask), ensures only the low 32 bits are kept. */
  return (uint32_t)(n64 & 0xFFFFFFFFULL);  /* 6.8.2 ULL stadardisation */
}

/* Extracts the High (Most Significant) 32-bit part of an int64_t */
static int32_t gethigh32 (int64_t n64) {
  /* 1. Cast to uint64_t for a safe, logical (zero-filling) right shift. */
  /* 2. Right shift by 32 bits to move the high pattern to the low position. */
  /* 3. Cast the final 32-bit pattern back to an int32_t. */
  return (int32_t)((uint64_t)n64 >> 32);
}

static int32_t getlow32 (int64_t n64) {
  /* 1. Bitwise AND with an unsigned 64-bit mask (0xFFFFFFFFULL) to isolate the low 32 bits. */
  /* 2. The mask is applied to the int64_t. */
  /* 3. The final 32-bit pattern is cast to an int32_t. */
  return (int32_t)(n64 & 0xFFFFFFFFULL);  /* 6.8.2 ULL stadardisation */
}

/* Reassembles the two 32-bit parts back into a 64-bit integer */
static uint64_t reassemble_64 (uint32_t high_32, uint32_t low_32) {
  /* 1. Cast the high part to 64-bit to prevent overflow during the shift.
     2. Left shift the high part by 32 bits to put it back in place.
     3. Bitwise OR the result with the low part. */
  return ((uint64_t)high_32 << 32) | low_32;
}

static void sethighu64 (uint64_t *x, uint32_t h) {
  *x = (*x & 0x00000000FFFFFFFFULL) | ((uint64_t)h << 32);  /* 6.8.2 ULL stadardisation */
}

static void setlowu64 (uint64_t *x, uint32_t l) {
  *x = (*x & 0xFFFFFFFF00000000ULL) | ((uint64_t)l);  /* 6.8.2 ULL stadardisation */
}

static void sethigh64 (int64_t *x, int32_t h) {
  /* Cast the input 'h' to UNsigned 32-bit first, then to UNsigned 64-bit,
     to prevent sign extension, ensuring only the 32 bits are moved up. */
  uint64_t shifted_h = (uint64_t)(uint32_t)h << 32;
  /* The mask should use 'UL' (unsigned long/64-bit) for safety and clarity.
     The result is assigned back to the signed int64_t *x. */
  *x = (*x & 0x00000000FFFFFFFFULL) | (int64_t)shifted_h;  /* 6.8.2 ULL stadardisation */
}

static void setlow64 (int64_t *x, int32_t l) {
  /* Crucially treats l as a 32-bit pattern to prevent sign extension */
  uint64_t new_low = (uint64_t)(uint32_t)l;
  *x = (*x & 0xFFFFFFFF00000000ULL) | (int64_t)new_low;  /* 6.8.2 ULL stadardisation */
}

static inline uint64_t double2bitwiseuint64 (double x) {
  uint64_t bits;
  memcpy(&bits, &x, sizeof bits);
  return bits;
}

static inline int64_t double2bitwiseint64 (double x) {
  int64_t bits;
  memcpy(&bits, &x, sizeof bits);
  return bits;
}

static inline double bitwiseuint64todouble (uint64_t x) {
  double y;
  memcpy(&y, &x, sizeof y);
  return y;
}

static inline double bitwiseint64todouble (int64_t x) {
  double y;
  memcpy(&y, &x, sizeof y);
  return y;
}


/* Checks **********************************************************************************/

static Ints *aux_checkint (lua_State *L, int idx) {
  if (isints(L, idx)) {
    /* do nothing */
  } else if (agn_isnonnegint(L, idx)) {
    createuint64(L, agn_tonumber(L, idx));
    lua_replace(L, idx);
  } else if (agn_isstring(L, idx)) {
    int rc;
    uint64_t x = safe_str_to_uint64(agn_tostring(L, idx), &rc);
    if (rc)
      luaL_error(L, "Error: string is malformed or value is out-of-range.");
    createuint64(L, x);  /* 6.3.4 fix */
    lua_replace(L, idx);
  } else {  /* 6.3.5 */
    luaL_error(L, "Error: expected an " LUA_QS " userdata, non-negative integer or string.", "ints");
  }
  return (Ints *)lua_touserdata(L, idx);
}


/* Userdata generation *********************************************************************/

static void createbitwiseintfromdouble (lua_State *L, char what, double value, const char *procname) {
  Ints *a;
  luaL_checkstack(L, 2, "not enough stack space");  /* for numarray userdata and its registry aux table */
  a = (Ints *)lua_newuserdata(L, sizeof(Ints));
  a->datatype = what;
  switch (what) {
    case UINT64T: {
      a->data.ui = double2bitwiseuint64(value);
      agn_setutypestring(L, -1, "uint64");
      break;
    }
    case INT64T: {
      a->data.i = double2bitwiseint64(value);
      agn_setutypestring(L, -1, "int64");
      break;
    }
    default: {
      agn_poptop(L);
      luaL_error(L, "Error in " LUA_QS ": datatype %d does not exist.", procname, what);
    }
  }
  lua_setmetatabletoobject(L, -1, "ints", 0);
  lua_createtable(L, 0, 0);  /* set internal status table */
  lua_setfenv(L, -2);
}

void createuint64 (lua_State *L, uint64_t value) {
  Ints *a;
  luaL_checkstack(L, 2, "not enough stack space");  /* for numarray userdata and its registry aux table */
  a = (Ints *)lua_newuserdata(L, sizeof(Ints));
  a->datatype = UINT64T;
  a->data.ui = value;
  agn_setutypestring(L, -1, "uint64");
  lua_setmetatabletoobject(L, -1, "ints", 0);
  lua_createtable(L, 0, 0);  /* set internal status table */
  lua_setfenv(L, -2);
}

void createint64 (lua_State *L, int64_t value) {
  Ints *a;
  luaL_checkstack(L, 2, "not enough stack space");
  a = (Ints *)lua_newuserdata(L, sizeof(Ints));
  a->datatype = INT64T;
  a->data.i = value;
  agn_setutypestring(L, -1, "int64");
  lua_setmetatabletoobject(L, -1, "ints", 0);
  lua_createtable(L, 0, 0);  /* set internal status table */
  lua_setfenv(L, -2);
}


/* The library functions *******************************************************************/

static int ints_touint64 (lua_State *L) {
  if (isints(L, 1)) {
    Ints *a = (Ints *)lua_touserdata(L, 1);
    if (a->datatype == INT64T) {  /* cast to uint64_t */
      createuint64(L, (uint64_t)a->data.i);
    } else {  /* just return input */
      lua_settop(L, 1);
    }
  } else {
    createbitwiseintfromdouble(L, UINT64T, agn_checknumber(L, 1), "ints.touint64");
  }
  return 1;
}


static int ints_toint64 (lua_State *L) {
  if (isints(L, 1)) {
    Ints *a = (Ints *)lua_touserdata(L, 1);
    if (a->datatype == UINT64T) {  /* cast to int64_t */
      createint64(L, (int64_t)a->data.ui);
    } else {  /* just return input */
      lua_settop(L, 1);
    }
  } else {
    createbitwiseintfromdouble(L, INT64T, agn_checknumber(L, 1), "ints.toint64");
  }
  return 1;
}


static int ints_todouble (lua_State *L) {
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      lua_pushnumber(L, bitwiseuint64todouble(a->data.ui));
      break;
    }
    case INT64T: {
      lua_pushnumber(L, bitwiseint64todouble(a->data.i));
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS ": datatype %d is not supported.", "ints.todouble", a->datatype);
  }
  return 1;
}


static int ints_getstore (lua_State *L) {
  int nargs = lua_gettop(L);
  checkints(L, 1);
  if (nargs == 1) {
    lua_getfenv(L, 1);
  } else if (agn_isinteger(L, 2)) {
    lua_getfenvi(L, 1, agn_tointeger(L, 2));
  } else {
    lua_getfenv(L, 1);
    lua_replace(L, 1);
    lua_settop(L, 2);
    lua_rawget(L, 1);
  }
  return 1;
}


static int ints_tonumber (lua_State *L) {
  Ints *a = checkints(L, 1);
  luaL_checkstack(L, 2, "not enough stack space");
  switch (a->datatype) {
    case UINT64T: {
      uint64_t x = a->data.ui;
      lua_pushnumber(L, x);
      lua_pushboolean(L, x > DBL_MAX);
      break;
    }
    case INT64T: {
      int64_t x = a->data.i;
      lua_pushnumber(L, x);
      lua_pushboolean(L, x > DBL_MAX || x < DBL_MIN);
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS ": datatype %d is not supported.", "ints.tonumber", a->datatype);
  }
  return 2;
}


static int mt_eq (lua_State *L) {
  Ints *a = checkints(L, 1);
  Ints *b = checkints(L, 2);
  if (a->datatype != b->datatype) {
    lua_pushfalse(L);
  } else {
    switch (a->datatype) {
      case UINT64T:
        lua_pushboolean(L, a->data.ui == b->data.ui);
        break;
      case INT64T:
        lua_pushboolean(L, a->data.i == b->data.i);
        break;
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__eq", a->datatype);
    }
  }
  return 1;
}


static int mt_lt (lua_State *L) {
  Ints *a = checkints(L, 1);
  Ints *b = checkints(L, 2);
  if (a->datatype != b->datatype) {
    lua_pushfalse(L);
  } else {
    switch (a->datatype) {
      case UINT64T:
        lua_pushboolean(L, a->data.ui < b->data.ui);
        break;
      case INT64T:
        lua_pushboolean(L, a->data.i < b->data.i);
        break;
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__lt", a->datatype);
    }
  }
  return 1;
}


static int mt_le (lua_State *L) {
  Ints *a = checkints(L, 1);
  Ints *b = checkints(L, 2);
  if (a->datatype != b->datatype) {
    lua_pushfalse(L);
  } else {
    switch (a->datatype) {
      case UINT64T:
        lua_pushboolean(L, a->data.ui <= b->data.ui);
        break;
      case INT64T:
        lua_pushboolean(L, a->data.i <= b->data.i);
        break;
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__le", a->datatype);
    }
  }
  return 1;
}


static int mt_add (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  Ints *b = aux_checkint(L, 2);
  if (a->datatype != b->datatype) {
    luaL_error(L, "Error in " LUA_QS " metamethod: data is of different type.", "__add");
  } else {
    switch (a->datatype) {
      case UINT64T: {
        uint64_t sum;
#if defined(__GNUC__) && (__GNUC__ > 5 || (__GNUC__ == 5 && __GNUC_MINOR__ >= 0))
        if (__builtin_add_overflow(a->data.ui, b->data.ui, &sum)) {  /* 6.3.2 change */
#else
        uint64_t x, y;
        x = a->data.ui;
        y = b->data.ui;
        sum = x + y;
        if (x > UINT64_MAX - y) {
#endif
          lua_pushtrue(L);
          lua_setglobal(L, "numoverflow");
        }
        createuint64(L, sum);
        break;
      }
      case INT64T: {
        int64_t sum;
#if defined(__GNUC__) && (__GNUC__ > 5 || (__GNUC__ == 5 && __GNUC_MINOR__ >= 0))
        if (__builtin_add_overflow(a->data.i, b->data.i, &sum)) {  /* 6.3.2 change */
#else
        int64_t x, y;
        x = a->data.i;
        y = b->data.i;
        sum = x + y;
        if ((x > 0LL && y > 0LL && x > INT64_MAX - y) ||
            (x < 0LL && y < 0LL && x < INT64_MIN - y)) {
#endif
          lua_pushtrue(L);
          lua_setglobal(L, "numoverflow");
        }
        createint64(L, sum);
        break;
      }
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__add", a->datatype);
    }
  }
  return 1;
}


static int mt_sub (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  Ints *b = aux_checkint(L, 2);
  if (a->datatype != b->datatype) {
    luaL_error(L, "Error in " LUA_QS " metamethod: data is of different type.", "__sub");
  } else {
    switch (a->datatype) {
      case UINT64T: {
        uint64_t diff;
#if defined(__GNUC__) && (__GNUC__ > 5 || (__GNUC__ == 5 && __GNUC_MINOR__ >= 0))
        if (__builtin_sub_overflow(a->data.ui, b->data.ui, &diff)) {  /* 6.3.2 change */
#else
        uint64_t x, y;
        x = a->data.ui;
        y = b->data.ui;
        diff = x - y;
        if (x < y) {
#endif
          lua_pushtrue(L);
          lua_setglobal(L, "numoverflow");  /* `underflow`, actually */
        }
        createuint64(L, diff);
        break;
      }
      case INT64T: {
        int64_t diff;
#if defined(__GNUC__) && (__GNUC__ > 5 || (__GNUC__ == 5 && __GNUC_MINOR__ >= 0))
        if (__builtin_sub_overflow(a->data.i, b->data.i, &diff)) {  /* 6.3.2 change */
#else
        int64_t x, y;
        x = a->data.i;
        y = b->data.i;
        diff = x - y;
        if (y > 0LL && (x < INT64_MIN + y)) {
#endif
          lua_pushtrue(L);
          lua_setglobal(L, "numoverflow");  /* `underflow`, actually */
        }
        createint64(L, diff);
        break;
      }
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__sub", a->datatype);
    }
  }
  return 1;
}


static int mt_mul (lua_State *L) {
  Ints *a, *b;
  a = aux_checkint(L, 1);
  b = aux_checkint(L, 2);
  if (a->datatype != b->datatype) {
    luaL_error(L, "Error in " LUA_QS " metamethod: data is of different type.", "__mul");
  } else {
    switch (a->datatype) {
      case UINT64T: {
        uint64_t prod;
#if defined(__GNUC__) && (__GNUC__ > 5 || (__GNUC__ == 5 && __GNUC_MINOR__ >= 0))
        if (__builtin_mul_overflow(a->data.ui, b->data.ui, &prod)) {  /* 6.3.2 change */
#else
        uint64_t x, y;
        x = a->data.ui;
        y = b->data.ui;
        prod = x * y;
        if (x != 0ULL && y > UINT64_MAX/x) {
#endif
          luaL_checkstack(L, 1, "not enough stack space");
          lua_pushtrue(L);
          lua_setglobal(L, "numoverflow");  /* `underflow`, actually */
        }
        createuint64(L, prod);
        break;
      }
      case INT64T: {
        int64_t prod;
#if defined(__GNUC__) && (__GNUC__ > 5 || (__GNUC__ == 5 && __GNUC_MINOR__ >= 0))
        if (__builtin_mul_overflow(a->data.i, b->data.i, &prod)) {  /* 6.3.2 change */
#else
        int64_t x, y;
        int overflow;
        x = a->data.i;
        y = b->data.i;
        prod = x * y;
        overflow = 0;
        /* Trivial case: zero operand means no overflow (already safe for the portable check) */
        if (x == 0 || y == 0) {
          overflow = 0;
        }
        /* Special case: INT64_MIN * -1 */
        else if ((x == INT64_MIN && y == -1LL) || (x == -1LL && y == INT64_MIN)) {
          overflow = 1;
        }
        /* Check for Positive Overflow (x*y > INT64_MAX) - Signs are the SAME */
        else if ((x > 0LL && y > 0LL && x > INT64_MAX/y) ||
                 (x < 0LL && y < 0LL && x < INT64_MAX/y)) {  /* Note: division INT64_MAX / negative is < 0 */
          overflow = 1;
        }
        /* Check for Negative Underflow (x*y < INT64_MIN) - Signs are DIFFERENT */
        else if (x > 0LL && y < 0LL && x > INT64_MIN/y) {  /* Note: INT64_MIN / negative is > 0 */
          overflow = 1;
        }
        else if (x < 0LL && y > 0LL && x < INT64_MIN/y) {  /* Note: INT64_MIN / positive is < 0 */
          overflow = 1;
        }
        if (overflow) {
#endif
          lua_pushtrue(L);
          lua_setglobal(L, "numoverflow");  /* or `underflow` */
        }
        createint64(L, prod);
        break;
      }
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__mul", a->datatype);
    }
  }
  return 1;
}


static int mt_div (lua_State *L) {
  Ints *a, *b;
  a = aux_checkint(L, 1);
  b = aux_checkint(L, 2);
  if (a->datatype != b->datatype) {
    luaL_error(L, "Error in " LUA_QS " operator: data is of different type.", "/");
  } else {
    switch (a->datatype) {
      case UINT64T:
        if (b->data.ui == 0ULL)
          luaL_error(L, "Error in " LUA_QS " operator: division by zero.", "/");
        createuint64(L, a->data.ui / b->data.ui);
        break;
      case INT64T:
        if (b->data.i == 0LL || (b->data.i == -1LL && a->data.i == INT64_MIN))  /* 6.3.2 fix */
          luaL_error(L, "Error in " LUA_QS " operator: division by zero or invalid operation.", "/");
        createint64(L, a->data.i / b->data.i);
        break;
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__div", a->datatype);
    }
  }
  return 1;
}


static int mt_mod (lua_State *L) {
  Ints *a, *b;
  a = aux_checkint(L, 1);
  b = aux_checkint(L, 2);
  if (a->datatype != b->datatype) {
    luaL_error(L, "Error in " LUA_QS " operator: data is of different type.", "%");
  } else {
    switch (a->datatype) {
      case UINT64T:
        if (b->data.ui == 0ULL)
          luaL_error(L, "Error in " LUA_QS " operator: division by zero.", "%");
        createuint64(L, a->data.ui % b->data.ui);
        break;
      case INT64T:
        if (b->data.i == 0LL)
          luaL_error(L, "Error in " LUA_QS " operator: division by zero.", "%");
        createint64(L, a->data.i % b->data.i);
        break;
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__mod", a->datatype);
    }
  }
  return 1;
}


static int mt_bshl (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  if (agn_isinteger(L, 2)) {
    int shift = agn_tointeger(L, 2);
    if (shift <= 0)
      luaL_error(L, "Error in " LUA_QS " operator: shift is non-positive.", "<<");
    switch (a->datatype) {
      case UINT64T:
        createuint64(L, a->data.ui << (uint64_t)shift);
        break;
      case INT64T:
        createint64(L, a->data.i << (int64_t)shift);
        break;
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__bshl", a->datatype);
    }
  } else {
    Ints *b = checkints(L, 2);
    if (a->datatype != b->datatype) {
      luaL_error(L, "Error in " LUA_QS " operator: data is of different type.", "<<");
    } else {
      switch (a->datatype) {
        case UINT64T:
          if (b->data.ui == 0ULL)
            luaL_error(L, "Error in " LUA_QS " operator: shift is non-positive.", "<<");
          createuint64(L, a->data.ui << b->data.ui);
          break;
        case INT64T:
          if (b->data.i <= 0LL)
            luaL_error(L, "Error in " LUA_QS " operator: shift is non-positive.", "<<");
          createint64(L, a->data.i << b->data.i);
          break;
        default:
          luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__bshl", a->datatype);
      }
    }
  }
  return 1;
}


static int mt_bshr (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  if (agn_isinteger(L, 2)) {
    int shift = agn_tointeger(L, 2);
    if (shift <= 0)
      luaL_error(L, "Error in " LUA_QS " operator: shift is non-positive.", ">>");
    switch (a->datatype) {
      case UINT64T:
        createuint64(L, a->data.ui >> (uint64_t)shift);
        break;
      case INT64T:
        createint64(L, a->data.i >> (int64_t)shift);
        break;
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__bshr", a->datatype);
    }
  } else {
    Ints *b = checkints(L, 2);
    if (a->datatype != b->datatype) {
      luaL_error(L, "Error in " LUA_QS " operator: data is of different type.", ">>");
    } else {
      switch (a->datatype) {
        case UINT64T:
          if (b->data.ui == 0ULL)
            luaL_error(L, "Error in " LUA_QS " operator: shift is non-positive.", ">>");
          createuint64(L, a->data.ui >> b->data.ui);
          break;
        case INT64T:
          if (b->data.i <= 0LL)
            luaL_error(L, "Error in " LUA_QS " operator: shift is non-positive.", ">>");
          createint64(L, a->data.i >> b->data.i);
          break;
        default:
          luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__bshr", a->datatype);
      }
    }
  }
  return 1;
}


/* Left rotation, created by Gemini AI, put into the public domain. */
static inline uint64_t rotl (const uint64_t x, int k) {
  k &= LUA_NBITS64 - 1;  /* 6.2.1, recommended by Gemini AI to prevent undefined behaviour,
    forces shift amount to be in [0, 63] */
  return (x << k) | (x >> (LUA_NBITS64 - k));
}

/* Right rotation, created by Gemini AI, put into the public domain. */
/* Shift right by k bits, OR-ed with shift left by (64 - k) bits (the bits that wrapped around) */
static inline uint64_t rotr (const uint64_t x, int k) {
  k &= LUA_NBITS64 - 1;  /* 6.2.1, recommended by Gemini AI to prevent undefined behaviour,
    forces shift amount to be in [0, 63] */
  return (x >> k) | (x << (LUA_NBITS64 - k));
}


static int mt_brotl (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  if (agn_isinteger(L, 2)) {
    int shift = agn_tointeger(L, 2);
    if (shift <= 0)
      luaL_error(L, "Error in " LUA_QS " operator: shift is non-positive.", "<<<");
    switch (a->datatype) {
      case UINT64T: {
        createuint64(L, rotl(a->data.ui, shift));
        break;
      }
      case INT64T: {
        createint64(L, rotl(a->data.i, shift));
        break;
      }
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__brotl", a->datatype);
    }
  } else {
    Ints *b = checkints(L, 2);
    if (a->datatype != b->datatype) {
      luaL_error(L, "Error in " LUA_QS " operator: data is of different type.", "<<<");
    } else {
      switch (a->datatype) {
        case UINT64T:
          if (b->data.ui == 0ULL)
            luaL_error(L, "Error in " LUA_QS " operator: shift is non-positive.", "<<<");
          createuint64(L, rotl(a->data.ui, (int)b->data.ui));
          break;
        case INT64T:
          if (b->data.i <= 0LL)
            luaL_error(L, "Error in " LUA_QS " operator: shift is non-positive.", "<<<");
          createint64(L, rotl(a->data.i, (int)b->data.i));
          break;
        default:
          luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__brotl", a->datatype);
      }
    }
  }
  return 1;
}


static int mt_brotr (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  if (agn_isinteger(L, 2)) {
    int shift = agn_tointeger(L, 2);
    if (shift <= 0)
      luaL_error(L, "Error in " LUA_QS " operator: shift is non-positive.", ">>>");
    switch (a->datatype) {
      case UINT64T: {
        createuint64(L, rotr(a->data.ui, shift));
        break;
      }
      case INT64T: {
        createint64(L, rotr(a->data.i, shift));
        break;
      }
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__brotr", a->datatype);
    }
  } else {
    Ints *b = checkints(L, 2);
    if (a->datatype != b->datatype) {
      luaL_error(L, "Error in " LUA_QS " operator: data is of different type.", ">>>");
    } else {
      switch (a->datatype) {
        case UINT64T:
          if (b->data.ui == 0ULL)
            luaL_error(L, "Error in " LUA_QS " operator: shift is non-positive.", ">>>");
          createuint64(L, rotr(a->data.ui, (int)b->data.ui));
          break;
        case INT64T:
          if (b->data.i <= 0LL)
            luaL_error(L, "Error in " LUA_QS " operator: shift is non-positive.", ">>>");
          createint64(L, rotr(a->data.i, (int)b->data.i));
          break;
        default:
          luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__brotr", a->datatype);
      }
    }
  }
  return 1;
}


static int mt_band (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  if (agn_isinteger(L, 2)) {
    int b = agn_tointeger(L, 2);
    switch (a->datatype) {
      case UINT64T:
        createuint64(L, a->data.ui & (uint64_t)b);
        break;
      case INT64T:
        createint64(L, a->data.i & (int64_t)b);
        break;
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__band", a->datatype);
    }
  } else {
    Ints *b = checkints(L, 2);
    if (a->datatype != b->datatype) {
      luaL_error(L, "Error in " LUA_QS " operator: data is of different type.", "&&");
    } else {
      switch (a->datatype) {
        case UINT64T:
          createuint64(L, a->data.ui & b->data.ui);
          break;
        case INT64T:
          createint64(L, a->data.i & b->data.i);
          break;
        default:
          luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__band", a->datatype);
      }
    }
  }
  return 1;
}


static int mt_bor (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  if (agn_isinteger(L, 2)) {
    int b = agn_tointeger(L, 2);
    switch (a->datatype) {
      case UINT64T:
        createuint64(L, a->data.ui | (uint64_t)b);
        break;
      case INT64T:
        createint64(L, a->data.i | (int64_t)b);
        break;
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__bor", a->datatype);
    }
  } else {
    Ints *b = checkints(L, 2);
    if (a->datatype != b->datatype) {
      luaL_error(L, "Error in " LUA_QS " operator: data is of different type.", "||");
    } else {
      switch (a->datatype) {
        case UINT64T:
          createuint64(L, a->data.ui | b->data.ui);
          break;
        case INT64T:
          createint64(L, a->data.i | b->data.i);
          break;
        default:
          luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__bor", a->datatype);
      }
    }
  }
  return 1;
}


static int mt_bxor (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  if (agn_isinteger(L, 2)) {
    int b = agn_tointeger(L, 2);
    switch (a->datatype) {
      case UINT64T:
        createuint64(L, a->data.ui ^ (uint64_t)b);
        break;
      case INT64T:
        createint64(L, a->data.i ^ (int64_t)b);
        break;
      default:
        luaL_error(L, "Error in " LUA_QS " operator: datatype %d is not supported.", "__bxor", a->datatype);
    }
  } else {
    Ints *b = checkints(L, 2);
    if (a->datatype != b->datatype) {
      luaL_error(L, "Error in " LUA_QS " metamethod: data is of different type.", "^^");
    } else {
      switch (a->datatype) {
        case UINT64T:
          createuint64(L, a->data.ui ^ b->data.ui);
          break;
        case INT64T:
          createint64(L, a->data.i ^ b->data.i);
          break;
        default:
          luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__bxor", a->datatype);
      }
    }
  }
  return 1;
}


static int mt_bnot (lua_State *L) {
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T:
      createuint64(L, ~(a->data.ui));
      break;
    case INT64T:
      createint64(L, ~(a->data.i));
      break;
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__bnot", a->datatype);
  }
  return 1;
}


static int mt_abs (lua_State *L) {
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      createuint64(L, a->data.ui);
      break;
    }
    case INT64T: {
      createint64(L, abs64(a->data.i));  /* 6.2.2, on some systems there is no llabs. */
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__abs", a->datatype);
  }
  return 1;
}


static int mt_absdiff (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  Ints *b = aux_checkint(L, 2);
  if (a->datatype != b->datatype) {
    luaL_error(L, "Error in " LUA_QS " metamethod: data is of different type.", "__absdiff");
  } else {
    switch (a->datatype) {
      case UINT64T: {
        uint64_t diff;
        uint64_t x, y;
        x = a->data.ui;
        y = b->data.ui;
        diff = (x > y) ? x - y : y - x;
        createuint64(L, diff);
        break;
      }
      case INT64T: {
        int64_t diff;
        int64_t x, y;
        x = a->data.i;
        y = b->data.i;
        diff = abs64(x - y);
        createint64(L, diff);
        break;
      }
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__absdiff", a->datatype);
    }
  }
  return 1;
}


static int mt_sign (lua_State *L) {
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t x = a->data.ui;
      createuint64(L, x != 0ULL);
      break;
    }
    case INT64T: {
      int64_t x = a->data.i;
      createint64(L, (x > 0) - (x < 0));  /* -1, 0, or +1, 6.2.2 change */
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__sign", a->datatype);
  }
  return 1;
}


static int ints_log2 (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t x = a->data.ui;
      int r = tools_uintlog2_64(x);
      if (r == -1) {
        luaL_error(L, "Error in " LUA_QS ": argument is zero.", "ints.log2");
      } else {
        createuint64(L, r);
      }
      break;
    }
    case INT64T: {
      int64_t x = a->data.i;
      if (x <= 0LL) {
        luaL_error(L, "Error in " LUA_QS ": argument is non-positive.", "ints.log2");
      } else {
        uint64_t y = x;
        createint64(L, tools_uintlog2_64(y));
      }
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS ": datatype %d is not supported.", "ints.log2", a->datatype);
  }
  return 1;
}


static int ints_log10 (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t x = a->data.ui;
      int r = tools_uintlog10_64(x);
      if (r == -1) {
        luaL_error(L, "Error in " LUA_QS ": argument is zero.", "ints.log2");
      } else {
        createuint64(L, r);
      }
      break;
    }
    case INT64T: {
      int64_t x = a->data.i;
      if (x <= 0LL) {
        luaL_error(L, "Error in " LUA_QS ": argument is non-positive.", "ints.log10");
      } else {
        uint64_t y = x;
        createint64(L, tools_uintlog10_64(y));
      }
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS ": datatype %d is not supported.", "ints.log10", a->datatype);
  }
  return 1;
}


static int mt_sqrt (lua_State *L) {
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      createuint64(L, tools_isqrtu64(a->data.ui));
      break;
    }
    case INT64T: {
      int64_t x = a->data.i;
      if (x < 0LL) {
        luaL_error(L, "Error in " LUA_QS " operator: argument is non-genative.", "sqrt");
      } else {
        uint64_t y = x;
        createint64(L, (int64_t)tools_isqrtu64(y));
      }
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__sqrt", a->datatype);
  }
  return 1;
}


/* Created by Gemini AI, put to the public domain. 7.3.8 */
#if !(defined(__GNUC__))
static int __builtin_clzll(unsigned long long x) {
  int n = 0;
  if (x == 0) return 64;
  for (n = 0; (x & 0x8000000000000000ULL) == 0; n++, x <<= 1);
  return n;
}
#endif

static int64_t cbrt_i64 (int64_t v) {
  if (v == 0) return 0;
  if (v < 0) return -cbrt_i64(-v);
  /* Hardened initial guess for ARM/x86 */
  /* We ensure the bit count is divided by 3 BEFORE shifting */
  uint64_t x = (uint64_t)1 << ((64 - __builtin_clzll((uint64_t)v))/3 + 1);
  uint64_t y;
  while (1) {
    y = (2*x + (uint64_t)v/(x*x))/3;
    if (y >= x) return (int64_t)x;
    x = y;
  }
}

static int ints_cbrt (lua_State *L) {
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t p = (uint64_t)cbrt_i64(a->data.ui);
      createuint64(L, p);
      break;
    }
    case INT64T: {
      int64_t p = cbrt_i64(a->data.i);
      createint64(L, p);
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS ": datatype %d is not supported.", "ints.cbrt", a->datatype);
  }
  return 1;
}


static uint64_t power_u64 (uint64_t base, uint32_t expo) {
  uint32_t i;
  uint64_t res = 1;
  for (i=0; i < expo; i++) {
    /* check if res * base would exceed 64 bits */
    if (res > 0 && base > (0xFFFFFFFFFFFFFFFFULL/res)) {
      return 0xFFFFFFFFFFFFFFFFULL;  /* return MAX if it would overflow */
    }
    res *= base;
  }
  return res;
}

static int64_t nth_root_i64 (int64_t v, int n, int *rc) {
  uint64_t x, y, p;
  *rc = 0;
  if (n <= 0) { *rc = -1; return 0; }  /* undefined for nonposints */
  if (n == 1) return v;
  if (v == 0) return 0;
  if (v < 0) {
    if (n % 2 == 0) { *rc = -1; return 0; }  /* no real root for even n */
    return -nth_root_i64(-v, n, rc);
  }
  /* 1. Initial Guess: log2(v)/n gives a very close starting bit */
  x = 1ULL << ((64 - __builtin_clzll((uint64_t)v))/n + 1);
  /* 2. Newton-Raphson Iteration */
  while (1) {
    /* We need x^(n-1) */
    p = power_u64(x, n - 1);
    if (p == 0xFFFFFFFFFFFFFFFFULL) {
      *rc = -2;  /* overflow */
      return 0LL;
    }
    /* Apply the general Newton formula */
    y = ((n - 1)*x + (uint64_t)v/p)/n;
    if (y >= x) return (int64_t)x;
    x = y;
  }
}

static uint64_t nth_root_ui64 (uint64_t v, int n, int *rc) {
  uint64_t x, y, p;
  *rc = 0;
  if (n <= 0) { *rc = -1; return 0; }  /* undefined for nonposints */
  if (n == 1) return v;
  if (v == 0) return 0;
  /* 1. Initial Guess: log2(v)/n gives a very close starting bit */
  x = 1ULL << ((64 - __builtin_clzll(v))/n + 1);
  /* 2. Newton-Raphson Iteration */
  while (1) {
    /* We need x^(n-1) */
    p = power_u64(x, n - 1);
    if (p == 0xFFFFFFFFFFFFFFFFULL) {
      *rc = -2;  /* overflow */
      return 0ULL;
    }
    /* Apply the general Newton formula */
    y = ((n - 1)*x + v/p)/n;
    if (y >= x) return x;
    x = y;
  }
}

static int ints_root (lua_State *L) {
  Ints *a = checkints(L, 1);
  int rc, n = agn_checkposint(L, 2);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t p = nth_root_ui64(a->data.ui, n, &rc);
      if (rc == -2)
        luaL_error(L, "Error in " LUA_QS ": calculation has overflowed.", "ints.root");
      createuint64(L, p);
      break;
    }
    case INT64T: {
      int64_t p = nth_root_i64(a->data.i, n, &rc);
      if (rc == -2)
        luaL_error(L, "Error in " LUA_QS ": calculation has overflowed.", "ints.root");
      else if (rc == -1)
        luaL_error(L, "Error in " LUA_QS ": input is negative.", "ints.root");
      createint64(L, p);
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS ": datatype %d is not supported.", "ints.root", a->datatype);
  }
  return 1;
}


/**
 * Raises base to the power of exponent (base^exponent) for uint64_t.
 *
 * @param base The uint64_t base.
 * @param exponent The non-negative integer exponent.
 * @param result Pointer to store the result.
 * @return True if the calculation succeeded without overflow, false otherwise.
 *
 * Created by Gemini AI, public domain.
 */
static bool power_uint64 (uint64_t base, int exponent, uint64_t *result) {
  *result = 1;  /* Start with result = base^0 = 1 */
  if (exponent < 0) return false;  /* Technically undefined for integers, treat as an error */
  if (exponent == 0) return true;  /* base^0 = 1 */
  if (base == 0) {
    *result = 0;
    return true;  /* 0^E = 0 for E > 0 */
  }
  /* --- Core Binary Exponentiation Loop --- */
  uint64_t current_base = base;
  /* Iterate through the bits of the exponent */
  while (exponent > 0) {
    /* Check if the current bit of the exponent is 1 (exponent is odd) */
    if (exponent & 1) {
      /* Check for multiplication overflow: *result * current_base */
      if (current_base > UINT64_MAX / *result) return false;  /* Overflow occurred */
      *result *= current_base;
    }
    /* Prepare for the next bit of the exponent (exponent is divided by 2) */
    exponent >>= 1;
    /* If exponent is now 0, stop to avoid squaring unnecessarily */
    if (exponent == 0) break;
    /* Check for squaring overflow: current_base * current_base */
    if (current_base > UINT64_MAX / current_base) return false;  /* Overflow occurred during squaring */
    current_base *= current_base;
  }
  return true;  /* Success */
}

/**
 * Raises base to the power of exponent (base^exponent) for int64_t.
 *
 * @param base The int64_t base.
 * @param exponent The integer exponent.
 * @param result Pointer to store the result.
 * @return True if the calculation succeeded without signed overflow, false otherwise.
 *
 * Created by Gemini AI, public domain.
 */
static bool power_int64 (int64_t base, int exponent, int64_t *result) {
  /* 1. Handle special cases based on exponent */
  if (exponent < 0) {
    /* Integer power function typically handles only non-negative exponents.
       For negative exponents, the result is fractional (e.g., 2^-1 = 0.5),
       which cannot be represented as an int64_t (except for 0). */
    if (exponent == 0) *result = 1;  /* Base case for non-zero base */
    else *result = 0;  /* Truncated result for 1/base^|exponent| */
    return true;  /* We return 0, which is technically the floor of the result */
  }
  if (exponent == 0) {
    *result = 1;  /* base^0 = 1 */
    return true;
  }
  if (base == 0) {
    *result = 0;
    return true;  /* 0^E = 0 for E > 0 */
  }
  if (base == 1) {
    *result = 1;
    return true;
  }
  /* 2. Determine the sign of the final result
     The sign depends on the base and the exponent's parity. */
  bool final_sign_is_negative = (base < 0) && (exponent % 2 != 0);
  /* 3. Use absolute value for the main calculation
     This simplifies overflow checks, as we only check against INT64_MAX. */
  uint64_t abs_base = abs64(base);  /* 6.2.1/2, on some systems there is no llabs. */
  uint64_t abs_result_u = 1;
  /* --- Core Binary Exponentiation Loop on unsigned values --- */
  uint64_t current_base = abs_base;
  while (exponent > 0) {
    if (exponent & 1) {
      /* Check for multiplication overflow: abs_result_u * current_base
         If the required result exceeds the positive limit (INT64_MAX), it overflows. */
      if (current_base > (uint64_t)INT64_MAX / abs_result_u) {
        return false;  /* Positive overflow */
      }
      abs_result_u *= current_base;
    }
    exponent >>= 1;
    if (exponent == 0) break;
    /* Check for squaring overflow: current_base * current_base */
    if (current_base > (uint64_t)INT64_MAX / current_base) {
      return false;  /* Positive overflow during squaring */
    }
    current_base *= current_base;
  }
  /* 4. Apply the final sign */
  if (final_sign_is_negative) {
    /* Check for the negative overflow case: INT64_MIN.
       The maximum positive result (INT64_MAX) is 1 smaller than the
       magnitude of the minimum negative result (INT64_MIN).
       Since abs_result_u holds the magnitude, if abs_result_u > INT64_MAX,
       the result is too large to fit in the negative range, *unless*
       abs_result_u is exactly 9223372036854775808 (INT64_MAX + 1), which
       corresponds to INT64_MIN. */
    if (abs_result_u == (uint64_t)INT64_MIN) {
      *result = INT64_MIN;
    } else if (abs_result_u > (uint64_t)INT64_MAX) {
      return false;  /* Overflow (magnitude too large) */
    } else {
      *result = -(int64_t)abs_result_u;
    }
  } else {
    /* Positive result */
    if (abs_result_u > (uint64_t)INT64_MAX) {
      return false;  /* Positive overflow */
    }
    *result = (int64_t)abs_result_u;
  }
  return true;
}

static int mt_pow (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  if (agn_isinteger(L, 2)) {
    int e = agn_tointeger(L, 2);
    switch (a->datatype) {
      case UINT64T: {
        uint64_t p;
        bool rc = power_uint64(a->data.ui, e, &p);
        if (rc) {
          createuint64(L, p);
        } else {
          luaL_error(L, "Error in " LUA_QS " metamethod: cannot compute power.", "__pow");
        }
        break;
      }
      case INT64T: {
        int64_t p;
        bool rc = power_int64(a->data.i, e, &p);
        if (rc) {
          createint64(L, p);
        } else {
          luaL_error(L, "Error in " LUA_QS " metamethod: cannot compute power.", "__pow");
        }
        break;
      }
      default:
        luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__pow", a->datatype);
    }
  } else {
    Ints *b = aux_checkint(L, 2);
    if (a->datatype != b->datatype) {
      luaL_error(L, "Error in " LUA_QS " metamethod: data is of different type.", "__pow");
    } else {
      switch (a->datatype) {
        case UINT64T: {
          uint64_t p;
          bool rc = power_uint64(a->data.ui, b->data.ui, &p);
          if (rc) {
            createuint64(L, p);
          } else {
            luaL_error(L, "Error in " LUA_QS " metamethod: cannot compute power.", "__pow");
          }
          break;
        }
        case INT64T: {
          int64_t p;
          bool rc = power_int64(a->data.i, b->data.i, &p);
          if (rc) {
            createint64(L, p);
          } else {
            luaL_error(L, "Error in " LUA_QS " metamethod: cannot compute power.", "__pow");
          }
          break;
        }
        default:
          luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__pow", a->datatype);
      }
    }
  }
  return 1;
}


static int mt_square (lua_State *L) {
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t p = a->data.ui * a->data.ui;
      createuint64(L, p);
      break;
    }
    case INT64T: {
      int64_t p = a->data.i * a->data.i;
      createint64(L, p);
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__square", a->datatype);
  }
  return 1;
}


static int mt_cube (lua_State *L) {
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t p = a->data.ui * a->data.ui;
      createuint64(L, p*a->data.ui);
      break;
    }
    case INT64T: {
      int64_t p = a->data.i * a->data.i;
      createint64(L, p*a->data.i);
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__cube", a->datatype);
  }
  return 1;
}


static int mt_antilog2 (lua_State *L) {  /* 6.4.0 */
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t p;
      bool rc = power_uint64(2ULL, a->data.ui, &p);
      if (rc) {
        createuint64(L, p);
      } else {
        luaL_error(L, "Error in " LUA_QS " metamethod: cannot compute power.", "__antilog2");
      }
      break;

    }
    case INT64T: {
      int64_t p;
      bool rc = power_int64(2LL, a->data.i, &p);
      if (rc) {
        createint64(L, p);
      } else {
        luaL_error(L, "Error in " LUA_QS " metamethod: cannot compute power.", "__antilog2");
      }
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__antilog2", a->datatype);
  }
  return 1;
}


static int mt_antilog10 (lua_State *L) {  /* 6.4.0 */
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t p;
      bool rc = power_uint64(10ULL, a->data.ui, &p);
      if (rc) {
        createuint64(L, p);
      } else {
        luaL_error(L, "Error in " LUA_QS " metamethod: cannot compute power.", "__antilog10");
      }
      break;

    }
    case INT64T: {
      int64_t p;
      bool rc = power_int64(10LL, a->data.i, &p);
      if (rc) {
        createint64(L, p);
      } else {
        luaL_error(L, "Error in " LUA_QS " metamethod: cannot compute power.", "__antilog10");
      }
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__antilog10", a->datatype);
  }
  return 1;
}


static int mt_unm (lua_State *L) {
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T:
      luaL_error(L, "Error in " LUA_QS " metamethod: unsigned integer cannot be negated.", "__unm");
      break;
    case INT64T:
      createint64(L, -a->data.i);
      break;
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__unm", a->datatype);
  }
  return 1;
}


static int mt_even (lua_State *L) {
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      lua_pushboolean(L, (a->data.ui & 1) == 0);
      break;
    }
    case INT64T: {
      lua_pushboolean(L, (a->data.i & 1) == 0);
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__even", a->datatype);
  }
  return 1;
}


static int mt_odd (lua_State *L) {
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      lua_pushboolean(L, (a->data.ui & 1) != 0);
      break;
    }
    case INT64T: {
      lua_pushboolean(L, (a->data.i & 1) != 0);
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__odd", a->datatype);
  }
  return 1;
}


static int mt_zero (lua_State *L) {  /* 6.4.0 */
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      lua_pushboolean(L, a->data.ui == 0ULL);
      break;
    }
    case INT64T: {
      lua_pushboolean(L, a->data.i == 0LL);
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__zero", a->datatype);
  }
  return 1;
}


static int mt_nonzero (lua_State *L) {  /* 6.4.0 */
  Ints *a = checkints(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      lua_pushboolean(L, a->data.ui != 0ULL);
      break;
    }
    case INT64T: {
      lua_pushboolean(L, a->data.i != 0LL);
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__nonzero", a->datatype);
  }
  return 1;
}


static int mt_tostring (lua_State *L) {
  int rc, i;
  char str[22];  /* a buffer of 22 is generally sufficient (19 digits + '-' + '\0') */
  Ints *a = checkints(L, 1);
  for (i=0; i < 22; i++) str[i] = 0;
  rc = 0;
  switch (a->datatype) {
    case UINT64T:
      safe_uint64_to_string(a->data.ui, str, sizeof(str), &rc);
      break;
    case INT64T:
      safe_int64_to_string(a->data.i, str, sizeof(str), &rc);
      break;
    default:
      luaL_error(L, "Error in " LUA_QS " metamethod: datatype %d is not supported.", "__tostring", a->datatype);
  }
  if (rc == 0) {
    luaL_checkstack(L, 2, "not enough stack space");
    if (!agn_getutype(L, 1))
      luaL_error(L, "Error in " LUA_QS " metamethod: malformed " LUA_QS " userdata.", "__tostring", "ints");
    lua_pushfstring(L, "%s(%s)", lua_tostring(L, -1), str);
    lua_remove(L, -2);
  } else if (rc == -1) {
    luaL_error(L, "Error in " LUA_QS " metamethod: encoding error or other system issue.", "__tostring");
  } else {
    luaL_error(L, "Error in " LUA_QS " metamethod: buffer is too small.", "__tostring");
  }
  return 1;
}


static int ints_tostring (lua_State *L) {
  int rc, i;
  char str[22];  /* a buffer of 22 is generally sufficient (19 digits + '-' + '\0') */
  Ints *a = checkints(L, 1);
  for (i=0; i < 22; i++) str[i] = 0;
  rc = 0;
  switch (a->datatype) {
    case UINT64T:
      safe_uint64_to_string(a->data.ui, str, sizeof(str), &rc);
      break;
    case INT64T:
      safe_int64_to_string(a->data.i, str, sizeof(str), &rc);
      break;
    default:
      luaL_error(L, "Error in " LUA_QS ": datatype %d is not supported.", "ints.tostring", a->datatype);
  }
  if (rc == 0) {
    lua_pushstring(L, str);
  } else if (rc == -1) {
    luaL_error(L, "Error in " LUA_QS ": encoding error or other system issue.", "ints.tostring");
  } else {
    luaL_error(L, "Error in " LUA_QS " metamethod: buffer is too small.", "ints.tostring");
  }
  return 1;
}


static int ints_uint64 (lua_State *L) {
  if (agn_isstring(L, 1)) {
    int rc;
    uint64_t x = safe_str_to_uint64(agn_tostring(L, 1), &rc);
    switch (rc) {
      case 0:  /* with negative input we will get the negation */
        createuint64(L, x);
        break;
      case 1:
        luaL_error(L, "Error in " LUA_QS ": input value is out-of-range.", "ints.uint64");
        break;
      case 2:
        luaL_error(L, "Error in " LUA_QS ": input string has no digits.", "ints.uint64");
        break;
      case 3:
        luaL_error(L, "Error in " LUA_QS ": input string has invalid character(s).", "ints.uint64");
        break;
      case 4:
        luaL_error(L, "Error in " LUA_QS ": input string is invalid.", "ints.uint64");
        break;
      default:
        luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.uint64");
    }
  } else if (agn_isnumber(L, 1) && lua_isnoneornil(L, 2)) {  /* with negative input we will get the negation */
    createuint64(L, (uint64_t)(agn_tonumber(L, 1) + 0.0));
  } else if (agn_isnumber(L, 1) && lua_istrue(L, 2)) {  /* 7.1.9 extension: unfold double to uint64_t */
    uint64_t u;
    lua_Number x = agn_tonumber(L, 1) + 0.0;  /* normalize -0.0 */
    memcpy(&u, &x, sizeof(u));
    createuint64(L, u);
  } else if (agn_isnonnegint(L, 1) && agn_isnonnegint(L, 2)) {  /* 7.1.9 extension: 2 uint32_t's to uint64_t */
    Ints *a;
    createuint64(L, 0);
    a = (Ints *)lua_touserdata(L, -1);
    sethighu64(&a->data.ui, lua_touint32_t(L, 1));
    setlowu64(&a->data.ui, lua_touint32_t(L, 2));
  } else {
    luaL_error(L, "Error in " LUA_QS ": need a number or string as input.", "ints.uint64");
  }
  return 1;
}


static int ints_int64 (lua_State *L) {
  if (agn_isstring(L, 1)) {
    int rc;
    int64_t x = safe_str_to_int64(agn_tostring(L, 1), &rc);
    switch (rc) {
      case 0:
        createint64(L, x);
        break;
      case 1:
        luaL_error(L, "Error in " LUA_QS ": input value is out-of-range.", "ints.int64");
        break;
      case 2:
        luaL_error(L, "Error in " LUA_QS ": input string has no digits.", "ints.int64");
        break;
      case 3:
        luaL_error(L, "Error in " LUA_QS ": input string has invalid character(s).", "ints.int64");
        break;
      case 4:
        luaL_error(L, "Error in " LUA_QS ": input string is invalid.", "ints.int64");
        break;
      default:
        luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.int64");
    }
  } else if (agn_isnumber(L, 1)) {
    createint64(L, agn_tonumber(L, 1) + 0.0);
  } else if (agn_isinteger(L, 1) && agn_isinteger(L, 2)) {  /* 7.1.9 extension */
    Ints *a;
    createint64(L, 0);
    a = (Ints *)lua_touserdata(L, -1);
    sethigh64(&a->data.i, lua_toint32_t(L, 1));
    setlow64(&a->data.i, lua_toint32_t(L, 2));
  } else {
    luaL_error(L, "Error in " LUA_QS ": need a number or string as input.", "ints.int64");
  }
  return 1;
}


static int mt_index (lua_State *L) {  /* 6.1.4 */
  if (luaL_isudata(L, 1, AGENA_INTSLIBNAME)) {
    if (lua_gettop(L) == 2 && agn_isstring(L, 2)) {
      /* sizeof(<string constant>) == strlen(<string constant>) + 1 */
      return agn_initmethodcall(L, AGENA_INTSLIBNAME, sizeof(AGENA_INTSLIBNAME) - 1);
    }
  }
  luaL_error(L, "Error in " LUA_QS " package: illegal call.", AGENA_INTSLIBNAME);
  return 0;
}


static int mt_gc (lua_State *L) {
  lua_lock(L);
  checkints(L, 1);
  lua_pushnil(L);  /* destroy environment table */
  lua_setfenv(L, 1);
  lua_setmetatabletoobject(L, 1, NULL, 1);
  lua_unlock(L);
  return 0;
}


/* RNG, as proposed by Gemini AI, put into the public domain.

   Features:
   - Simplicity and Speed: The core next_u64 function is very short, relying only on basic bitwise (XOR, shift, rotate)
     and addition operations, making it extremely fast.

   - Quality: It passes most standard statistical tests (like TestU01's BigCrush) well, though it is not cryptographically
     secure.

   - State: The internal state is crucial. It must be a non-zero value. The provided seed_from_single_u64 function handles
     generating a robust two-word seed from a single input like time(NULL).

   - Period: The period is huge, meaning it can generate a vast number of unique random numbers before repeating the sequence. */

/* State variables (must be seeded to a non-zero state) */
static uint64_t s[2] = { 0 };

/* Function to generate the next 64-bit random number */
static uint64_t next_u64 (void) {
  const uint64_t s0 = s[0];
  uint64_t s1 = s[1];
  /* The result is the sum of the two state words */
  const uint64_t result = s0 + s1;
  /* Update the state using XOR, rotation, and shift operations */
  s1 ^= s0;
  s[0] = rotl(s0, 24) ^ s1 ^ (s1 << 16);  /* a=24, b=16 */
  s[1] = rotl(s1, 37);                    /* c=37 */
  return result;
}

/* --- Seeding function (Must be called once before use) --- */
/* void seed_xoroshiro(uint64_t seed1, uint64_t seed2) {
    s[0] = seed1 == 0 ? 1 : seed1; // Ensure non-zero
    s[1] = seed2 == 0 ? 1 : seed2; // Ensure non-zero
} */

/* Example: Using a simpler SplitMix64 to generate the two seeds from one input
   (SplitMix64 is a generator often used specifically for seeding other generators) */
static void seed_from_single_u64 (uint64_t seed) {
  uint64_t z = seed + 0x9e3779b97f4a7c15ULL;
  z = (z ^ (z >> 30)) * 0xbf5847614e5fadbULL;
  z = (z ^ (z >> 27)) * 0x94d049b4f1a62eb1ULL;
  s[0] = z ^ (z >> 31);
  z = z + 0x9e3779b97f4a7c15ULL;
  z = (z ^ (z >> 30)) * 0xbf5847614e5fadbULL;
  z = (z ^ (z >> 27)) * 0x94d049b4f1a62eb1ULL;
  s[1] = z ^ (z >> 31);
  /* Fallback if both end up zero (highly unlikely) */
  if (s[0] == 0 && s[1] == 0) { s[0] = 1; }
}

static int ints_random (lua_State *L) {
  uint64_t seed;
  int nargs = lua_gettop(L);
  if (nargs == 0) {
    if (s[0] == 0 && s[1] == 0) {
      seed = wallclock_ns();
      seed_from_single_u64(seed);
    }
  } else {
    uint64_t seed;
    Ints *a = checkints(L, 1);
    seed = (a->datatype == UINT64T) ? a->data.ui : (uint64_t)a->data.i;
    seed_from_single_u64(seed);
  }
  createuint64(L, next_u64());
  return 1;
}


/* Counts the number of one bits in the unsigned 64-bit integer x and returns it as an integer. */
static int ints_onebits (lua_State *L) {  /* 6.2.1 */
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T: {
#ifdef __GNUC__
      lua_pushinteger(L, __builtin_popcountll(a->data.ui));
#else
      lua_pushinteger(L, tools_onebitsu64(a->data.ui));
#endif
      break;
    }
    case INT64T: {
#ifdef __GNUC__
      lua_pushinteger(L, __builtin_popcountll((uint64_t)a->data.i));
#else
      lua_pushinteger(L, tools_onebitsu64((uint64_t)a->data.i));
#endif
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.onebits");
  }
  return 1;
}


/* Returns the number of leading zeros (clz) in the unsigned 64-bit integer n, and the modified value of x after this operation,
   where all bits starting with the first non-zero bit in n are set to 1. 6.1.2 */
static int ints_leadzeros (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  luaL_checkstack(L, 2, "not enough stack space");
  switch (a->datatype) {
    case UINT64T: {
      uint64_t x, n;
      n = tools_clzu64(a->data.ui, &x);
      lua_pushinteger(L, n);
      createuint64(L, x);
      break;
    }
    case INT64T: {
      uint64_t x, n;
      n = tools_clzu64((uint64_t)a->data.i, &x);
      lua_pushinteger(L, n);
      createint64(L, (int64_t)x);
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.leadzeros");
  }
  return 2;
}


#define ALLONES64    (~(((~(uint64_t)0) << (LUA_NBITS64 - 1)) << 1))

/* macro to trim extra bits */
#define trim64(x)    ((x) & ALLONES64)

/* builds a number with 'n' ones (1 <= n <= LUA_NBITS) */
#define mask64(n)    (~((ALLONES64 << 1) << ((n) - 1)))

/* Counts the number of trailing zeros (ctz) in the unsigned 64-bit integer x, and also
   returns the modified value of x after this operation as a second result, where all bits
   starting with the least significant bit in x are set to 1. 6.2.1 */
static int ints_trailzeros (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  luaL_checkstack(L, 2, "not enough stack space");
  switch (a->datatype) {
    case UINT64T: {
      uint64_t x, r;
      r = tools_ctzu64(a->data.ui, &x);
      lua_pushinteger(L, r);
      createuint64(L, x | (r ? mask64(r) : 0));
      break;
    }
    case INT64T: {
      uint64_t x, r;
      r = tools_ctzu64((uint64_t)a->data.i, &x);
      lua_pushinteger(L, r);
      createint64(L, (uint64_t)x | (r ? mask64(r) : 0));
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.trailzeros");
  }
  return 2;
}


/* Returns the position of the most significant bit (msb) in the unsigned 64-bit integer x,
   i.e. the largest index of a 1-bit, counting from bit index 1. If x = 0, returns 0. */
static int ints_mostsigbit (lua_State *L) {  /* 6.2.1 */
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T:
      lua_pushinteger(L, tools_msb64(a->data.ui));
      break;
    case INT64T:
      lua_pushinteger(L, tools_msb64((uint64_t)a->data.i));
      break;
    default:
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.mostsigbit");
  }
  return 1;
}


static int ints_leastsigbit (lua_State *L) {  /* 6.2.1 */
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T:
      lua_pushinteger(L, tools_lsb64(a->data.ui));
      break;
    case INT64T:
      lua_pushinteger(L, tools_lsb64((uint64_t)a->data.i));
      break;
    default:
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.leastsigbit");
  }
  return 1;
}


static int ints_tobytes (lua_State *L) {  /* 6.2.1 */
  int s, i;
  unsigned char *src;
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t y = a->data.ui;
      s = sizeof(uint64_t);
      agn_createseq(L, s);
      #if BYTE_ORDER == BIG_ENDIAN
      tools_swapuint64_t(&y);
      #endif
      src = (unsigned char *)&y;
      for (i=0; i < s; i++) {
        agn_seqsetinumber(L, -1, i + 1, src[i]);
      }
      break;
    }
    case INT64T: {
      int64_t y = a->data.i;
      s = sizeof(int64_t);
      agn_createseq(L, s);
      #if BYTE_ORDER == BIG_ENDIAN
      tools_swapint64_t(&y);
      #endif
      src = (unsigned char *)&y;
      for (i=0; i < s; i++) {
        agn_seqsetinumber(L, -1, i + 1, src[i]);
      }
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.leastsigbit");
  }
  return 1;
}


/* In the signed or unsigned integer n retrieves the bit currently set at position pos and returns the Agena
   numbers 0 or 1. pos is an integer in the range [1, 64]. 6.2.2 */
static int ints_getbit (lua_State *L) {
  int pos;
  Ints *a = aux_checkint(L, 1);
  pos = agn_checkposint(L, 2);
  if (pos > 64)
    luaL_error(L, "Error in " LUA_QS ": position is out-of-range.", "ints.getbit");
  switch (a->datatype) {
    case UINT64T: {
      uint64_t x = a->data.ui;
      lua_pushinteger(L, tools_getuint64bit(x, pos));  /* works with both Big and Little Endian */
      break;
    }
    case INT64T: {
      int64_t x = a->data.i;
      lua_pushinteger(L, tools_getint64bit(x, pos));  /* works with both Big and Little Endian */
      break;
    }
    default:
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.getbit");
  }
  return 1;
}


/* Retrieves all the bits in the signed or unsigned 64-bit integer n and returns them in a sequence. 6.2.2 */
static int ints_getbits (lua_State *L) {
  int i;
  Ints *a = aux_checkint(L, 1);
  agn_createseq(L, LUA_NBITS64);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t x = a->data.ui;
      for (i=1; i <= LUA_NBITS64; i++) {
        agn_seqsetinumber(L, -1, i, tools_getuint64bit(x, i));
      }
      break;
    }
    case INT64T: {
      int64_t x = a->data.i;
      for (i=1; i <= LUA_NBITS64; i++) {
        agn_seqsetinumber(L, -1, i, tools_getint64bit(x, i));
      }
      break;
    }
    default: {
      agn_poptop(L);
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.getbits");
    }
  }
  return 1;
}


/* In the signed or unsigned integer n, sets zero-bit or a one-bit bit in-place at position pos.
   bit can be 0 or 1. pos is an integer in the range [1, 64]. The function returns nothing. */
static int ints_setbit (lua_State *L) {  /* 6.2.2 */
  int pos, bit;
  Ints *a = aux_checkint(L, 1);
  pos = agn_checkposint(L, 2);
  bit = agn_checknonnegint(L, 3) & 1;
  if (pos > 64)
    luaL_error(L, "Error in " LUA_QS ": position is out-of-range.", "ints.setbit");
  switch (a->datatype) {
    case UINT64T:
      tools_setuint64bit(&a->data.ui, pos, bit);  /* works with both Big and Little Endian */
      break;
    case INT64T:
      tools_setint64bit(&a->data.i, pos, bit);  /* works with both Big and Little Endian */
      break;
    default:
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.setbit");
  }
  return 0;
}


/* Taken from "The Aggregate Magic Algorithms", https://aggregate.org/MAGIC/#Average%20of%20Integers */
/* `ints.mean` computes (x + y)/2 = (x & y) + ((x ^ y) >> 1) without overflowing, 6.2.2 */
static int ints_mean (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  Ints *b = aux_checkint(L, 2);
  if (a->datatype != b->datatype) {
    luaL_error(L, "Error in " LUA_QS ": data is of different type.", "ints.mean");
  } else {
    switch (a->datatype) {
      case UINT64T: {
        uint64_t x, y;
        x = a->data.ui;
        y = b->data.ui;
        createuint64(L, (x & y) + ((x ^ y) >> 1ULL));
        break;
      }
      case INT64T: {
        int64_t x, y;
        x = a->data.i;
        y = b->data.i;
        createint64(L, (x & y) + ((x ^ y) >> 1LL));
        break;
      }
      default:
        luaL_error(L, "Error in " LUA_QS ": datatype %d is not supported.", "ints.mean", a->datatype);
    }
  }
  return 1;
}


/* Taken from: https://graphics.stanford.edu/~seander/bithacks.html, 6.2.2
   "Compute the minimum (min) or maximum (max) of two integers without branching" */
static int ints_min (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  Ints *b = aux_checkint(L, 2);
  if (a->datatype != b->datatype) {
    luaL_error(L, "Error in " LUA_QS ": data is of different type.", "ints.min");
  } else {
    switch (a->datatype) {
      case UINT64T: {
        uint64_t x, y, m;
        x = a->data.ui;
        y = b->data.ui;
        m = y ^ ((x ^ y) & -(x < y));
        lua_pushvalue(L, 1 + (m == y));
        break;
      }
      case INT64T: {
        int64_t x, y, m;
        x = a->data.i;
        y = b->data.i;
        m = y ^ ((x ^ y) & -(x < y));
        lua_pushvalue(L, 1 + (m == y));
        break;
      }
      default:
        luaL_error(L, "Error in " LUA_QS ": datatype %d is not supported.", "ints.min", a->datatype);
    }
  }
  return 1;
}


/* Taken from: https://graphics.stanford.edu/~seander/bithacks.html, 6.2.2
   "Compute the minimum (min) or maximum (max) of two integers without branching" */
static int ints_max (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  Ints *b = aux_checkint(L, 2);
  if (a->datatype != b->datatype) {
    luaL_error(L, "Error in " LUA_QS ": data is of different type.", "ints.max");
  } else {
    switch (a->datatype) {
      case UINT64T: {
        uint64_t x, y, m;
        x = a->data.ui;
        y = b->data.ui;
        m = x ^ ((x ^ y) & -(x < y));
        lua_pushvalue(L, 1 + (m == y));
        break;
      }
      case INT64T: {
        int64_t x, y, m;
        x = a->data.i;
        y = b->data.i;
        m = x ^ ((x ^ y) & -(x < y));
        lua_pushvalue(L, 1 + (m == y));
        break;
      }
      default:
        luaL_error(L, "Error in " LUA_QS ": datatype %d is not supported.", "ints.max", a->datatype);
    }
  }
  return 1;
}


static int ints_minmax (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  Ints *b = aux_checkint(L, 2);
  if (a->datatype != b->datatype) {
    luaL_error(L, "Error in " LUA_QS ": data is of different type.", "ints.minmax");
  } else {
    luaL_checkstack(L, 2, "not enough stack space");
    switch (a->datatype) {
      case UINT64T: {
        uint64_t x, y, t, max, min;
        x = a->data.ui;
        y = b->data.ui;
        t = ((x ^ y) & -(x < y));
        min = y ^ t;
        lua_pushvalue(L, 1 + (min == y));
        max = x ^ t;
        lua_pushvalue(L, 1 + (max == y));
        break;
      }
      case INT64T: {
        int64_t x, y, t, max, min;
        x = a->data.i;
        y = b->data.i;
        t = ((x ^ y) & -(x < y));
        min = y ^ t;
        lua_pushvalue(L, 1 + (min == y));
        max = x ^ t;
        lua_pushvalue(L, 1 + (max == y));
        break;
      }
      default:
        luaL_error(L, "Error in " LUA_QS ": datatype %d is not supported.", "ints.minmax", a->datatype);
    }
  }
  return 2;
}


/* Taken from: https://graphics.stanford.edu/~seander/bithacks.html,
   "Compute parity of word with a multiply ", 6.2.2 */
static INLINE uint64_t parityu64 (uint64_t v) {
  v ^= v >> 1;
  v ^= v >> 2;
  v = (v & 0x1111111111111111ULL)*0x1111111111111111ULL;
  return (v >> 60ULL) & 1ULL;
}

static int ints_parity (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T:
      lua_pushinteger(L, parityu64(a->data.ui));
      break;
    case INT64T:
      lua_pushinteger(L, parityu64((uint64_t)a->data.i));
      break;
    default:
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.parity");
  }
  return 1;
}


/* Retrieves the upper 32-bits of a signed or unsigned 64-bit integer x and returns them as a signed
   Agena number.
   See also: ints.getlow, ints.getwords, ints.sethigh, ints.setlow, ints.setwords. 6.2.3 */
static int ints_gethigh (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T:
      lua_pushnumber(L, gethighu32(a->data.ui));
      break;
    case INT64T:
      lua_pushnumber(L, gethigh32(a->data.i));
      break;
    default:
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.gethigh");
  }
  return 1;
}

/* Retrieves the lower 32-bits of a signed or unsigned 64-bit integer x and returns them as a signed
   Agena number.
   See also: ints.gethigh, ints.getwords, ints.sethigh, ints.setlow, ints.setwords. 6.2.3 */
static int ints_getlow (lua_State *L) {  /* 6.2.3 */
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T:
      lua_pushnumber(L, getlowu32(a->data.ui));
      break;
    case INT64T:
      lua_pushnumber(L, getlow32(a->data.i));
      break;
    default:
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.getlow");
  }
  return 1;
}

/* Retrieves both the higher and the lower 32-bits of a signed or unsigned 64-bit integer n and returns
   them as two Agena numbers. If n is signed, then the result may also be signed. If n is unsigned, so will
   be the result.
   See also: ints.gethigh, ints.getlow, ints.sethigh, ints.setlow, ints.setwords. 6.2.3 */
static int ints_getwords (lua_State *L) {  /* 6.2.3 */
  uint64_t x;
  Ints *a = aux_checkint(L, 1);
  luaL_checkstack(L, 2, "not enough stack space");
  switch (a->datatype) {
    case UINT64T:
      x = a->data.ui;
      lua_pushnumber(L, gethighu32(x));
      lua_pushnumber(L, getlowu32(x));
      break;
    case INT64T:
      x = a->data.i;
      lua_pushnumber(L, gethigh32(x));
      lua_pushnumber(L, getlow32(x));
      break;
    default: {
      agn_poptop(L);
      luaL_error(L, "Error in " LUA_QS ": need a signed or unsigned 64-bit integer.", "ints.getwords");
    }
  }
  return 2;
}


/* Takes two integers h, l and sets them as the higher and lower 32-bits of a new signed or unsigned 64-bit
   integer which is the result. By default or if `sign` is set to `false`, an unsigned integer will
   be returned. If `sign` is `true` the resulting 64-bit integer will be signed.
   See also: ints.gethigh, ints.getlow, ints.getwords, ints.sethigh, ints.setlow. 6.2.3 */
static int ints_setwords (lua_State *L) {
  int sign;
  luaL_checkany(L, 2);
  sign = agnL_optboolean(L, 3, 0);
  switch (sign) {
    case 0: {
      uint32_t h, l;
      h = luaL_checkuint32_t(L, 1);
      l = luaL_checkuint32_t(L, 2);
      createuint64(L, reassemble_64(h, l));
      break;
    }
    case 1: {
      int32_t h, l;
      h = luaL_checkint32_t(L, 1);
      l = luaL_checkint32_t(L, 2);
      createint64(L, reassemble_64(h, l));
      break;
    }
    default: {
      agn_poptop(L);
      luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.setwords");
    }
  }
  return 1;
}


/* Takes a signed or unsigned 64-bit integer n and an Agena number h and sets h to the higher 32 bits in n.
   The operation is in-place, thus modifying n. The function returns nothing.
   See also: ints.gethigh, ints.getlow, ints.getwords, ints.setlow, ints.setwords. 6.2.3 */
static int ints_sethigh (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint32_t h = luaL_checkuint32_t(L, 2);
      sethighu64(&a->data.ui, h);
      break;
    }
    case INT64T: {
      int32_t h = luaL_checkint32_t(L, 2);
      sethigh64(&a->data.i, h);
      break;
    }
    default: {
      agn_poptop(L);
      luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.sethigh");
    }
  }
  return 0;
}


/* Takes a signed or unsigned 64-bit integer n and an Agena number l and sets l to the lower 32 bits in n.
   The operation is in-place, thus modifying n. The function returns nothing.
   See also: ints.gethigh, ints.getlow, ints.getwords, ints.sethigh, ints.setwords. 6.2.3 */
static int ints_setlow (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint32_t l = luaL_checkuint32_t(L, 2);
      setlowu64(&a->data.ui, l);
      break;
    }
    case INT64T: {
      int32_t l = luaL_checkint32_t(L, 2);
      setlow64(&a->data.i, l);
      break;
    }
    default: {
      agn_poptop(L);
      luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.setlow");
    }
  }
  return 0;
}


/* Checks whether its argument n is a signed 64-bit integer and returns `true` or `false`.
   See also: ints.checkint64, ints.checkuint64, ints.isuint64. 6.2.3 */
static int ints_isint64 (lua_State *L) {  /* 6.2.3, changed 6.3.1 */
  int i, r = 1, nargs = lua_gettop(L);
  if (nargs == 0) {  /* 6.5.3 */
    luaL_error(L, "Error in " LUA_QS ": need at least one value.", "ints.isint64");
  }
  for (i=0; i < nargs && r; i++) {  /* 6.5.2 extension */
    if (!isints(L, i + 1)) {
      r = 0;
    } else {
      Ints *a = lua_touserdata(L, i + 1);
      r = a->datatype == INT64T;
    }
  }
  lua_pushboolean(L, r);
  return 1;
}


/* Checks whether its argument n is an unsigned 64-bit integer and returns `true` or `false`.
   See also: ints.checkint64, ints.checkuint64, ints.isint64. 6.2.3, changed 6.3.1 */
static int ints_isuint64 (lua_State *L) {
  int i, r = 1, nargs = lua_gettop(L);
  if (nargs == 0) {  /* 6.5.3 */
    luaL_error(L, "Error in " LUA_QS ": need at least one value.", "ints.isuint64");
  }
  for (i=0; i < nargs && r; i++) {  /* 6.5.2 extension */
    if (!isints(L, i + 1)) {
      r = 0;
    } else {
      Ints *a = lua_touserdata(L, i + 1);
      r = a->datatype == UINT64T;
    }
  }
  lua_pushboolean(L, r);
  return 1;
}


/* Checks whether its argument n is a signed 64-bit integer and issues an error otherwise. You may optionally
   pass the name of the calling function for `procname` so that it is included in the error message. If n passed
   the test successfully, the function returns nothing.
   See also: ints.checkuint64, ints.isint64, ints.isuint64. 6.2.3, extended 6.5.2 */
static int ints_checkint64 (lua_State *L) {
  Ints *a;
  const char *procname = NULL;
  int i, j, r = 1, nargs = lua_gettop(L);
  if (nargs > 1 && agn_isstring(L, nargs)) procname = agn_tostring(L, nargs--);
  if (nargs == 0) {  /* 6.5.3 */
    luaL_error(L, "Error in " LUA_QS ": need at least one value.", "ints.checkint64");
  }
  for (i=0; i < nargs && r; i++) {
    j = i + 1;
    if (!isints(L, j)) {
      if (procname == NULL)
        luaL_error(L, "Error: expected signed 64-bit integer for arg #%d, got %s.", j, luaL_typename(L, j));
      else
        luaL_error(L, "Error in " LUA_QS ": expected signed 64-bit integer for arg #%d, got %s.", procname, j, luaL_typename(L, j));
    }
    a = toints(L, j);
    if (a->datatype != INT64T) {
      if (procname == NULL)
        luaL_error(L, "Error: expected signed 64-bit integer for arg #%d, got unsigned one.", j);
      else
        luaL_error(L, "Error in " LUA_QS ": got unsigned 64-bit integer for arg #%d.", procname, j);
    }
  }
  return 0;
}


/* Checks whether its argument n is an unsigned 64-bit integer and issues an error otherwise. You may optionally
   pass the name of the calling function for `procname` so that it is included in the error message. If n passed
   the test successfully, the function returns nothing.
   See also: ints.checkint64, ints.isint64, ints.isuint64. 6.2.3, extended 6.5.2 */
static int ints_checkuint64 (lua_State *L) {
  Ints *a;
  const char *procname = NULL;
  int i, j, r = 1, nargs = lua_gettop(L);
  if (nargs > 1 && agn_isstring(L, nargs)) procname = agn_tostring(L, nargs--);
  if (nargs == 0) {  /* 6.5.3 */
    luaL_error(L, "Error in " LUA_QS ": need at least one value.", "ints.checkuint64");
  }
  for (i=0; i < nargs && r; i++) {
    j = i + 1;
    if (!isints(L, j)) {
      if (procname == NULL)
        luaL_error(L, "Error: expected signed 64-bit integer for arg #%d, got %s.", j, luaL_typename(L, j));
      else
        luaL_error(L, "Error in " LUA_QS ": expected signed 64-bit integer for arg #%d, got %s.", procname, j, luaL_typename(L, j));
    }
    a = toints(L, j);
    if (a->datatype != UINT64T) {
      if (procname == NULL)
        luaL_error(L, "Error: expected unsigned 64-bit integer for arg #%d, got unsigned one.", j);
      else
        luaL_error(L, "Error in " LUA_QS ": got signed 64-bit integer for arg #%d.", procname, j);
    }
  }
  return 0;
}


static int ints_isposint (lua_State *L) {  /* 6.5.2 */
  Ints *a;
  int i, r = 1, nargs = lua_gettop(L);
  if (nargs == 0) {  /* 6.5.3 */
    luaL_error(L, "Error in " LUA_QS ": need at least one value.", "ints.isposint");
  }
  for (i=0; i < nargs && r; i++) {
    a = aux_checkint(L, i + 1);
    switch (a->datatype) {
      case UINT64T: {
        uint64_t v = a->data.ui;
        r = v > 0ULL;
        break;
      }
      case INT64T: {
        int64_t v = a->data.i;
        r = v > 0LL;
        break;
      }
      default: {
        luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.isposint");
      }
    }
  }
  lua_pushboolean(L, r);
  return 1;
}


static int ints_isnonnegint (lua_State *L) {  /* 6.5.2 */
  Ints *a;
  int i, r = 1, nargs = lua_gettop(L);
  if (nargs == 0) {  /* 6.5.3 */
    luaL_error(L, "Error in " LUA_QS ": need at least one value.", "ints.isnonnegint");
  }
  for (i=0; i < nargs && r; i++) {
    a = aux_checkint(L, i + 1);
    switch (a->datatype) {
      case UINT64T: {
        r = 1;
        break;
      }
      case INT64T: {
        int64_t v = a->data.i;
        r = v >= 0LL;
        break;
      }
      default: {
        luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.isnonnegint");
      }
    }
  }
  lua_pushboolean(L, r);
  return 1;
}


static int ints_isnegint (lua_State *L) {  /* 6.5.2 */
  Ints *a;
  int i, r = 1, nargs = lua_gettop(L);
  if (nargs == 0) {  /* 6.5.3 */
    luaL_error(L, "Error in " LUA_QS ": need at least one value.", "ints.isnegint");
  }
  for (i=0; i < nargs && r; i++) {
    a = aux_checkint(L, i + 1);
    switch (a->datatype) {
      case UINT64T: {
        r = 0;
        break;
      }
      case INT64T: {
        int64_t v = a->data.i;
        r = v < 0LL;
        break;
      }
      default: {
        luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.isnegint");
      }
    }
  }
  lua_pushboolean(L, r);
  return 1;
}


/* Checks whether the signed or unsigned 64-bit integer n is a power of two and returns `true` or `false`.
   The input can also be an Agena number or a string depicting a 64-bit integer.
   With signed input n, the check is done for the absolute value of n.
   See also: ints.nextpow2. 6.2.3 */
static int ints_ispow2 (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t v = a->data.ui;
      lua_pushboolean(L, v && !(v & (v - 1ULL)));
      break;
    }
    case INT64T: {
      int64_t v = abs64(a->data.i);
      lua_pushboolean(L, v && !(v & (v - 1ULL)));
      break;
    }
    default: {
      luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.ispow2");
    }
  }
  return 1;
}


static int ints_nextpow2 (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t v = a->data.ui;
      v = tools_nextpow2u64(v);
      if (v < a->data.ui) {  /* 6.3.3 */
        lua_pushtrue(L);
        lua_setglobal(L, "numoverflow");
      }
      createuint64(L, v);
      break;
    }
    case INT64T: {
      int64_t v = tools_nextpow2u64(abs64(a->data.i));
      if (v < a->data.i) {  /* 6.3.3 */
        lua_pushtrue(L);
        lua_setglobal(L, "numoverflow");
      }
      createint64(L, v);
      break;
    }
    default: {
      luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.nextpow2");
    }
  }
  return 1;
}


/* Checks whether the signed or unsigned 64-bit integer n is a prime and returns `true` or `false`.
   n may also be a non-negative Agena number or a string representing a non-negative integer.
   With signed input n, the check is done for the absolute value of n.
   See also: ints.nextprime. */
static int ints_isprime (lua_State *L) {  /* 6.2.3 */
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      lua_pushboolean(L, tools_isprime(a->data.ui));  /* 100+ percent tuning, 6.3.2 */
      break;
    }
    case INT64T: {
      uint64_t v = abs64(a->data.i);
      lua_pushboolean(L, tools_isprime(v));  /* 100+ percent tuning, 6.3.2 */
      break;
    }
    default: {
      luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.isprime");
    }
  }
  return 1;
}


/* Determines if two integers a, b are relatively prime (or co-prime). Two numbers are co-prime if they
   share no common positive factors other than 1. 6.3.5 */
static int ints_iscoprime (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  Ints *b = aux_checkint(L, 2);
  if (a->datatype != b->datatype)
    luaL_error(L, "Error in " LUA_QS ": data is of different type.", "ints.iscoprime");
  switch (a->datatype) {
    case UINT64T:
      lua_pushboolean(L, tools_gcdu64(a->data.ui, b->data.ui) == 1ULL);
      break;
    case INT64T:
      lua_pushboolean(L, tools_gcdi64(a->data.i, b->data.i) == 1LL);
      break;
    default:
      luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.iscoprime");
  }
  return 1;
}


/* For the signed or unsigned 64-bit integer n returns the next prime. n may also be a non-negative Agena number
   or a string representing a non-negative integer. With signed input n, the function computes the next prime
   for the absolute value of n. If the return is zero it indicates an overflow. See also: ints.isprime. 6.2.3 */
static int ints_nextprime (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t v = tools_nextprime(a->data.ui);
      if (v < a->data.ui) {  /* 6.3.3 */
        lua_pushtrue(L);
        lua_setglobal(L, "numoverflow");
      }
      createuint64(L, v);
      break;
    }
    case INT64T: {
      uint64_t v = abs64(a->data.i);
      v = tools_nextprime(v);
      if (v < a->data.ui) {  /* 6.3.3 */
        lua_pushtrue(L);
        lua_setglobal(L, "numoverflow");
      }
      createint64(L, v);
      break;
    }
    default: {
      luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.nextprime");
    }
  }
  return 1;
}


/* Returns the largest prime less than integer n. 6.3.2 */
static int ints_prevprime (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T: {
      uint64_t v = tools_prevprime(a->data.ui);
      if (a->data.ui == 0ULL) {  /* 6.3.3 */
        lua_pushtrue(L);
        lua_setglobal(L, "numoverflow");
      }
      createuint64(L, v);
      break;
    }
    case INT64T: {
      uint64_t v = tools_prevprime(abs64(a->data.i));
      if (a->data.ui == 0ULL) {  /* 6.3.3 */
        lua_pushtrue(L);
        lua_setglobal(L, "numoverflow");
      }
      createint64(L, v);
      break;
    }
    default: {
      luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.nextprime");
    }
  }
  return 1;
}

/* Conducts modular multiplication (a*b) % mod, avoiding overflow. a, b, mod must all be unsigned
   64-bit integers, nonnegative Agena numbers or strings representing a non-negative integer.
   If mod is zero, the function returns zero. See also: ints.powmod. 6.2.3 */
static int ints_mulmod (lua_State *L) {
  Ints *base = aux_checkint(L, 1);
  Ints *expo = aux_checkint(L, 2);
  Ints *mod  = aux_checkint(L, 3);
  if (base->datatype == UINT64T && expo->datatype == UINT64T && mod->datatype == UINT64T) {
    createuint64(L, tools_mulmodu64(base->data.ui, expo->data.ui, mod->data.ui));
  } else if (base->datatype == INT64T && expo->datatype == INT64T && mod->datatype == INT64T) {  /* 6.3.3 */
    createint64(L, tools_mulmodi64(base->data.i, expo->data.i, mod->data.i));
  } else {
    luaL_error(L, "Error in " LUA_QS ": expected signed or unsigned 64-bit integers only.", "ints.mulmod");
  }
  return 1;
}


/* Conducts modular exponentiation (a^b) % mod, avoiding overflow. a, b, mod must all be unsigned
   64-bit integers, nonnegative Agena numbers or strings representing a non-negative integer.
   If mod is zero, the function returns zero. See also: ints.mulmod. 6.2.3 */
static int ints_powmod (lua_State *L) {
  Ints *base = aux_checkint(L, 1);
  Ints *expo = aux_checkint(L, 2);
  Ints *mod  = aux_checkint(L, 3);
  if (base->datatype == UINT64T && expo->datatype == UINT64T && mod->datatype == UINT64T) {
    createuint64(L, tools_powmodu64(base->data.ui, expo->data.ui, mod->data.ui));
  } else if (base->datatype == INT64T && expo->datatype == INT64T && mod->datatype == INT64T) {  /* 6.3.3 */
    createint64(L, tools_powmodi64(base->data.i, expo->data.i, mod->data.i));
  } else {
    luaL_error(L, "Error in " LUA_QS ": expected signed or unsigned 64-bit integers only.", "ints.powmod");
  }
  return 1;
}


/* Generated by Gemini AI, put into the public domain. 10.29.2025
   A helper function to implement the Extended Euclidean Algorithm (EEA).
   It calculates: a*x + m*y = gcd(a, m)
   It returns the gcd, and updates x and y to hold the coefficients.
   Note: The EEA naturally returns signed coefficients (x, y), even for unsigned inputs. */
static uint64_t aux_gcdu64 (uint64_t a, uint64_t m, int64_t *x, int64_t *y) {
  if (a == 0ULL) {
    *x = 0LL; *y = 1LL; return m;
  }
  /* Recursive step */
  int64_t x1, y1;
  uint64_t gcd = aux_gcdu64(m % a, a, &x1, &y1);
  /* Update x and y using results from recursive call */
  *x = y1 - (int64_t)(m/a)*x1;
  *y = x1;
  return gcd;
}

/* Generated by Gemini AI, put into the public domain. 10.29.2025
   Calculates the modular multiplicative inverse of 'a' modulo 'm'.
   Returns 'x' such that a*x === 1 (mod m).
   Returns 0 if the inverse does not exist (gcd(a, m) != 1) or if m is 0/1. */
uint64_t modinverseu64 (uint64_t a, uint64_t m) {
  int64_t x, y, a_mod, gcd, m_signed, inv_signed;
  if (m <= 1ULL) return 0ULL;
  /* 1. Calculate a mod m */
  a_mod = a % m;
  /* Edge case: 0 has no inverse mod m (unless m=1, which is checked above) */
  if (a_mod == 0ULL) return 0ULL;
  /* 2. Compute GCD and the coefficient x */
  gcd = aux_gcdu64(a_mod, m, &x, &y);
  /* 3. Check if the inverse exists */
  if (gcd != 1ULL) return 0ULL;  /* Inverse does not exist (a and m are not coprime) */
  /* 4. Adjust x to be in the positive range [1, m-1]
        The result 'x' is a signed integer from EEA. We must map it back to
        the unsigned [1, m-1] range using modular arithmetic.
        Cast m to signed for the operation, then adjust if negative */
  m_signed = (int64_t)m;
  inv_signed = x % m_signed;
  if (inv_signed < 0LL) inv_signed += m_signed;
  return (uint64_t)inv_signed;
}

static int64_t aux_gcdi64 (int64_t a, int64_t m, int64_t *x, int64_t *y) {
  int64_t x1, y1, gcd;
  if (a == 0LL) {
    *x = 0LL; *y = 1LL; return m;
  }
  /* Recursive step */
  gcd = aux_gcdi64(m % a, a, &x1, &y1);
  /* Update x and y using results from recursive call */
  *x = y1 - (m/a)*x1;
  *y = x1;
  return gcd;
}

/* Calculates the modular multiplicative inverse of 'a' modulo 'm'.
   Returns 'x' such that a*x === 1 (mod m).
   Returns 0 if the inverse does not exist (gcd(a, m) != 1). */
static int64_t modinverse64 (int64_t a, int64_t m) {
  if (m <= 0LL) return 0LL;
  int64_t x, y, a_mod, gcd, inv;
  /* 1. Ensure 'a' is in the canonical positive range [0, m-1] */
  a_mod = a % m;
  if (a_mod < 0LL) a_mod += m;
  /* Edge case: if a_mod is 0, the inverse does not exist (unless m=1) */
  if (a_mod == 0LL) return 0LL;
  /* 2. Compute GCD and the coefficient x */
  gcd = aux_gcdi64(a_mod, m, &x, &y);
  /* 3. Check if the inverse exists */
  if (gcd != 1LL) return 0LL;  /* Inverse does not exist (a and m are not coprime) */
  /* 4. Adjust x to be in the positive range [1, m-1]
        The EEA guarantees that 'x' is the solution, but it might be negative. */
  inv = x % m;
  if (inv < 0LL) inv += m;
  return inv;
}

static int ints_invmod (lua_State *L) {  /* 6.3.3 */
  Ints *a = aux_checkint(L, 1);
  Ints *m = aux_checkint(L, 2);
  if (a->datatype == UINT64T && m->datatype == UINT64T) {
    createuint64(L, modinverseu64(a->data.ui, m->data.ui));
  } else if (a->datatype == INT64T && m->datatype == INT64T) {
    createint64(L, modinverse64(a->data.i, m->data.i));
  } else {
    luaL_error(L, "Error in " LUA_QS ": expected signed or unsigned 64-bit integers only.", "ints.invmod");
  }
  return 1;
}



static int ints_lcm (lua_State *L) {  /* 6.3.3 */
  Ints *a = aux_checkint(L, 1);
  Ints *m = aux_checkint(L, 2);
  if (a->datatype == UINT64T && m->datatype == UINT64T) {
    createuint64(L, tools_lcmu64(a->data.ui, m->data.ui));
  } else if (a->datatype == INT64T && m->datatype == INT64T) {
    createint64(L, tools_lcmi64(a->data.i, m->data.i));
  } else {
    luaL_error(L, "Error in " LUA_QS ": expected signed or unsigned 64-bit integers only.", "ints.lcm");
  }
  return 1;
}


static int ints_gcd (lua_State *L) {  /* 6.3.3 */
  Ints *a = aux_checkint(L, 1);
  Ints *m = aux_checkint(L, 2);
  if (a->datatype == UINT64T && m->datatype == UINT64T) {
    createuint64(L, tools_gcdu64(a->data.ui, m->data.ui));
  } else if (a->datatype == INT64T && m->datatype == INT64T) {
    createint64(L, tools_gcdi64(a->data.i, m->data.i));
  } else {
    luaL_error(L, "Error in " LUA_QS ": expected signed or unsigned 64-bit integers only.", "ints.gcd");
  }
  return 1;
}


/* Creates a genuine duplicate of the signed or unsigned 64-bit integer n. 6.2.3 */
static int ints_copy (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T:
      createuint64(L, a->data.ui);
      break;
    case INT64T:
      createint64(L, a->data.i);
      break;
    default: {
      luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.copy");
    }
  }
  return 1;
}


/* Swaps the values of integers a, b in-place. The function returns nothing. 6.4.2 */
static int ints_swap (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  Ints *b = aux_checkint(L, 2);
  if (a->datatype != b->datatype) {
    luaL_error(L, "Error in " LUA_QS ": expected signed or unsigned 64-bit integers only.", "ints.swap");
  }
  switch (a->datatype) {
    case UINT64T: {
      uint64_t t = a->data.ui;
      a->data.ui = b->data.ui;
      b->data.ui = t;
      break;
    }
    case INT64T: {
      int64_t t = a->data.i;
      a->data.i = b->data.i;
      b->data.i = t;
      break;
    }
    default: {
      luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.swap");
    }
  }
  return 0;
}


static uint64_t reverseu64 (uint64_t a) {
  uint64_t result = 0ULL;
  int i;
  /* Loop through all 64 bits sequentially */
  for (i = 0; i < 64; ++i) {
    /* Shift the current result left by one bit */
    result <<= 1;
    /* Take the LSB of the input 'a' and set it as the MSB of the result */
    result |= (a & 1ULL);
    /* Shift the input 'a' right to process the next bit */
    a >>= 1;
  }
  return result;
}

static int ints_reverse (lua_State *L) {
  Ints *a = aux_checkint(L, 1);
  switch (a->datatype) {
    case UINT64T:
      createuint64(L, reverseu64(a->data.ui));
      break;
    case INT64T:
      createint64(L, (int64_t)reverseu64((int64_t)a->data.i));
      break;
    default: {
      luaL_error(L, "Error in " LUA_QS ": this should not happen.", "ints.reverse");
    }
  }
  return 1;
}


static const struct luaL_Reg ints_metalib [] = {  /* metamethods for numeric userdata `n` */
  {"__unm",       mt_unm},
  {"__abs",       mt_abs},
  {"__absdiff",   mt_absdiff},
  {"__sign",      mt_sign},
  {"__eq",        mt_eq},
  {"__aeq",       mt_eq},  /* new 7.10.6 */
  {"__lt",        mt_lt},
  {"__le",        mt_le},
  {"__add",       mt_add},
  {"__sub",       mt_sub},
  {"__mul",       mt_mul},
  {"__div",       mt_div},
  {"__intdiv",    mt_div},
  {"__mod",       mt_mod},
  {"__brotl",     mt_brotl},
  {"__brotr",     mt_brotr},
  {"__bshl",      mt_bshl},
  {"__bshr",      mt_bshr},
  {"__band",      mt_band},
  {"__bnot",      mt_bnot},
  {"__bor",       mt_bor},
  {"__bxor",      mt_bxor},
  {"__sqrt",      mt_sqrt},
  {"__pow",       mt_pow},
  {"__ipow",      mt_pow},
  {"__antilog2",  mt_antilog2},
  {"__antilog10", mt_antilog10},
  {"__square",    mt_square},
  {"__cube",      mt_cube},
  {"__even",      mt_even},
  {"__odd",       mt_odd},
  {"__zero",      mt_zero},
  {"__nonzero",   mt_nonzero},
  {"__index",     mt_index},     /* OOP-style calls */
  {"__tostring",  mt_tostring},  /* for output at the console, e.g. print(n) */
  {"__gc",        mt_gc},        /* do not forget garbage collection */
  {NULL, NULL}
};


static const luaL_Reg intsnumlib[] = {
  {"cbrt",        ints_cbrt},
  {"checkint64",  ints_checkint64},
  {"checkuint64", ints_checkuint64},
  {"copy",        ints_copy},
  {"gcd",         ints_gcd},
  {"getbit",      ints_getbit},
  {"getbits",     ints_getbits},
  {"gethigh",     ints_gethigh},
  {"getlow",      ints_getlow},
  {"getstore",    ints_getstore},
  {"getwords",    ints_getwords},
  {"int64",       ints_int64},
  {"invmod",      ints_invmod},
  {"iscoprime",   ints_iscoprime},
  {"isint64",     ints_isint64},
  {"isnegint",    ints_isnegint},
  {"isnonnegint", ints_isnonnegint},
  {"isposint",    ints_isposint},
  {"ispow2",      ints_ispow2},
  {"isprime",     ints_isprime},
  {"isuint64",    ints_isuint64},
  {"lcm",         ints_lcm},
  {"leadzeros",   ints_leadzeros},
  {"leastsigbit", ints_leastsigbit},
  {"log2",        ints_log2},
  {"log10",       ints_log10},
  {"max",         ints_max},
  {"mean",        ints_mean},
  {"min",         ints_min},
  {"minmax",      ints_minmax},
  {"mostsigbit",  ints_mostsigbit},
  {"mulmod",      ints_mulmod},
  {"nextpow2",    ints_nextpow2},
  {"nextprime",   ints_nextprime},
  {"onebits",     ints_onebits},
  {"parity",      ints_parity},
  {"powmod",      ints_powmod},
  {"prevprime",   ints_prevprime},
  {"random",      ints_random},
  {"reverse",     ints_reverse},
  {"root",        ints_root},
  {"setbit",      ints_setbit},
  {"sethigh",     ints_sethigh},
  {"setlow",      ints_setlow},
  {"setwords",    ints_setwords},
  {"swap",        ints_swap},
  {"tobytes",     ints_tobytes},
  {"todouble",    ints_todouble},
  {"toint64",     ints_toint64},
  {"tonumber",    ints_tonumber},
  {"tostring",    ints_tostring},
  {"touint64",    ints_touint64},
  {"trailzeros",  ints_trailzeros},
  {"uint64",      ints_uint64},
  {NULL, NULL}
};


/*
** Open ints library
*/
LUALIB_API int luaopen_ints (lua_State *L) {
  luaL_newmetatable(L, AGENA_INTSLIBNAME);
  luaL_register(L, NULL, ints_metalib);
  luaL_register(L, AGENA_INTSLIBNAME, intsnumlib);
  /* a few unsigned constants, 6.2.1 */
  lua_pushliteral(L, "naught");
  createuint64(L, 0ULL);
  lua_rawset(L, -3);
  lua_pushliteral(L, "nought");
  createuint64(L, 0ULL);
  lua_rawset(L, -3);
  lua_pushliteral(L, "one");
  createuint64(L, 1ULL);
  lua_rawset(L, -3);
  lua_pushliteral(L, "two");
  createuint64(L, 2ULL);
  lua_rawset(L, -3);
  lua_pushliteral(L, "three");
  createuint64(L, 3ULL);
  lua_rawset(L, -3);
  lua_pushliteral(L, "four");
  createuint64(L, 4ULL);
  lua_rawset(L, -3);
  lua_pushliteral(L, "five");
  createuint64(L, 5ULL);
  lua_rawset(L, -3);
  lua_pushliteral(L, "six");
  createuint64(L, 6ULL);
  lua_rawset(L, -3);
  lua_pushliteral(L, "seven");
  createuint64(L, 7ULL);
  lua_rawset(L, -3);
  lua_pushliteral(L, "eight");
  createuint64(L, 8ULL);
  lua_rawset(L, -3);
  lua_pushliteral(L, "nine");
  createuint64(L, 9ULL);
  lua_rawset(L, -3);
  lua_pushliteral(L, "ten");
  createuint64(L, 10ULL);
  lua_rawset(L, -3);
  return 1;
}

