# makefile for building the strict-ANSI version of Agena with GCC

# Rename this file from `makefile.ansi` to `makefile` and then compile Agena in the
# src directory with the following two statements (make -f makefile.ansi will not work !):
#      make config
#      make ansi

# You need the MAPM library files available at http://downloads.sourceforge.net/agena/mapmagena-x.y.z.tar.gz
# to compile Agena.

# == CHANGE THE SETTINGS BELOW TO SUIT YOUR ENVIRONMENT =======================

# Your platform. See PLATS for possible values.
PLAT= none

CC= gcc
CFLAGS= -Wall $(MYCFLAGS)
AR= ar rcu
RANLIB= ranlib
RM= rm -f
LIBS= -lm -lmapm $(MYLIBS)

MYCFLAGS=
MYLDFLAGS=
MYLIBS=

# == END OF USER SETTINGS. NO NEED TO CHANGE ANYTHING BELOW THIS LINE =========

PLATS= ansi

LUA_A=  libagena.a
CORE_O= lapi.o lcode.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o \
	lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o \
	lundump.o lvm.o lzio.o lset.o lseq.o lpair.o agnhlps.o iniparse.o lreg.o
LIB_O=  agnxlib.o lbaselib.o ldblib.o liolib.o lmathlib.o loslib.o ltablib.o \
	lrtable.o lenviron.o lstrlib.o utils.o loadlib.o linit.o stats.o ads.o \
	agnhlps.o bags.o cephes.o calc.o linalg.o binio.o mapm.o xbase.o agnt64.o \
	sofa.o interp.o moon.o sunriset.o astro.o skycrane.o gzip.o llist.o cordic.o \
	rlhmath.o lreglib.o hashes.o numarray.o registry.o zx.o stack.o

LUA_T=	agena
LUA_O=	agena.o

ALL_O= $(CORE_O) $(LIB_O) $(LUA_O) $(LUAC_O)
ALL_T= $(LUA_A) $(LUA_T)
ALL_A= $(LUA_A)

default: $(PLAT)

all:	$(ALL_T)

o:	$(ALL_O)

a:	$(ALL_A)

$(LUA_A): $(CORE_O) $(LIB_O)
	$(AR) $@ $?
	$(RANLIB) $@

$(LUA_T): $(LUA_O) $(LUA_A)
	$(CC) -o $@ $(MYLDFLAGS) $(LUA_O) $(LUA_A) $(LIBS)

#$(LUAC_T): $(LUAC_O) $(LUA_A)
#	$(CC) -o $@ $(MYLDFLAGS) $(LUAC_O) $(LUA_A) $(LIBS)

clean:
	$(RM) $(ALL_T) $(ALL_O) agena.dll agena.exe agncfg.h config config.exe libagena.so agena.res

config: config.c
	$(CC) $(CFLAGS) -o config config.c
	./config agncfg.h

depend:
	@$(CC) $(CFLAGS) -MM l*.c

echo:
	@echo "PLAT = $(PLAT)"
	@echo "CC = $(CC)"
	@echo "CFLAGS = $(CFLAGS)"
	@echo "AR = $(AR)"
	@echo "RANLIB = $(RANLIB)"
	@echo "RM = $(RM)"
	@echo "MYCFLAGS = $(MYCFLAGS)"
	@echo "MYLDFLAGS = $(MYLDFLAGS)"
	@echo "MYLIBS = $(MYLIBS)"

# convenience targets for popular platforms

none:
	@echo "Please choose a platform:"
	@echo "   $(PLATS)"

ansi:
	$(MAKE) all MYCFLAGS="-O2 -DLUA_ANSI -DPROPCMPLX"
	strip $(LUA_T)

install:
	cp ./agena /usr/local/bin

# list targets that do not create files (but not all makes understand .PHONY)
#.PHONY: all $(PLATS) default o a clean depend echo none

# DO NOT DELETE

lapi.o: lapi.c agena.h agncmpt.h agnconf.h agnhlps.h lapi.h lobject.h llimits.h ldebug.h \
  lstate.h ltm.h lundump.h lzio.h lmem.h ldo.h lfunc.h lgc.h lstring.h ltable.h \
agenalib.h
agnxlib.o: agnxlib.c agena.h agnconf.h agnxlib.h
lbaselib.o: lbaselib.c agena.h agnconf.h agnxlib.h agenalib.h
lcode.o: lcode.c agena.h agnconf.h lcode.h llex.h lobject.h llimits.h \
  lzio.h lmem.h lopcodes.h lparser.h ldebug.h lstate.h ltm.h ldo.h lgc.h \
  ltable.h
ldblib.o: ldblib.c agena.h agnconf.h agnxlib.h agenalib.h
ldebug.o: ldebug.c agena.h agnconf.h lapi.h lobject.h llimits.h lcode.h \
  llex.h lzio.h lmem.h lopcodes.h lparser.h ldebug.h lstate.h ltm.h ldo.h \
  lfunc.h lstring.h lgc.h ltable.h lvm.h
ldo.o: ldo.c agena.h agnconf.h ldebug.h lstate.h lobject.h llimits.h ltm.h \
  lzio.h lmem.h ldo.h lfunc.h lgc.h lopcodes.h lparser.h lstring.h \
  ltable.h lundump.h lvm.h
ldump.o: ldump.c agena.h agnconf.h lobject.h llimits.h lstate.h ltm.h \
  lzio.h lmem.h lundump.h
lfunc.o: lfunc.c agena.h agnconf.h lfunc.h lobject.h llimits.h lgc.h lmem.h \
  lstate.h ltm.h lzio.h
lgc.o: lgc.c agena.h agnconf.h ldebug.h lstate.h lobject.h llimits.h ltm.h \
  lzio.h lmem.h ldo.h lfunc.h lgc.h lstring.h ltable.h
linit.o: linit.c agena.h agnconf.h agenalib.h agnxlib.h
liolib.o: liolib.c agena.h agnconf.h agnxlib.h agenalib.h
llex.o: llex.c agena.h agnconf.h ldo.h lobject.h llimits.h lstate.h ltm.h \
  lzio.h lmem.h llex.h lparser.h lstring.h lgc.h ltable.h
lmathlib.o: lmathlib.c agena.h agnconf.h agnxlib.h agenalib.h
lmem.o: lmem.c agena.h agnconf.h ldebug.h lstate.h lobject.h llimits.h \
  ltm.h lzio.h lmem.h ldo.h
loadlib.o: loadlib.c agnxlib.h agena.h agnconf.h lobject.h llimits.h \
  agenalib.h
lobject.o: lobject.c agena.h agnconf.h ldo.h lobject.h llimits.h lstate.h \
  ltm.h lzio.h lmem.h lstring.h lgc.h lvm.h
lopcodes.o: lopcodes.c lopcodes.h llimits.h agena.h agnconf.h
loslib.o: loslib.c agena.h agnconf.h agnxlib.h agenalib.h sofa.h
lparser.o: lparser.c agena.h agnconf.h lcode.h llex.h lobject.h llimits.h \
  lzio.h lmem.h lopcodes.h lparser.h ldebug.h lstate.h ltm.h ldo.h \
  lfunc.h lstring.h lgc.h ltable.h
lrtable.o:	lrtable.c agena.h agnxlib.h agenalib.h
lenviron.o:	lenviron.c agena.h agnxlib.h agenalib.h
lstate.o: lstate.c agena.h agnconf.h ldebug.h lstate.h lobject.h llimits.h \
  ltm.h lzio.h lmem.h ldo.h lfunc.h lgc.h llex.h lstring.h ltable.h
lstring.o: lstring.c agena.h agnconf.h lmem.h llimits.h lobject.h lstate.h \
  ltm.h lzio.h lstring.h lgc.h
lstrlib.o: lstrlib.c agena.h agnconf.h agnxlib.h agenalib.h lstrlib.h
ltable.o: ltable.c agena.h agnconf.h ldebug.h lstate.h lobject.h llimits.h \
  ltm.h lzio.h lmem.h ldo.h lgc.h ltable.h
ltablib.o: ltablib.c agena.h agnconf.h agnxlib.h agenalib.h
lreglib.o: lreglib.c agena.h agnconf.h agnxlib.h agenalib.h
ltm.o: ltm.c agena.h agnconf.h lobject.h llimits.h lstate.h ltm.h lzio.h \
  lmem.h lstring.h lgc.h ltable.h
agena.o: agena.c agena.h agnconf.h agnxlib.h agenalib.h agnhlps.h
lundump.o: lundump.c agena.h agnconf.h ldebug.h lstate.h lobject.h \
  llimits.h ltm.h lzio.h lmem.h ldo.h lfunc.h lstring.h lgc.h lundump.h
lvm.o: lvm.c agena.h agnconf.h ldebug.h lstate.h lobject.h llimits.h ltm.h \
  lzio.h lmem.h ldo.h lfunc.h lgc.h lopcodes.h lstring.h ltable.h lset.h lvm.h
lzio.o: lzio.c agena.h agnconf.h llimits.h lmem.h lstate.h lobject.h ltm.h \
  lzio.h
utils.o: utils.c agena.h agnxlib.h agenalib.h lstrlib.h
agnhlps.o: agnhlps.c agnhlps.h agncmpt.h agnconf.h
cephes.o: cephes.c
agnt64.o: agnt64.c agnt64_l.h agnt64_c.h
sofa.o: sofa.c sofa.h
iniparse.o:	iniparse.c iniparse.h
moon.o: moon.c moon.h
sunriset.o: sunriset.c sunriset.h
lset.o: lset.c agena.h ldebug.h lstate.h lobject.h \
  lmem.h ldo.h lgc.h lset.h
lseq.o: lseq.c agena.h ldebug.h lstate.h lobject.h lmem.h ldo.h lgc.h \
  lseq.h
lreg.o: lreg.c agena.h ldebug.h lstate.h lobject.h lmem.h ldo.h lgc.h \
	lreg.h
lpair.o: lpair.c agena.h ldebug.h lstate.h lobject.h lmem.h ldo.h lgc.h \
  lpair.h
binio.o: binio.c agena.h agnxlib.h agenalib.h
ads.o: ads.c agena.h agnxlib.h agenalib.h agncfg.h agnhlps.h
astro.o: astro.c moon.c sunriset.c agena.h agnxlib.h agenalib.h agnxlib.h
calc.o: calc.c cephes.c interp.c rlhmath.c agena.h agnxlib.h agenalib.h
bags.o: bags.c agena.h agnxlib.h agenalib.h
linalg.o: linalg.c agena.h agnxlib.h agenalib.h
stats.o: stats.c cephes.c agena.h agnxlib.h agenalib.h
#phq.o: phq.c agena.h agnxlib.h agenalib.h utils.h
mapm.o:	mapm.c agena.h agnxlib.h agenalib.h m_apm.h
xbase.o: xbase.c agena.h agnxlib.h agenalib.h
skycrane.o: skycrane.c agena.h agnxlib.h agenalib.h
gzip.o:	gzip.c agena.h agnxlib.h agenalib.h
llist.o:	llist.c agena.h agnxlib.h agenalib.h
cordic.o:	cordic.c agena.h agnxlib.h agenalib.h
hashes.o:	hashes.c agena.h agnxlib.h agenalib.h
numarray.o:	numarray.c agena.h agnxlib.h agenalib.h agnhlps.h
registry.o: registry.c agena.h agnxlib.h agenalib.h agncmpt.h
stack.o: stack.c agena.h agnxlib.h agenalib.h
zx.o:	zx.c agena.h agnxlib.h agenalib.h agnhlps.h
# (end of Makefile)
