# Makefile for Agena plus packages
# Originally created by Gemini AI, 21/03/2026
# For the regular build, deployment:
# make -f makefile.pluswin
# For Dr. Memory:
# make -f makefile.pluswin DEBUG_BUILD=1

CC = gcc
STRIP = strip --strip-unneeded
LIB_DIR = ../lib

# --- Flag Definitions ---
# -Wtype-limits prints warnings about futile comparisons
#BASE_FLAGS = -pipe -fgnu89-inline -Wtype-limits -Wno-attributes -fno-omit-frame-pointer $(SSE_FLAGS)
BASE_FLAGS = -pipe -fgnu89-inline -Wtype-limits -Wno-attributes -fno-omit-frame-pointer
OFFS = -Wint-to-pointer-cast -Wpointer-to-int-cast

# Conditional flags configuration based on build type
ifdef DEBUG_BUILD
  # Dr. Memory configuration: -O0 guarantees non-scrambled line mapping
  # Removed -ffunction-sections and -fdata-sections to avoid memory block splitting
  OPT_FLAGS    = -O0 -g
  LINK_G_FLAG  = -g
  STRIP        = @echo Skipping strip for debug:
else
  # Production configuration: High optimization and aggressive sections pruning
  OPT_FLAGS    = -O3 -ffunction-sections -fdata-sections
  LINK_G_FLAG  =
  STRIP        = strip --strip-unneeded
endif

#ifeq ($(MSYSTEM),UCRT64)
#  ASTRO_FLOAT_FLAGS = -ffloat-store
#else ifeq ($(MSYSTEM),MINGW64)
#  ASTRO_FLOAT_FLAGS = -ffloat-store
#else ifdef IS64BIT
#  ASTRO_FLOAT_FLAGS = -ffloat-store
#else
#  # Legacy 32-bit target falls back to strict 64-bit float emulation capping
#  ASTRO_FLOAT_FLAGS = -ffloat-store
#endif

ASTRO_FLOAT_FLAGS = 

# Composite flags injected into rules
COMMON_FLAGS = $(OPT_FLAGS) $(BASE_FLAGS)
CFLAGS_DLL   = $(COMMON_FLAGS) $(LINK_G_FLAG) -I. -shared -Wl,--gc-sections
CFLAGS_OBJ   = $(COMMON_FLAGS) -c -DLUA_BUILD_AS_DLL -fcommon -Wno-inline
DD_FLAGS     = -ffloat-store -fno-unsafe-math-optimizations -fno-associative-math -fno-builtin

AG_LIBS = -L. -lagena

ifeq ($(MSYSTEM),UCRT64)
  NCURSES_INCDIR = -I/ucrt64/include/ncurses
else ifeq ($(MSYSTEM),MINGW64)
  NCURSES_INCDIR = -I/mingw64/include/ncurses
else ifdef IS64BIT
  NCURSES_INCDIR = -I/ucrt64/include/ncurses
else
  # Legacy 32-bit baseline (leaves include pointers clean or root-bound)
  NCURSES_INCDIR =
endif

# If compiling in a 64-bit MSYS2 shell, use the wide/dynamic library name.
# Otherwise, fall back to the standard library name for legacy 32-bit toolchains.
ifeq ($(MSYSTEM),UCRT64)
  CURSES_LIB = -lncursesw
else ifeq ($(MSYSTEM),MINGW64)
  CURSES_LIB = -lncursesw
else ifdef IS64BIT
  CURSES_LIB = -lncursesw
else
  CURSES_LIB = -lncurses
endif

ifeq ($(MSYSTEM),UCRT64)
  # Verweist direkt und absolut manipulationssicher auf die statische 64-Bit-Datei
  MAPM_LINK = ../ports/mapm_4.9.5/libmapm.a
else ifeq ($(MSYSTEM),MINGW64)
  MAPM_LINK = ../ports/mapm_4.9.5/libmapm.a
else ifdef IS64BIT
  MAPM_LINK = ../ports/mapm_4.9.5/libmapm.a
else
  # Dein originales 32-Bit-Legacy-System bleibt vollkommen unangetastet
  MAPM_LINK = -lmapm
endif

# --- Target Lists ---
DLLS = abci.dll ads.dll astro.dll com.dll cordic.dll curses.dll ddhash.dll \
	double.dll fastmath.dll fractals.dll gmp.dll gzip.dll iconv.dll ival.dll \
	mapm.dll minizip.dll mpfr.dll net.dll skycrane.dll strhash.dll strmap.dll \
	testlib.dll zx.dll

OBJS = abci.o ads.o agnt64.o astro.o cordic.o curses.o dcastro.o ival.o \
	miniz.o moon.o net.o network.o sdncal.o sofa.o sunriset.o vecoff64.o

all: $(DLLS)
	@echo [SUCCESS] Libraries built and linked against agena.dll

# --- Compilation Rules ---

abci.dll: abci.c
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $^ $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

ads.dll: ads.o vecoff64.o
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $^ $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

astro.dll: astro.o agnt64.o sofa.o sdncal.o moon.o sunriset.o dcastro.o
	@rm -f $@
#	$(CC) $(CFLAGS_DLL) -shared -static-libgcc -fpic -o $@ $^ $(AG_LIBS) -lkernel32
	$(CC) $(CFLAGS_DLL) -shared -static-libgcc -fPIC -o $@ $^ $(AG_LIBS) -lkernel32
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

com.dll: com.c luasys.c charbuf.c
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -DPLUS -o $@ $^ -lwsock32 -lwininet -lmswsock -lws2_32 $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

cordic.dll: cordic.o
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $^ $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

curses.dll: curses.o
	@rm -f $@
#	$(CC) $(CFLAGS_DLL) -o $@ $< -lncurses $(AG_LIBS)
	$(CC) $(CFLAGS_DLL) -DNCURSES_DLL -o $@ $< $(CURSES_LIB) $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

ddhash.dll: ddhash.c
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $< $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

double.dll: double.c
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $< $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

fastmath.dll: fastmath.c
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -Wno-strict-aliasing -o $@ $< $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

fractals.dll: fractals.c
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $< $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

gmp.dll: gmp.c
	@rm -f $@.tmp
	$(CC) $(CFLAGS_DLL) -o $@.tmp $< -lgmp $(AG_LIBS)
	$(STRIP) $@.tmp
	@mv -f $@.tmp $(LIB_DIR)/$@

gzip.dll: gzip.c
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $< -lz $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

iconv.dll: iconv.c
	@rm -f $@.tmp
	$(CC) $(CFLAGS_DLL) -o $@.tmp $< -liconv $(AG_LIBS)
	$(STRIP) $@.tmp
	@mv -f $@.tmp $(LIB_DIR)/$@

ival.dll: ival.o
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $< ../ports/ival/src/fi_lib.a $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

mapm.dll: mapm.c
	@rm -f mapm.tmp
	$(CC) $(CFLAGS_DLL) -o mapm.tmp $< $(MAPM_LINK) $(AG_LIBS)
	$(STRIP) mapm.tmp
	@rm -f $@
	@mv -f mapm.tmp $(LIB_DIR)/$@

minizip.dll: minizip.c miniz.o
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $^ $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

mpfr.dll: mpfr.c
	@rm -f $@.tmp
	$(CC) $(CFLAGS_DLL) -I../ports/mpfr-4.2.2/src -o $@.tmp $< -lmpfr -lgmp $(AG_LIBS)
	$(STRIP) $@.tmp
	@mv -f $@.tmp $(LIB_DIR)/$@

net.dll: net.o network.o
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $^ -lwsock32 -lwininet -lmswsock -lWs2_32 $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

strhash.dll: strhash.c
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $< $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

strmap.dll: strmap.c
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $< $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

skycrane.dll: skycrane.c
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $< $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

testlib.dll: testlib.c
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $< $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

zx.dll: zx.c
	@rm -f $@
	$(CC) $(CFLAGS_DLL) -o $@ $< $(AG_LIBS)
	$(STRIP) $@
	@mv -f $@ $(LIB_DIR)

# --- Object Rules ---

cordic.o: cordic.c
	$(CC) $(CFLAGS_OBJ) -o $@ $<

agnt64.o: agnt64.c
	$(CC) $(CFLAGS_OBJ) -o $@ $<

sofa.o: sofa.c
	$(CC) $(CFLAGS_OBJ) $(ASTRO_FLOAT_FLAGS) -o $@ $<

sdncal.o: sdncal.c
	$(CC) $(CFLAGS_OBJ) -o $@ $<

ival.o: ival.c
	$(CC) $(CFLAGS_OBJ) -I../ports/ival/src -o $@ $<

vecoff64.o: vecoff64.c
	$(CC) $(CFLAGS_OBJ) -o $@ $<

ads.o: ads.c
	$(CC) $(OFFS) $(CFLAGS_OBJ) -o $@ $<

sunriset.o: sunriset.c
	$(CC) $(CFLAGS_OBJ) $(ASTRO_FLOAT_FLAGS) -o $@ $<

moon.o: moon.c
	$(CC) $(CFLAGS_OBJ) $(ASTRO_FLOAT_FLAGS) -o $@ $<

astro.o: astro.c
	$(CC) $(CFLAGS_OBJ) $(ASTRO_FLOAT_FLAGS) -o $@ $<

miniz.o: miniz.c
	$(CC) $(CFLAGS_OBJ) -o $@ $<

network.o: network.c
	$(CC) $(CFLAGS_OBJ) -o $@ $<

net.o: net.c
	$(CC) $(CFLAGS_OBJ) -o $@ $<

curses.o: curses.c
	$(CC) $(COMMON_FLAGS) $(NCURSES_INCDIR) -DNCURSES_DLL -DLUA_BUILD_AS_DLL -DHAVE_NCURSES_H -c -o $@ $<

dcastro.o: dcastro.c
	$(CC) $(CFLAGS_OBJ) -fno-fast-math $(ASTRO_FLOAT_FLAGS) -o $@ $<

# --- Targeted Clean ---
clean:
	rm -f $(OBJS)

.PHONY: all clean distclean
