#define numcuckoo_c
#define LUA_LIB

/* This file has largely been generated by Gemini AI, put to the public domain. Initiated January 04, 2026.
   Fixed May 22, 2026.
   Additions by a_walz are:
   - Checks for memory allocation errors when resizing,
   - Agena C package functions and metamethods.

   Savings according to Gemini AI:
   - Agena Set: Each entry is ~24 bytes.
   - Classic C Array: Each entry is 8 bytes (64 bits).
   - This Cuckoo Filter: Each entry is 4 bytes (32-bit fingerprint).
   - The Saving: You save around 45% of your memory.

   The chance for false positives is 0.000000186%. */

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>  /* for memcpy */

#include "agena.h"

#include "agenalib.h"
#include "agnhlps.h"
#include "agnxlib.h"

#define checknumcuckoo(L,n) (DoubleCuckoo *)luaL_checkudata(L, n, AGENA_NUMCUCKOOLIBNAME)
#define isnumcuckoo(L,n)    (luaL_isudata(L, n, AGENA_NUMCUCKOOLIBNAME) && agn_isutypeset(L, n))


/* * CONFIGURATION
 * 4 slots per bucket allows for a maximum of ~95% load factor. But see below.
 * MAX_KICKS prevents infinite loops during high congestion.
 */
#define DCF_SLOTS_PER_BUCKET 4
#define DCF_MAX_KICKS 500

/* Aim for 80% load factor to keep kick chains extremely short */
#define DCF_LOAD_FACTOR_LIMIT 0.80

typedef struct {
  uint32_t *buckets;  /* 7.5.12 upgrade from uint16_t's */
  /* `capacity` is the number of buckets, must be a power of 2; to be multiplied by DCF_SLOTS_PER_BUCKET
     to get the current total number of cells in use by the filter */
  size_t capacity;
  size_t count;
  int kicks;
  uint32_t rng_state;  /* 7.5.12 change */
} DoubleCuckoo;

/* --- Internal Helpers --- */

/* Do NOT PLAY around with hashes, you might degrade the quality significantly. This implementation below
   works best both when inserting and deleting values from a filter. 7.5.12. */
static uint64_t dcf_hash (double val) {
  /* DO NOT CHANGE ! */
  uint64_t u;
  val += 0.0;
  memcpy(&u, &val, sizeof(u));
  /* Salted SplitMix64 */
  u ^= 0x9e3779b97f4a7c15ULL; /* Seed/Salt */
  u = (u^(u >> 30))*0xbf58476d1ce4e5b9ULL;
  u = (u^(u >> 27))*0x94d049bb133111ebULL;
  return u^(u >> 31);
}

static uint32_t dcf_fingerprint (double val) {
  /* Use a full 32-bit hash as the fingerprint */
  return (uint32_t)dcf_hash(val);
}

static uint32_t dcf_fingerprint32 (double val) {
  uint64_t h = dcf_hash(val);
  uint32_t fp = (uint32_t)(h ^ (h >> 32));
  return fp == 0 ? 1 : fp;  /* 0 is reserved for 'Empty' */
}

/* Correct implementation: Always pass capacity explicitly */
static size_t dcf_alt_index (size_t i, uint32_t fp, size_t capacity) {
  /* Use a more robust avalanche for 32-bit mixing */
  uint32_t h = fp;
  h ^= h >> 16;
  h *= 0x85ebca6b;
  h ^= h >> 13;
  h *= 0xc2b2ae35;
  h ^= h >> 16;
  return (i ^ (size_t)h) & (capacity - 1);
}


/* --- Core Functions --- */

/* do not call the function via the Agena C API, instead allocate memory and initialise
   DoubleCuckoo fields directly. */
DoubleCuckoo *dcf_create (size_t bucket_count) {
  size_t cap = 8;
  while (cap < bucket_count) cap <<= 1;
  DoubleCuckoo *filter = (DoubleCuckoo*)calloc(1, sizeof(DoubleCuckoo));
  if (!filter) return NULL;
  filter->buckets = (uint32_t*)calloc(cap * DCF_SLOTS_PER_BUCKET, sizeof(uint32_t));
  if (!filter->buckets) return NULL;  /* 7.3.4 fix */
  filter->capacity = cap;
  filter->count = 0;
  filter->kicks = DCF_MAX_KICKS;
  filter->rng_state = 0xACE1u;
  return filter;
}

static size_t dcf_hash_fp_to_index (uint32_t fp, size_t capacity) {
  /* This must match the index calculation used in dcf_resize */
  uint64_t h = (uint64_t)fp * 0x5bd1e995;
  return (size_t)(h & (capacity - 1));
}

bool dcf_contains (DoubleCuckoo *filter, double val) {
  int s;
  uint32_t fp = dcf_fingerprint(val);
  /* Calculate the two possible buckets for this fingerprint */
  size_t i1 = dcf_hash_fp_to_index(fp, filter->capacity);
  size_t i2 = dcf_alt_index(i1, fp, filter->capacity);
  /* Check bucket i1 */
  for (s=0; s < DCF_SLOTS_PER_BUCKET; s++) {
    if (filter->buckets[i1 * DCF_SLOTS_PER_BUCKET + s] == fp) return true;
  }
  /* Check bucket i2 */
  for (s=0; s < DCF_SLOTS_PER_BUCKET; s++) {
    if (filter->buckets[i2 * DCF_SLOTS_PER_BUCKET + s] == fp) return true;
  }
  return false;
}

/* internal raw insertion used by public insert and resize */
static bool dcf_insert_fp_raw (DoubleCuckoo *filter, uint32_t fp, size_t i) {
  int k, s;
  size_t curr_i = i;
  for (k=0; k < filter->kicks; k++) {
    for (s=0; s < DCF_SLOTS_PER_BUCKET; s++) {
      size_t idx = curr_i * DCF_SLOTS_PER_BUCKET + s;
      if (filter->buckets[idx] == 0) {
        filter->buckets[idx] = fp;
        filter->count++;
        return true;
      }
    }
    /* Kick a random slot */
    filter->rng_state = filter->rng_state * 1103515245 + 12345;
    int q = (int)((filter->rng_state >> 16) % DCF_SLOTS_PER_BUCKET);
    size_t victim_idx = curr_i * DCF_SLOTS_PER_BUCKET + q;
    uint32_t temp_fp = filter->buckets[victim_idx];
    filter->buckets[victim_idx] = fp;
    fp = temp_fp;
    curr_i = dcf_alt_index(curr_i, fp, filter->capacity);
  }
  return false;
}

int dcf_resize (DoubleCuckoo *filter);

int dcf_insert (DoubleCuckoo *filter, double val) {
  uint32_t fp = dcf_fingerprint(val);
  if (dcf_contains(filter, val)) return 1;
  /* Calculate threshold based on total slots */
  size_t total_slots = filter->capacity * DCF_SLOTS_PER_BUCKET;
  size_t threshold = (size_t)(total_slots * DCF_LOAD_FACTOR_LIMIT);
  /* Check if we are approaching the limit */
  if (filter->count >= threshold) {
    if (!dcf_resize(filter)) return 0; /* Resize failed */
  }
  size_t i = dcf_hash_fp_to_index(fp, filter->capacity);
  if (dcf_insert_fp_raw(filter, fp, i)) return 1;
  /* If we fail even after resize, the filter is genuinely saturated */
  return 0;
}

int dcf_resize (DoubleCuckoo *filter) {
  size_t i, start_i;
  size_t old_cap = filter->capacity;
  uint32_t *old_buckets = filter->buckets;
  size_t new_cap = old_cap << 1;
  uint32_t *new_buckets = (uint32_t*)calloc(new_cap * DCF_SLOTS_PER_BUCKET, sizeof(uint32_t));
  if (!new_buckets) return 0;
  /* Temporarily point to the new buckets to attempt migration */
  filter->buckets = new_buckets;
  filter->capacity = new_cap;
  filter->count = 0;
  filter->rng_state = 0xACE1u;
  for (i=0; i < old_cap * DCF_SLOTS_PER_BUCKET; i++) {
    if (old_buckets[i] != 0) {
      /* Re-insert using kicking logic */
      start_i = dcf_hash_fp_to_index(old_buckets[i], new_cap);
      if (!dcf_insert_fp_raw(filter, old_buckets[i], start_i)) {
        /* FAILURE: Roll back */
        free(new_buckets);
        filter->buckets = old_buckets;
        filter->capacity = old_cap;
        return 0;
      }
    }
  }
  free(old_buckets);
  return 1;
}

bool dcf_remove (DoubleCuckoo *filter, double val) {
  int i, s;
  uint32_t fp = dcf_fingerprint(val); /* Upgraded to 32-bit as discussed */
  size_t i1 = dcf_hash_fp_to_index(fp, filter->capacity);
  size_t i2 = dcf_alt_index(i1, fp, filter->capacity);
  size_t indices[2] = {i1, i2};
  for (i=0; i < 2; i++) {
    for (s=0; s < DCF_SLOTS_PER_BUCKET; s++) {
      size_t idx = indices[i] * DCF_SLOTS_PER_BUCKET + s;
      if (filter->buckets[idx] == fp) {
        filter->buckets[idx] = 0;
        /* Ensure we never go below zero */
        if (filter->count > 0) {
          filter->count--;
        }
        return true;
      }
    }
  }
  return false;
}

void dcf_free (DoubleCuckoo *filter) {  /* do not call this via the Agena C API as it would also free the
  userdata object itself, causing problems with memory managers, especially under DOS, probably OS/2. */
  if (!filter) return;
  if (filter->buckets) {
    xfree(filter->buckets);  /* prevent second free of the array */
  }
  free(filter);
}


/* Agena C Functions ****************************************************************/

static int numcuckoo_new (lua_State *L) {
  uint32_t n = tools_nextpow2u32(agnL_optposint(L, 1, 8));  /* smallest power of 2 greater than or equal x, 7.5.11 change */
  int kicks = agnL_optposint(L, 2, DCF_MAX_KICKS);
  DoubleCuckoo *u = (DoubleCuckoo *)lua_newuserdata(L, sizeof(DoubleCuckoo));
  u->buckets = (uint32_t*)calloc(n * DCF_SLOTS_PER_BUCKET, sizeof(uint32_t));
  if (u->buckets == NULL) {
    agn_poptop(L);
    luaL_error(L, "Error in " LUA_QS ": memory allocation failed.", "numcuckoo.new");
  }
  u->capacity = n;
  u->count = 0;
  u->kicks = kicks;
  u->rng_state = 0xACE1u;
  lua_setmetatabletoobject(L, -1, AGENA_NUMCUCKOOLIBNAME, 1);
  return 1;
}


static int numcuckoo_include (lua_State *L) {
  if (!dcf_insert(checknumcuckoo(L, 1), agn_checknumber(L, 2)))
    luaL_error(L, "Error in " LUA_QS ": memory allocation failed.", "numcuckoo.include");
  return 0;
}


static int numcuckoo_remove (lua_State *L) {
  lua_pushboolean(L, dcf_remove(checknumcuckoo(L, 1), agn_checknumber(L, 2)));
  return 1;
}


static int numcuckoo_find (lua_State *L) {
  lua_pushboolean(L, dcf_contains(checknumcuckoo(L, 1), agn_checknumber(L, 2)));
  return 1;
}


/* Returns a value between 0.0 and 1.0 representing how full the filter is.
   0.50 means the filter is 50% occupied. */
static double dcf_load_factor (DoubleCuckoo *filter) {
  if (filter->capacity == 0) return 0.0;
  size_t total_slots = filter->capacity*DCF_SLOTS_PER_BUCKET;
  return (double)filter->count/(double)total_slots;
}

static int numcuckoo_attrib (lua_State *L) {
  DoubleCuckoo *u = checknumcuckoo(L, 1);
  lua_createtable(L, 0, 6);
  lua_rawsetstringnumber(L, -1, "count",   u->count);
  lua_rawsetstringnumber(L, -1, "buckets", u->capacity);
  lua_rawsetstringnumber(L, -1, "slotsperbucket", DCF_SLOTS_PER_BUCKET);
  lua_rawsetstringnumber(L, -1, "cells",   u->capacity*DCF_SLOTS_PER_BUCKET);
  lua_rawsetstringnumber(L, -1, "load",    dcf_load_factor(u));
  lua_rawsetstringnumber(L, -1, "bytes",   u->capacity*DCF_SLOTS_PER_BUCKET*sizeof(uint32_t) + sizeof(DoubleCuckoo));
  return 1;
}


/* Returns the high and lower unsigned 32-bit words of the SplitMix64-based hash for number x,
   plus the fingerprint of x. These are essential data used internally by the package. 6.5.11 */
static int numcuckoo_hash (lua_State *L) {
  lua_Number x = agn_checknumber(L, 1);
  uint32_t n = agnL_optuint32_t(L, 2, 0);  /* 7.1.9 change */
  uint32_t fp = dcf_fingerprint(x);
  if (agnL_optboolean(L, 3, 0)) {  /* 7.1.9 change */
    lua_pushnumber(L, n == 0 ? fp : fp % n);  /* just return the unsigned 2-byte fingerprint */
    return 1;
  } else {
    uint32_t hx, lx, fp32;
    uint64_t h = dcf_hash(x);
    luaL_checkstack(L, 4, "not enough stack space");
    hx = (uint32_t)(h >> 32);
    lx = (uint32_t)(h & 0xFFFFFFFF);
    fp32 = dcf_fingerprint32(x);
    if (n == 0) {
      lua_pushnumber(L, (lua_Number)hx);          /* high */
      lua_pushnumber(L, (lua_Number)lx);          /* low */
      lua_pushnumber(L, (lua_Number)fp);          /* unsigned 16-bit fingerprint */
      lua_pushnumber(L, (lua_Number)fp32);        /* unsigned 32-bit fingerprint */
    } else {
      lua_pushnumber(L, (lua_Number)(hx % n));    /* high */
      lua_pushnumber(L, (lua_Number)(lx % n));    /* low */
      lua_pushnumber(L, (lua_Number)(fp % n));    /* unsigned 16-bit fingerprint */
      lua_pushnumber(L, (lua_Number)(fp32 % n));  /* unsigned 32-bit fingerprint */
    }
    return 4;
  }
}


static int mt_gc (lua_State *L) {  /* __gc method */
  DoubleCuckoo *u = checknumcuckoo(L, 1);
  /* remove read-only mode if set */
  agn_udfreeze(L, 1, 0);
  /* delete metatable and user-defined type */
  lua_setmetatabletoobject(L, 1, NULL, 1);
  if (u && u->buckets) {
    xfree(u->buckets);  /* prevent second free of the array */
  }
  return 0;
}


static int mt_in (lua_State *L) {
  DoubleCuckoo *u = checknumcuckoo(L, 2);
  lua_pushboolean(L, dcf_contains(u, agn_checknumber(L, 1)));
  return 1;
}


static int mt_notin (lua_State *L) {
  DoubleCuckoo *u = checknumcuckoo(L, 2);
  lua_pushboolean(L, !dcf_contains(u, agn_checknumber(L, 1)));
  return 1;
}


static int mt_empty (lua_State *L) {
  DoubleCuckoo *u = checknumcuckoo(L, 1);
  lua_pushboolean(L, u->count == 0);
  return 1;
}


static int mt_filled (lua_State *L) {
  DoubleCuckoo *u = checknumcuckoo(L, 1);
  lua_pushboolean(L, u->count != 0);
  return 1;
}


static int mt_getsize (lua_State *L) {
  DoubleCuckoo *u = checknumcuckoo(L, 1);
  lua_pushinteger(L, u->count);
  return 1;
}


static int mt_u2string (lua_State *L) {  /* at the console, the array is formatted as follows: */
  DoubleCuckoo *u = checknumcuckoo(L, 1);
  if (agn_getutype(L, 1)) {
    lua_pushfstring(L, "(%u)", u->count);
    lua_concat(L, 2);
  } else
    luaL_error(L, "Error in " LUA_QS ": invalid cuckoo filter.", "numcuckoo.__tostring");
  return 1;
}


static const struct luaL_Reg numcuckoo_lib [] = {  /* metamethods for numeric userdata `n` */
  {"attrib",     numcuckoo_attrib},
  {"find",       numcuckoo_find},
  {"hash",       numcuckoo_hash},
  {"include",    numcuckoo_include},
  {"remove",     numcuckoo_remove},
  {"__size",     mt_getsize},   /* metamethod for `size` operator */
  {"__empty",    mt_empty},     /* metamethod for `empty` operator */
  {"__filled",   mt_filled},    /* metamethod for `filled` operator */
  {"__in",       mt_in},        /* metamethod for `in` operator */
  {"__notin",    mt_notin},     /* metamethod for `notin` operator */
  {"__tostring", mt_u2string},  /* for output at the console, e.g. print(n) */
  {"__gc",       mt_gc},        /* please do not forget garbage collection */
  {NULL, NULL}
};


static const luaL_Reg numcuckoolib[] = {
  {"attrib",     numcuckoo_attrib},
  {"find",       numcuckoo_find},
  {"hash",       numcuckoo_hash},
  {"include",    numcuckoo_include},
  {"new",        numcuckoo_new},
  {"remove",     numcuckoo_remove},
  {NULL, NULL}
};


/*
** Open numcuckoo library
*/

static void createmeta (lua_State *L) {
  luaL_newmetatable(L, AGENA_NUMCUCKOOLIBNAME);  /* create metatable */
  lua_pushvalue(L, -1);  /* push metatable */
  lua_setfield(L, -2, "__index");  /* metatable.__index = metatable */
  luaL_register(L, NULL, numcuckoo_lib);  /* methods */
}

LUALIB_API int luaopen_numcuckoo (lua_State *L) {
  createmeta(L);
  luaL_register(L, AGENA_NUMCUCKOOLIBNAME, numcuckoolib);
  return 1;
}

