#define numfilter_c
#define LUA_LIB

/* This file has largely been generated by Gemini AI, put to the public domain. Initiated January 04, 2026.
   Additions by a_walz are:
   
   - Agena C package functions and metamethods.

   Savings according to Gemini AI:
   - Agena Set: Each entry is ~24 bytes.
   - Classic C Array: Each entry is 8 bytes (64 bits).
   - This Cuckoo Filter: Each entry is 2 bytes (16-bit fingerprint).
   - The Saving: You save around 90% of your memory.

   The chance for false positives is 0.0122%.
   
   This version does not allow a filter to be resized, as this would invalidate it. Fixing this failed. 
   When preallocating enough slots, though, it is great for storing vast amounts of numbers with 16-bit 
   fingerprints, with a very low number of false positives. */

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>  /* for memcpy */

#include "agena.h"

#include "agenalib.h"
#include "agnhlps.h"
#include "agnxlib.h"

#define checknumcuckoo(L,n) (DoubleFilter *)luaL_checkudata(L, n, AGENA_NUMFILTERLIBNAME)
#define isnumcuckoo(L,n)    (luaL_isudata(L, n, AGENA_NUMFILTERLIBNAME) && agn_isutypeset(L, n))


/* * CONFIGURATION
 * 4 slots per bucket allows for ~95% load factor.
 * MAX_KICKS prevents infinite loops during high congestion.
 */
#define DF_SLOTS_PER_BUCKET 4
#define DF_MAX_KICKS 500

typedef struct {
  uint16_t *buckets;
  /* `capacity` is the number of buckets, must be a power of 2; to be multiplied by DF_SLOTS_PER_BUCKET
     to get the current total number of cells in use by the filter */
  size_t capacity;
  size_t count;
  int kicks;
} DoubleFilter;

/* --- Internal Helpers --- */

/* SplitMix64 based hash */
static uint64_t df_hash (double val) {
  uint64_t u;
  val += 0.0;  /* normalize -0.0, 7.1.9 change */
  memcpy(&u, &val, sizeof(u));
  u = (u^(u >> 30))*0xbf58476d1ce4e5b9ULL;
  u = (u^(u >> 27))*0x94d049bb133111ebULL;
  return u^(u >> 31);
}


static uint16_t df_fingerprint (double val) {
  uint64_t h = df_hash(val);
  uint16_t fp = (uint16_t)(h ^ (h >> 32));
  return fp == 0 ? 1 : fp;  /* 0 is reserved for 'Empty' */
}

static uint32_t df_fingerprint32 (double val) {
  uint64_t h = df_hash(val);
  uint32_t fp = (uint32_t)(h ^ (h >> 32));
  return fp == 0 ? 1 : fp;  /* 0 is reserved for 'Empty' */
}

/* i2 = i1 ^ hash(fingerprint) */
static size_t df_alt_index (size_t i, uint16_t fp, size_t capacity) {
  uint64_t h = df_hash((double)fp);
  return (i ^ h) & (capacity - 1);
}

/* --- Core Functions --- */

/* do not call the function via the Agena C API, instead allocate memory and initialise
   DoubleFilter fields directly. */
DoubleFilter *df_create (size_t bucket_count) {
  size_t cap = 8;
  while (cap < bucket_count) cap <<= 1;
  DoubleFilter *filter = (DoubleFilter*)malloc(sizeof(DoubleFilter));
  if (!filter) return NULL;
  filter->buckets = (uint16_t*)calloc(cap * DF_SLOTS_PER_BUCKET, sizeof(uint16_t));
  if (!filter->buckets) return NULL;  /* 7.3.4 fix */
  filter->capacity = cap;
  filter->count = 0;
  filter->kicks = DF_MAX_KICKS;
  return filter;
}

bool df_contains (DoubleFilter *filter, double val) {
  int s;
  uint16_t fp = df_fingerprint(val);
  size_t i1 = df_hash(val) & (filter->capacity - 1);
  size_t i2 = df_alt_index(i1, fp, filter->capacity);
  for (s=0; s < DF_SLOTS_PER_BUCKET; s++) {
    if (filter->buckets[i1 * DF_SLOTS_PER_BUCKET + s] == fp) return true;
    if (filter->buckets[i2 * DF_SLOTS_PER_BUCKET + s] == fp) return true;
  }
  return false;
}

/* internal raw insertion used by public insert and resize */
static bool df_insert_fp_raw (DoubleFilter *filter, uint16_t fp, size_t i1) {
  int k, q, s;
  size_t idx, index, cur_i = i1;
  for (k=0; k < filter->kicks; k++) {
    /* try to find an empty slot */
    for (s=0; s < DF_SLOTS_PER_BUCKET; s++) {
      idx = cur_i * DF_SLOTS_PER_BUCKET + s;
      if (filter->buckets[idx] == 0) {
        filter->buckets[idx] = fp;
        filter->count++;
        return true;
      }
    }
    /* no empty slot: kick a random resident */
    q = rand() % DF_SLOTS_PER_BUCKET;
    index = cur_i * DF_SLOTS_PER_BUCKET + q;
    uint16_t temp_fp = filter->buckets[index];
    filter->buckets[index] = fp;
    fp = temp_fp;
    cur_i = df_alt_index(cur_i, fp, filter->capacity);
  }
  return false;
}

int df_insert (DoubleFilter *filter, double val) {
  if (df_contains(filter, val)) return 1;
  uint16_t fp = df_fingerprint(val);
  size_t i1 = df_hash(val) & (filter->capacity - 1);
  if (df_insert_fp_raw(filter, fp, i1)) return 1;
  return 0;
}

void df_free (DoubleFilter *filter) {  /* do not call this via the Agena C API as it would also free the
  userdata object itself, causing problems with memory managers, especially under DOS, probably OS/2. */
  if (!filter) return;
  if (filter->buckets) {
    xfree(filter->buckets);  /* prevent second free of the array */
  }
  free(filter);
}


/* Agena C Functions ****************************************************************/

static int numfilter_new (lua_State *L) {
  uint32_t n = tools_nextpow2u32(agnL_optposint(L, 1, 8));  /* smallest power of 2 greater than or equal x */
  int kicks = agnL_optposint(L, 2, DF_MAX_KICKS);
  DoubleFilter *u = (DoubleFilter *)lua_newuserdata(L, sizeof(DoubleFilter));
  u->buckets = (uint16_t*)calloc(n * DF_SLOTS_PER_BUCKET, sizeof(uint16_t));
  if (u->buckets == NULL) {
    agn_poptop(L);
    luaL_error(L, "Error in " LUA_QS ": memory allocation failed.", "numfilter.new");
  }
  u->capacity = n;
  u->count = 0;
  u->kicks = kicks;
  lua_setmetatabletoobject(L, -1, AGENA_NUMFILTERLIBNAME, 1);
  return 1;
}


static int numfilter_include (lua_State *L) {
  if (!df_insert(checknumcuckoo(L, 1), agn_checknumber(L, 2)))
    luaL_error(L, "Error in " LUA_QS ": filter is full.", "numfilter.include");
  return 0;
}


static int numfilter_find (lua_State *L) {
  lua_pushboolean(L, df_contains(checknumcuckoo(L, 1), agn_checknumber(L, 2)));
  return 1;
}


/* Returns a value between 0.0 and 1.0 representing how full the filter is.
   0.50 means the filter is 50% occupied. */
static double df_load_factor (DoubleFilter *filter) {
  if (filter->capacity == 0) return 0.0;
  size_t total_slots = filter->capacity*DF_SLOTS_PER_BUCKET;
  return (double)filter->count/(double)total_slots;
}

static int numfilter_attrib (lua_State *L) {
  DoubleFilter *u = checknumcuckoo(L, 1);
  lua_createtable(L, 0, 6);
  lua_rawsetstringnumber(L, -1, "count",   u->count);
  lua_rawsetstringnumber(L, -1, "buckets", u->capacity);
  lua_rawsetstringnumber(L, -1, "slotsperbucket", DF_SLOTS_PER_BUCKET);
  lua_rawsetstringnumber(L, -1, "cells",   u->capacity*DF_SLOTS_PER_BUCKET);
  lua_rawsetstringnumber(L, -1, "load",    df_load_factor(u));
  lua_rawsetstringnumber(L, -1, "bytes",   u->capacity*DF_SLOTS_PER_BUCKET*sizeof(uint16_t) + sizeof(DoubleFilter));
  return 1;
}


/* Returns the high and lower unsigned 32-bit words of the SplitMix64-based hash for number x,
   plus the fingerprint of x. These are essential data used internally by the package. 6.5.11 */
static int numfilter_hash (lua_State *L) {
  lua_Number x = agn_checknumber(L, 1);
  uint32_t n = agnL_optuint32_t(L, 2, 0);  /* 7.1.9 change */
  uint16_t fp = df_fingerprint(x);
  if (agnL_optboolean(L, 3, 0)) {  /* 7.1.9 change */
    lua_pushnumber(L, n == 0 ? fp : fp % n);  /* just return the unsigned 2-byte fingerprint */
    return 1;
  } else {
    uint32_t hx, lx, fp32;
    uint64_t h = df_hash(x);
    luaL_checkstack(L, 4, "not enough stack space");
    hx = (uint32_t)(h >> 32);
    lx = (uint32_t)(h & 0xFFFFFFFF);
    fp32 = df_fingerprint32(x);
    if (n == 0) {
      lua_pushnumber(L, (lua_Number)hx);          /* high */
      lua_pushnumber(L, (lua_Number)lx);          /* low */
      lua_pushnumber(L, (lua_Number)fp);          /* unsigned 16-bit fingerprint */
      lua_pushnumber(L, (lua_Number)fp32);        /* unsigned 32-bit fingerprint */
    } else {
      lua_pushnumber(L, (lua_Number)(hx % n));    /* high */
      lua_pushnumber(L, (lua_Number)(lx % n));    /* low */
      lua_pushnumber(L, (lua_Number)(fp % n));    /* unsigned 16-bit fingerprint */
      lua_pushnumber(L, (lua_Number)(fp32 % n));  /* unsigned 32-bit fingerprint */
    }
    return 4;
  }
}


static int mt_gc (lua_State *L) {  /* __gc method */
  DoubleFilter *u = checknumcuckoo(L, 1);
  /* remove read-only mode if set */
  agn_udfreeze(L, 1, 0);
  /* delete metatable and user-defined type */
  lua_setmetatabletoobject(L, 1, NULL, 1);
  if (u && u->buckets) {
    xfree(u->buckets);  /* prevent second free of the array */
  }
  return 0;
}


static int mt_in (lua_State *L) {
  DoubleFilter *u = checknumcuckoo(L, 2);
  lua_pushboolean(L, df_contains(u, agn_checknumber(L, 1)));
  return 1;
}


static int mt_notin (lua_State *L) {
  DoubleFilter *u = checknumcuckoo(L, 2);
  lua_pushboolean(L, !df_contains(u, agn_checknumber(L, 1)));
  return 1;
}


static int mt_empty (lua_State *L) {
  DoubleFilter *u = checknumcuckoo(L, 1);
  lua_pushboolean(L, u->count == 0);
  return 1;
}


static int mt_filled (lua_State *L) {
  DoubleFilter *u = checknumcuckoo(L, 1);
  lua_pushboolean(L, u->count != 0);
  return 1;
}


static int mt_getsize (lua_State *L) {
  DoubleFilter *u = checknumcuckoo(L, 1);
  lua_pushinteger(L, u->count);
  return 1;
}


static int mt_u2string (lua_State *L) {  /* at the console, the array is formatted as follows: */
  DoubleFilter *u = checknumcuckoo(L, 1);
  if (agn_getutype(L, 1)) {
    lua_pushfstring(L, "(%u)", u->count);
    lua_concat(L, 2);
  } else
    luaL_error(L, "Error in " LUA_QS ": invalid number filter.", "numfilter.__tostring");
  return 1;
}


static const struct luaL_Reg numfilter_lib [] = {  /* metamethods for numeric userdata `n` */
  {"attrib",     numfilter_attrib},
  {"find",       numfilter_find},
  {"hash",       numfilter_hash},
  {"include",    numfilter_include},
  {"__size",     mt_getsize},   /* metamethod for `size` operator */
  {"__empty",    mt_empty},     /* metamethod for `empty` operator */
  {"__filled",   mt_filled},    /* metamethod for `filled` operator */
  {"__in",       mt_in},        /* metamethod for `in` operator */
  {"__notin",    mt_notin},     /* metamethod for `notin` operator */
  {"__tostring", mt_u2string},  /* for output at the console, e.g. print(n) */
  {"__gc",       mt_gc},        /* please do not forget garbage collection */
  {NULL, NULL}
};


static const luaL_Reg numfilterlib[] = {
  {"attrib",     numfilter_attrib},
  {"find",       numfilter_find},
  {"hash",       numfilter_hash},
  {"include",    numfilter_include},
  {"new",        numfilter_new},
  {NULL, NULL}
};


/*
** Open numfilter library
*/

static void createmeta (lua_State *L) {
  luaL_newmetatable(L, AGENA_NUMFILTERLIBNAME);  /* create metatable */
  lua_pushvalue(L, -1);  /* push metatable */
  lua_setfield(L, -2, "__index");  /* metatable.__index = metatable */
  luaL_register(L, NULL, numfilter_lib);  /* methods */
}

LUALIB_API int luaopen_numfilter (lua_State *L) {
  createmeta(L);
  luaL_register(L, AGENA_NUMFILTERLIBNAME, numfilterlib);
  return 1;
}

