/*
** $Id: suffix.c, initiated August 23, 2026 $
** Simple interface to libdivsufsort, created with the help of Gemini AI
** See Copyright Notice in agena.h
*/

#define suffix_c
#define LUA_LIB

#include <stdlib.h>
#include <string.h>

#include "agena.h"

#include "agenalib.h"
#include "agnxlib.h"
#include "divsufsort.h"


#define SA_SIZE sizeof(saidx_t)  /* element sizing */

/* 1. Generic Suffix Array Generator, 7.9.0, created by Gemini AI */
static int suffix_sa (lua_State *L) {
  size_t len;
  const unsigned char *str = (const unsigned char *)luaL_checklstring(L, 1, &len);
  if (len == 0) {
    lua_pushliteral(L, "");
    return 1;
  }
  if (len > (size_t)(-1)/SA_SIZE) {
    luaL_error(L, "Error in " LUA_QS ": string size exceeds maximum capacity for indexing.", "suffix.sa");
  }
  /* Allocate memory for the suffix array buffer */
  saidx_t *SA = (saidx_t *)malloc(len*SA_SIZE);
  if (!SA)
    return luaL_error(L, "Error in " LUA_QS ": memory allocation failed.", "suffix.sa");
  if (divsufsort(str, SA, (saidx_t)len) != 0) {
    free(SA);
    luaL_error(L, "Error in " LUA_QS ": libdivsufsort computation failed.", "suffix.sa");
  }
  /* Push the raw integer bytes back to Lua as an immutable binary block */
  lua_pushlstring(L, (const char *)SA, len*SA_SIZE);
  free(SA);
  return 1;
}

/* 2. Generic LCP Array Generator (O(N) Kasai Algorithm), 7.9.0, created by Gemini AI */
static int suffix_lcp (lua_State *L) {
  size_t len, sa_len, i;
  const unsigned char *str = (const unsigned char *)luaL_checklstring(L, 1, &len);
  const saidx_t *SA = (const saidx_t *)luaL_checklstring(L, 2, &sa_len);
  if (len == 0 || sa_len != len*SA_SIZE) {
    return luaL_error(L, "Error in " LUA_QS ": string, suffix array lengths mismatch alignment.", "suffix.lcp"); 
  }
  if (len > (size_t)(-1)/SA_SIZE) {
    luaL_error(L, "Error in " LUA_QS ": libdivsufsort computation failed.", "suffix.lcp");
  }
  /* allocate temporary Inverse Suffix Array (ISA) and the output LCP array */
  saidx_t *ISA = (saidx_t *)malloc(len*SA_SIZE);
  saidx_t *LCP = (saidx_t *)malloc(len*SA_SIZE);
  if (!ISA || !LCP) {
    free(ISA); free(LCP);
    luaL_error(L, "Error in " LUA_QS ": storage allocation failed for LCP pipeline.", "suffix.lcp");
  }
  /* invert Suffix Array: ISA[SA[i]] = i */
  for (i=0; i < len; i++) {
    ISA[SA[i]] = (saidx_t)i;
  }
  /* Kasai's algorithm to compute LCP in linear time */
  saidx_t k = 0;
  for (i=0; i < len; i++) {
    if (ISA[i] == (saidx_t)(len - 1)) {
      k = 0;
      continue;
    }
    size_t j = (size_t)SA[ISA[i] + 1];
    while (i + k < len && j + k < len && str[i + k] == str[j + k]) {
      k++;
    }
    LCP[ISA[i]] = k;
    if (k > 0) k--;
  }
  LCP[len - 1] = 0; /* Boundary terminator */
  /* push the raw integer bytes back to Lua */
  lua_pushlstring(L, (const char *)LCP, len*SA_SIZE);
  free(ISA);
  free(LCP);
  return 1;
}


static int aux_search (const char *text, size_t text_len, 
                       const saidx_t *SA, size_t sa_elements,
                       const char *pattern, size_t pat_len, 
                       size_t start_offset, int case_insensitive,
                       size_t *out_best_idx) {
  /* 7.9.1, generated by Gemini AI */
  if (text_len == 0 || pat_len == 0 || start_offset > text_len) return 0;
  saidx_t low = 0;
  saidx_t high = (saidx_t)sa_elements - 1;
  saidx_t match_mid_idx = -1;
  saidx_t i;
  /* Step 1: Binary search for any structural match */
  while (low <= high) {
    saidx_t mid = low + (high - low)/2;
    saidx_t text_idx = SA[mid];
    size_t suffix_len = text_len - (size_t)text_idx;
    size_t cmp_len = (suffix_len < pat_len) ? suffix_len : pat_len;
    int cmp = case_insensitive ? strncasecmp(pattern, text + text_idx, cmp_len)
                               : memcmp(pattern, text + text_idx, cmp_len);
    if (cmp == 0) {
      if (pat_len > cmp_len) {
        low = mid + 1;
      } else {
        match_mid_idx = mid;
        break;
      }
    } else if (cmp < 0) {
      high = mid - 1;
    } else {
      low = mid + 1;
    }
  }
  /* Step 2: Linear neighborhood scan for the earliest occurrence >= start_offset */
  if (match_mid_idx != -1) {
    saidx_t best_text_idx = -1;
    for (i=match_mid_idx; i >= 0; i--) {
      saidx_t text_idx = SA[i];
      int match = case_insensitive ? (strncasecmp(pattern, text + text_idx, pat_len) == 0)
                                   : (memcmp(pattern, text + text_idx, pat_len) == 0);
      if (text_len - (size_t)text_idx >= pat_len && match) {
        if ((size_t)text_idx >= start_offset) {
          if (best_text_idx == -1 || text_idx < best_text_idx) best_text_idx = text_idx;
        }
      } else { break; }
    }
    for (i=match_mid_idx + 1; i < (saidx_t)sa_elements; i++) {
      saidx_t text_idx = SA[i];
      int match = case_insensitive ? (strncasecmp(pattern, text + text_idx, pat_len) == 0)
                                   : (memcmp(pattern, text + text_idx, pat_len) == 0);
      if (text_len - (size_t)text_idx >= pat_len && match) {
        if ((size_t)text_idx >= start_offset) {
          if (best_text_idx == -1 || text_idx < best_text_idx) best_text_idx = text_idx;
        }
      } else { break; }
    }
    if (best_text_idx != -1) {
      *out_best_idx = (size_t)best_text_idx;
      return 1;  /* match found */
    }
  }
  return 0;  /* no match */
}


static int suffix_find (lua_State *L) {  /* 7.9.1, generated by Gemini AI */
  size_t text_len, sa_bytes, pat_len;
  const char *text = agn_checklstring(L, 1, &text_len);
  const char *sa_bin = agn_checklstring(L, 2, &sa_bytes);
  const char *pattern = agn_checklstring(L, 3, &pat_len);
  lua_Integer init_pos = luaL_optinteger(L, 4, 1);  /* starting position for the search */
  int nocase = agnL_optboolean(L, 5, 0);  /* case-sensitive search by default */
  if (text_len > (size_t)(-1)/sizeof(saidx_t))
    luaL_error(L, "Error in " LUA_QS ": input string is too long.", "suffix.find");
  if (init_pos < 0) init_pos = (lua_Integer)text_len + init_pos + 1;
  if (init_pos < 1) init_pos = 1;
  luaL_checkstack(L, 2, "not enough stack space");
  if (sa_bytes != text_len*sizeof(saidx_t)) goto err;
  size_t start_offset = (size_t)init_pos - 1;
  size_t best_text_idx;
  if (aux_search(text, text_len, (const saidx_t *)sa_bin, 
      text_len, pattern, pat_len, start_offset, nocase, &best_text_idx)) {
    lua_pushinteger(L, (lua_Integer)(best_text_idx + 1));
    lua_pushlstring(L, text + best_text_idx, pat_len);
    return 2;
  }
err:
  lua_pushnil(L); 
  lua_pushnil(L); 
  return 2;
}


static int finditer (lua_State *L) {  /* 7.9.1, generated by Gemini AI */
  size_t text_len, pat_len;
  const char *text = lua_tolstring(L, lua_upvalueindex(1), &text_len);
  const char *sa_bin = lua_tostring(L, lua_upvalueindex(2));
  const char *pattern = lua_tolstring(L, lua_upvalueindex(3), &pat_len);
  size_t curoffset = (size_t)lua_tointeger(L, lua_upvalueindex(4));
  int nocase = lua_toboolean(L, lua_upvalueindex(5));
  size_t best_text_idx;
  if (aux_search(text, text_len, (const saidx_t *)sa_bin, 
      text_len, pattern, pat_len, curoffset, nocase, &best_text_idx)) {
    size_t nextoffset = best_text_idx + pat_len;
    lua_pushinteger(L, (lua_Integer)nextoffset);
    lua_replace(L, lua_upvalueindex(4));  /* update Upvalue 4 */
    lua_pushinteger(L, (lua_Integer)(best_text_idx + 1));
  } else {
    lua_pushnil(L);
  }
  return 1;
}

static int suffix_gfind (lua_State *L) {  /* 7.9.1, generated by Gemini AI */
  agn_checklstring(L, 1, NULL);
  size_t text_len, sa_bytes;
  agn_checklstring(L, 1, &text_len);
  agn_checklstring(L, 2, &sa_bytes);
  agn_checklstring(L, 3, NULL);  /* the pattern */
  lua_Integer init_pos = luaL_optinteger(L, 4, 1);
  int nocase = agnL_optboolean(L, 5, 0);  /* case-sensitive search by default */
  if (sa_bytes != text_len*sizeof(saidx_t)) {
    return luaL_error(L, "Error in " LUA_QS ": suffix array alignment is invalid.", "suffix.gfind");
  }
  if (init_pos < 0) init_pos = (lua_Integer)text_len + init_pos + 1;
  if (init_pos < 1) init_pos = 1;
  size_t start_offset = (size_t)init_pos - 1;
  lua_pushvalue(L, 1);  /* Upvalue 1: Text */
  lua_pushvalue(L, 2);  /* Upvalue 2: Suffix Array binary */
  lua_pushvalue(L, 3);  /* Upvalue 3: Pattern */
  lua_pushinteger(L, (lua_Integer)start_offset);  /* Upvalue 4: Dynamic starting state */
  lua_pushboolean(L, nocase);  /* Upvalue 5: Flag */
  lua_pushcclosure(L, finditer, 5);
  return 1;
}


/* Helper comparison function for qsort */
static int compare_saidx (const void *a, const void *b) {
  saidx_t ia = *(const saidx_t *)a;
  saidx_t ib = *(const saidx_t *)b;
  return (ia > ib) - (ia < ib);
}

static int suffix_findall (lua_State *L) {  /* 7.9.0, generated by Gemini AI */
  size_t text_len, sa_bytes, pat_len;
  /* strict type enforcement to catch typos immediately */
  const char *text = luaL_checklstring(L, 1, &text_len);
  const char *sa_bin = luaL_checklstring(L, 2, &sa_bytes);
  const char *pattern = luaL_checklstring(L, 3, &pat_len);
  if (text_len > (size_t)(-1)/sizeof(saidx_t))
    luaL_error(L, "Error in " LUA_QS ": input string is too long.", "suffix.findall");
  if (text_len == 0 || pat_len == 0 || sa_bytes != text_len*sizeof(saidx_t)) {
    lua_newtable(L);
    return 1;
  }
  const saidx_t *SA = (const saidx_t *)sa_bin;
  saidx_t low = 0;
  saidx_t high = (saidx_t)text_len - 1;
  saidx_t found_sa_idx = -1;
  /* step 1: Binary search to find ANY initial match position in the SA */
  while (low <= high) {
    saidx_t mid = low + (high - low)/2;
    saidx_t text_idx = SA[mid];
    size_t suffix_len = text_len - (size_t)text_idx;
    size_t cmp_len = (suffix_len < pat_len) ? suffix_len : pat_len;
    int cmp = memcmp(pattern, text + text_idx, cmp_len);
    if (cmp == 0) {
      if (pat_len > cmp_len) {
        low = mid + 1;
      } else {
        found_sa_idx = mid; /* found an anchor point! */
        break;
      }
    } else if (cmp < 0) {
      high = mid - 1;
    } else {
      low = mid + 1;
    }
  }
  lua_newtable(L);
  if (found_sa_idx == -1) {
    return 1;  /* if no match exists, return the empty table directly */
  }
  /* step 2: Linear scan up and down to find the match boundaries */
  saidx_t start_sa = found_sa_idx;
  saidx_t end_sa = found_sa_idx;
  /* scan upwards in the sorted suffix array */
  while (start_sa > 0) {
    saidx_t text_idx = SA[start_sa - 1];
    if (text_len - text_idx >= pat_len && memcmp(pattern, text + text_idx, pat_len) == 0) {
      start_sa--;
    } else {
      break;
    }
  }
  /* scan downwards in the sorted suffix array */
  while (end_sa < (saidx_t)text_len - 1) {
    saidx_t text_idx = SA[end_sa + 1];
    if (text_len - text_idx >= pat_len && memcmp(pattern, text + text_idx, pat_len) == 0) {
      end_sa++;
    } else {
      break;
    }
  }
  /* step 3: extract match indices into a temporary buffer to sort them chronologically */
  size_t total_matches = (size_t)(end_sa - start_sa + 1);
  saidx_t *match_buffer = (saidx_t *)malloc(total_matches*sizeof(saidx_t));
  if (!match_buffer) {
    agn_poptop(L);  /* drop table pushed before */
    luaL_error(L, "Error in " LUA_QS ": storage allocation failed.", "suffix.findall");
  }
  size_t i;
  for (i=0; i < total_matches; i++) {
    match_buffer[i] = SA[start_sa + (saidx_t)i];
  }
  /* sort positions so they appear in reading order (left-to-right) */
  qsort(match_buffer, total_matches, sizeof(saidx_t), compare_saidx);
  /* step 4: populate the Lua/Agena result table */
  for (i=0; i < total_matches; i++) {
    /* convert 0-based C index to 1-based native Agena string index */
    lua_pushinteger(L, (lua_Integer)(match_buffer[i] + 1));
    lua_rawseti(L, -2, (int)(i + 1));
  }
  free(match_buffer);
  return 1;
}


static int suffix_count (lua_State *L) {  /* 7.9.0, generated by Gemini AI */
  size_t text_len, sa_bytes, pat_len;
  saidx_t i;
  const char *text = luaL_checklstring(L, 1, &text_len);
  const char *sa_bin = luaL_checklstring(L, 2, &sa_bytes);
  const char *pattern = luaL_checklstring(L, 3, &pat_len);
  /* 4th argument: optional 1-based starting position (default to 1), 7.9.1 */
  lua_Integer init_pos = luaL_optinteger(L, 4, 1);
  if (text_len > (size_t)(-1)/sizeof(saidx_t))
    luaL_error(L, "Error in " LUA_QS ": input string is too long.", "suffix.count");
  if (init_pos < 0) {
    init_pos = (lua_Integer)text_len + init_pos + 1;
  }
  if (init_pos < 1) {
    init_pos = 1;
  }
  /* if the text or pattern is empty, or the start position exceeds text boundaries */
  if (text_len == 0 || pat_len == 0 || (size_t)init_pos > text_len || sa_bytes != text_len*sizeof(saidx_t)) {
    lua_pushinteger(L, 0);
    return 1;
  }
  /* Convert 1-based Agena index to 0-based C offset */
  size_t start_offset = (size_t)init_pos - 1;
  const saidx_t *SA = (const saidx_t *)sa_bin;
  saidx_t low = 0, high = (saidx_t)text_len - 1;
  saidx_t first_idx = -1, last_idx = -1;
  /* binary search 1: find the first (leftmost) occurrence in SA */
  while (low <= high) {
    saidx_t mid = low + (high - low)/2;
    saidx_t text_idx = SA[mid];
    size_t suffix_len = text_len - (size_t)text_idx;
    size_t cmp_len = (suffix_len < pat_len) ? suffix_len : pat_len;
    int cmp = memcmp(pattern, text + text_idx, cmp_len);
    if (cmp == 0 && pat_len <= suffix_len) {
      first_idx = mid;
      high = mid - 1;  /* keep searching left */
    } else if (cmp <= 0) {
      high = mid - 1;
    } else {
      low = mid + 1;
    }
  }
  if (first_idx == -1) {  /* if it doesn't exist, count is 0 */
    lua_pushinteger(L, 0);
    return 1;
  }
  /* binary search 2: find the last (rightmost) occurrence in SA */
  low = first_idx; high = (saidx_t)text_len - 1;
  while (low <= high) {
    saidx_t mid = low + (high - low)/2;
    saidx_t text_idx = SA[mid];
    size_t suffix_len = text_len - (size_t)text_idx;
    size_t cmp_len = (suffix_len < pat_len) ? suffix_len : pat_len;
    int cmp = memcmp(pattern, text + text_idx, cmp_len);
    if (cmp == 0 && pat_len <= suffix_len) {
      last_idx = mid;
      low = mid + 1;  /* keep searching right */
    } else if (cmp <= 0) {
      high = mid - 1;
    } else {
      low = mid + 1;
    }
  }
  /* filter matching blocks to calculate the valid subset count */
  lua_Integer valid_count = 0;
  for (i=first_idx; i <= last_idx; i++) {
    if ((size_t)SA[i] >= start_offset) {
      valid_count++;
    }
  }
  lua_pushinteger(L, valid_count);
  return 1;
}


static int suffix_autocomplete (lua_State *L) {
  size_t text_len, sa_bytes, pre_len, delim_len = 0;
  /* enforce strict parameter validation for the core variables */
  const char *text = luaL_checklstring(L, 1, &text_len);
  const char *sa_bin = luaL_checklstring(L, 2, &sa_bytes);
  const char *prefix = luaL_checklstring(L, 3, &pre_len);
  /* read the optional fourth argument for custom delimiters */
  const char *delims = luaL_optlstring(L, 4, NULL, &delim_len);
  if (text_len > (size_t)(-1)/sizeof(saidx_t))
    luaL_error(L, "Error in " LUA_QS ": input string is too long.", "suffix.autocomplete");
  if (text_len == 0 || pre_len == 0 || sa_bytes != text_len*sizeof(saidx_t)) goto err;
  const saidx_t *SA = (const saidx_t *)sa_bin;
  saidx_t low = 0, high = (saidx_t)text_len - 1;
  saidx_t first_idx = -1, last_idx = -1;
  /* step 1: Binary Search for the LEFTMOST boundary matching the prefix */
  while (low <= high) {
    saidx_t mid = low + (high - low)/2;
    saidx_t text_idx = SA[mid];
    size_t suffix_len = text_len - (size_t)text_idx;
    size_t cmp_len = (suffix_len < pre_len) ? suffix_len : pre_len;
    int cmp = memcmp(prefix, text + text_idx, cmp_len);
    if (cmp == 0 && pre_len <= suffix_len) {
      first_idx = mid;
      high = mid - 1;
    } else if (cmp <= 0) {
      high = mid - 1;
    } else {
      low = mid + 1;
    }
  }
  if (first_idx == -1) goto err;
  /* step 2: Binary Search for the RIGHTMOST boundary matching the prefix */
  low = first_idx;
  high = (saidx_t)text_len - 1;
  while (low <= high) {
    saidx_t mid = low + (high - low)/2;
    saidx_t text_idx = SA[mid];
    size_t suffix_len = text_len - (size_t)text_idx;
    size_t cmp_len = (suffix_len < pre_len) ? suffix_len : pre_len;
    int cmp = memcmp(prefix, text + text_idx, cmp_len);
    if (cmp == 0 && pre_len <= suffix_len) {
      last_idx = mid;
      low = mid + 1;
    } else if (cmp <= 0) {
      high = mid - 1;
    } else {
      low = mid + 1;
    }
  }
  /* step 3: extract unique word completions */
  luaL_checkstack(L, 6, "not enough stack space");
  lua_newtable(L);
  lua_newtable(L);
  int result_count = 0;
  saidx_t i;
  for (i=first_idx; i <= last_idx; i++) {
    saidx_t text_idx = SA[i];
    /* boundary verification context check */
    if (text_idx > 0) {
      char prev_c = text[text_idx - 1];
      if (delims) {  /* if custom delimiters exist, verify the previous character was one of them */
        if (memchr(delims, prev_c, delim_len) == NULL) continue;
      } else {  /* fall back to default word bounds */
        if (!isspace((unsigned char)prev_c) && !ispunct((unsigned char)prev_c)) continue;
      }
    }
    /* scan forward from the match to find the end of the word segment */
    size_t word_len = pre_len;
    while (text_idx + word_len < text_len) {
      char c = text[text_idx + word_len];
      if (delims) {  /* break the loop if the current character matches a custom delimiter */
        if (memchr(delims, c, delim_len) != NULL) break;
      } else {  /* default break conditions */
        if (isspace((unsigned char)c) || ispunct((unsigned char)c)) break;
      }
      word_len++;
    }
    /* push, deduplicate, and record */
    lua_pushlstring(L, text + text_idx, word_len);
    lua_pushvalue(L, -1);
    lua_rawget(L, -3);
    if (lua_isnil(L, -1)) {
      lua_pop(L, 1);
      lua_pushvalue(L, -1);
      lua_pushboolean(L, 1);
      lua_rawset(L, -4);
      result_count++;
      lua_rawseti(L, -3, result_count);
    } else {
      lua_pop(L, 2);
    }
  }
  lua_pop(L, 1);
  return 1;
err:
  lua_newtable(L);
  return 1;
}


#ifndef SUFFIX_MAGIC
#define SUFFIX_MAGIC "AGN_SA01"
#endif

/* suffix.dump (filename, text, sa_bin [, lcp_bin]) -> boolean; generated by Gemini AI, 7.9.1 */
static int suffix_save (lua_State *L) {
  const char *filename = luaL_checkstring(L, 1);
  size_t text_len, sa_bytes, lcp_bytes = 0;
  const char *text = luaL_checklstring(L, 2, &text_len);
  const char *sa_bin = luaL_checklstring(L, 3, &sa_bytes);
  const char *lcp_bin = luaL_optlstring(L, 4, NULL, &lcp_bytes);
  /* Alignment sanity checks before writing (Safe to use luaL_error here) */
  if (sa_bytes != text_len * sizeof(saidx_t))
    return luaL_error(L, "Error in " LUA_QS ": suffix array size mismatches text length.", "suffix.save");
  if (lcp_bin && lcp_bytes != text_len * sizeof(saidx_t))
    return luaL_error(L, "Error in " LUA_QS ": LCP Array size mismatches text length.", "suffix.save");
  FILE *f = fopen(filename, "wb");
  if (!f) {
    /* Safe error handling: return false and an error string to Lua instead of crashing */
    lua_pushboolean(L, 0);
    lua_pushstring(L, "cannot open file for writing.");
    return 2; 
  }
  /* 1. Write file header signature */
  if (fwrite(SUFFIX_MAGIC, 1, 8, f) != 8) goto write_error;
  /* 2. Write component size lengths */
  uint64_t sizes[3];
  sizes[0] = (uint64_t)text_len;
  sizes[1] = (uint64_t)sa_bytes;
  sizes[2] = (uint64_t)lcp_bytes;
  if (fwrite(sizes, sizeof(uint64_t), 3, f) != 3) goto write_error;
  /* 3. Write raw payload data streams */
  if (text_len > 0 && fwrite(text, 1, text_len, f) != text_len) goto write_error;
  if (sa_bytes > 0 && fwrite(sa_bin, 1, sa_bytes, f) != sa_bytes) goto write_error;
  if (lcp_bin && lcp_bytes > 0) {
    if (fwrite(lcp_bin, 1, lcp_bytes, f) != lcp_bytes) goto write_error;
  }
  fclose(f);
  return 0;
write_error:
  fclose(f); /* Guaranteed cleanup of system file descriptor */
  luaL_error(L, "Error in " LUA_QS ": disk write failed or device out of space.", "suffix.save");
  return 0;
}


/* suffix.read (filename) -> text, sa_bin, lcp_bin (or nil); generated by Gemini AI, 7.9.1 */
static int suffix_read (lua_State *L) {
  const char *filename = luaL_checkstring(L, 1);
  FILE *f = fopen(filename, "rb");
  if (!f)
    return luaL_error(L, "Error in " LUA_QS ": cannot open file for reading.", "suffix.read");
  /* 1. validate header magic */
  char magic[8];
  if (fread(magic, 1, 8, f) != 8 || memcmp(magic, SUFFIX_MAGIC, 8) != 0) {
    fclose(f);
    return luaL_error(L, "Error in " LUA_QS ": index file format is invalid or signature corrupted.", "suffix.read");
  }
  /* 2. read component size lengths */
  uint64_t sizes[3];
  if (fread(sizes, sizeof(uint64_t), 3, f) != 3) {
    fclose(f);
    return luaL_error(L, "Error in " LUA_QS ": reading size metadata header failed.", "suffix.read");
  }
  size_t text_len  = (size_t)sizes[0];
  size_t sa_bytes  = (size_t)sizes[1];
  size_t lcp_bytes = (size_t)sizes[2];
  /* 3. Determine maximum layout buffer upfront to avoid variable array realloc risks */
  size_t max_buf = text_len;
  if (sa_bytes > max_buf)  max_buf = sa_bytes;
  if (lcp_bytes > max_buf) max_buf = lcp_bytes;
  /* Safe workspace buffer allocation */
  char *buffer = (char *)malloc(max_buf > 0 ? max_buf : 1);
  if (!buffer) {
    fclose(f);
    return luaL_error(L, "Error in " LUA_QS ": memory allocation failed.", "suffix.read");
  }
  luaL_checkstack(L, 3, "not enough stack space");
  /* read and push Text string */
  if (text_len > 0) {
    if (fread(buffer, 1, text_len, f) != text_len) goto load_error;
    lua_pushlstring(L, buffer, text_len);
  } else {
    lua_pushliteral(L, "");
  }
  /* read and push SA binary block */
  if (sa_bytes > 0) {
    if (fread(buffer, 1, sa_bytes, f) != sa_bytes) goto load_error;
    lua_pushlstring(L, buffer, sa_bytes);
  } else {
    lua_pushliteral(L, "");
  }
  /* read and push LCP binary block if it exists */
  if (lcp_bytes > 0) {
    if (fread(buffer, 1, lcp_bytes, f) != lcp_bytes) goto load_error;
    lua_pushlstring(L, buffer, lcp_bytes);
  } else {
    lua_pushnil(L);  /* return null for the missing LCP slot */
  }
  free(buffer);
  fclose(f);
  return 3; /* returns: text, sa_bin, lcp_bin */
load_error:
  free(buffer);
  fclose(f);
  return luaL_error(L, "Error in " LUA_QS ": unexpected end-of-file or corrupted data block.", "suffix.read");
}


static const struct luaL_Reg suffix[] = {
  /* generators */
  {"sa",           suffix_sa},            /* added on August 23, 2026 */
  {"lcp",          suffix_lcp},           /* added on August 23, 2026 */
  /* specialised functions */
  {"autocomplete", suffix_autocomplete},  /* added on August 23, 2026 */
  {"count",        suffix_count},         /* added on August 23, 2026 */
  {"find",         suffix_find},          /* added on August 23, 2026 */
  {"findall",      suffix_findall},       /* added on August 23, 2026 */
  {"gfind",        suffix_gfind},         /* added on August 24, 2026 */
  {"read",         suffix_read},          /* added on August 24, 2026 */
  {"save",         suffix_save},          /* added on August 24, 2026 */
  {NULL,  NULL}
};


/*
** Open suffix library
*/

int luaopen_suffix (lua_State *L) {
  luaL_register(L, "suffix", suffix);
  return 1;
}

